$gwx_XC_36=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx_XC_36 || [];
function gz$gwx_XC_36_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx_XC_36_1)return __WXML_GLOBAL__.ops_cached.$gwx_XC_36_1
__WXML_GLOBAL__.ops_cached.$gwx_XC_36_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([[7],[3,'theme']])
Z([3,'onChooseAvatar'])
Z([3,'avatar-wrapper'])
Z([3,'chooseAvatar'])
Z([3,'avatar'])
Z([[7],[3,'avatarUrl']])
Z([3,'tui-set-box'])
Z([3,'tui-mtop'])
Z([1,false])
Z([3,'editNickname'])
Z([1,true])
Z([3,'tui-item-box'])
Z([3,'tui-logo'])
Z([3,'widthFix'])
Z([3,'https://qianyufang.top/public/yingyu/images/my/nickname.png'])
Z([3,'tui-list-cell_name'])
Z([3,'我的昵称'])
Z([3,'tui-right'])
Z([3,'cu-capsule'])
Z([3,'tui-list-cell_name  text-xl'])
Z([a,[[7],[3,'nickName']]])
Z(z[7])
Z([a,[3,' '],z[10]])
Z(z[10])
Z(z[11])
Z(z[12])
Z(z[13])
Z([3,'https://qianyufang.top/public/yingyu/images/my/birth.png'])
Z(z[15])
Z([3,'出生年月'])
Z(z[17])
Z([3,'bindDateChange'])
Z([[7],[3,'date_today']])
Z([3,'month'])
Z([3,'date'])
Z([3,'2010-01-01'])
Z([[7],[3,'birth']])
Z([3,'picker'])
Z([a,[[7],[3,'birth']]])
Z(z[7])
Z(z[8])
Z(z[10])
Z(z[11])
Z(z[12])
Z(z[13])
Z([3,'https://qianyufang.top/public/yingyu/images/my/shenfen.png'])
Z(z[15])
Z([3,'我的身份'])
Z(z[17])
Z(z[18])
Z([3,'selectParent'])
Z([a,[3,'cu-tag '],[[2,'?:'],[[2,'=='],[[7],[3,'parent']],[1,1]],[1,'bg-macron'],[1,'line-macron']]])
Z([3,'1'])
Z([3,'爸爸'])
Z(z[50])
Z([a,z[51][1],[[2,'?:'],[[2,'=='],[[7],[3,'parent']],[1,2]],[1,'bg-macron'],[1,'line-macron']]])
Z([3,'2'])
Z([3,'妈妈'])
Z(z[50])
Z([a,z[51][1],[[2,'?:'],[[2,'=='],[[7],[3,'parent']],[1,3]],[1,'bg-macron'],[1,'line-macron']]])
Z([3,'3'])
Z([3,'宝宝'])
Z(z[50])
Z([a,z[51][1],[[2,'?:'],[[2,'=='],[[7],[3,'parent']],[1,4]],[1,'bg-macron'],[1,'line-macron']]])
Z([3,'4'])
Z([3,'老师'])
Z(z[7])
Z(z[8])
Z(z[10])
Z(z[11])
Z(z[12])
Z(z[13])
Z([3,'https://qianyufang.top/public/yingyu/images/my/family.png'])
Z(z[15])
Z([3,'家庭成员'])
Z(z[17])
Z(z[18])
Z([[7],[3,'family']])
Z([3,'index'])
Z([3,'margin-left'])
Z([[2,'=='],[[6],[[7],[3,'item']],[3,'parent']],[1,0]])
Z([3,'circle'])
Z([3,'未知'])
Z([[2,'=='],[[6],[[7],[3,'item']],[3,'parent']],[1,1]])
Z(z[81])
Z(z[53])
Z([[2,'=='],[[6],[[7],[3,'item']],[3,'parent']],[1,2]])
Z(z[81])
Z(z[57])
Z([[2,'=='],[[6],[[7],[3,'item']],[3,'parent']],[1,3]])
Z(z[81])
Z(z[61])
Z([[2,'=='],[[6],[[7],[3,'item']],[3,'parent']],[1,4]])
Z(z[81])
Z(z[65])
Z([[2,'!='],[[7],[3,'vip']],[1,0]])
Z(z[7])
Z(z[8])
Z([3,'true'])
Z(z[11])
Z(z[12])
Z(z[13])
Z([3,'https://qianyufang.top/public/yingyu/images/my/vip1.png'])
Z(z[15])
Z([a,[[7],[3,'vipTitle']]])
Z(z[17])
Z([[2,'=='],[[7],[3,'vip']],[[2,'-'],[1,2]]])
Z([a,[3,'已到期 '],[[7],[3,'time']]])
Z([a,[3,'已于'],z[107][2],[3,' 生效']])
Z([[2,'=='],[[7],[3,'is_share']],[1,false]])
Z(z[7])
Z([[2,'=='],[[7],[3,'main_user']],[1,true]])
Z([[2,'<'],[[6],[[7],[3,'family']],[3,'length']],[1,3]])
Z([3,'bg-macron'])
Z([3,'share'])
Z([3,'width:80%;'])
Z([3,'邀请家庭成员共享账号'])
Z([[2,'>'],[[6],[[7],[3,'family']],[3,'length']],[1,1]])
Z([3,'margin-top-xl'])
Z([3,'unbind'])
Z([3,'bg-green'])
Z(z[115])
Z([3,'我要解绑其他共享账号'])
Z(z[119])
Z(z[120])
Z(z[115])
Z([3,'我要解绑此账号，不再共享'])
Z(z[118])
Z([3,'back'])
Z([3,'bg-blue'])
Z(z[115])
Z([3,'返回'])
Z([3,'tui-page__hd'])
Z([3,'tui-page__title'])
Z([3,'Tips'])
Z([3,'tui-page__desc'])
Z([a,[3,'1.每个'],[[2,'?:'],[[2,'!='],[[7],[3,'vip']],[1,0]],[1,'会员'],[1,'']],[3,'账号最多可以三个微信共享']])
Z(z[135])
Z([3,'2.点击橙色按钮转发给家人，对方打开后即可共享'])
Z(z[135])
Z([3,'3.学习打卡数据家庭内部成员可见，实时同步更新'])
Z(z[118])
Z([3,'goHome'])
Z(z[113])
Z([3,'width:60%;'])
Z([3,'查看宝宝的学习记录'])
})(__WXML_GLOBAL__.ops_cached.$gwx_XC_36_1);return __WXML_GLOBAL__.ops_cached.$gwx_XC_36_1
}
__WXML_GLOBAL__.ops_set.$gwx_XC_36=z;
__WXML_GLOBAL__.ops_init.$gwx_XC_36=true;
var x=['./pages/set/set.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx_XC_36_1()
var a4WC=_n('view')
_rz(z,a4WC,'data-weui-theme',0,e,s,gg)
var t5WC=_mz(z,'button',['bind:chooseavatar',1,'class',1,'openType',2],[],e,s,gg)
var e6WC=_mz(z,'image',['class',4,'src',1],[],e,s,gg)
_(t5WC,e6WC)
_(a4WC,t5WC)
_(r,a4WC)
var b7WC=_n('view')
_rz(z,b7WC,'class',6,e,s,gg)
var o0WC=_n('view')
_rz(z,o0WC,'class',7,e,s,gg)
var fAXC=_mz(z,'tui-list-cell',['arrow',8,'bind:tap',1,'radius',2],[],e,s,gg)
var cBXC=_n('view')
_rz(z,cBXC,'class',11,e,s,gg)
var hCXC=_mz(z,'image',['class',12,'mode',1,'src',2],[],e,s,gg)
_(cBXC,hCXC)
var oDXC=_n('text')
_rz(z,oDXC,'class',15,e,s,gg)
var cEXC=_oz(z,16,e,s,gg)
_(oDXC,cEXC)
_(cBXC,oDXC)
var oFXC=_n('view')
_rz(z,oFXC,'class',17,e,s,gg)
var lGXC=_n('view')
_rz(z,lGXC,'class',18,e,s,gg)
var aHXC=_n('text')
_rz(z,aHXC,'class',19,e,s,gg)
var tIXC=_oz(z,20,e,s,gg)
_(aHXC,tIXC)
_(lGXC,aHXC)
_(oFXC,lGXC)
_(cBXC,oFXC)
_(fAXC,cBXC)
_(o0WC,fAXC)
_(b7WC,o0WC)
var eJXC=_n('view')
_rz(z,eJXC,'class',21,e,s,gg)
var bKXC=_mz(z,'tui-list-cell',['arrow',22,'radius',1],[],e,s,gg)
var oLXC=_n('view')
_rz(z,oLXC,'class',24,e,s,gg)
var xMXC=_mz(z,'image',['class',25,'mode',1,'src',2],[],e,s,gg)
_(oLXC,xMXC)
var oNXC=_n('text')
_rz(z,oNXC,'class',28,e,s,gg)
var fOXC=_oz(z,29,e,s,gg)
_(oNXC,fOXC)
_(oLXC,oNXC)
var cPXC=_n('view')
_rz(z,cPXC,'class',30,e,s,gg)
var hQXC=_mz(z,'picker',['bindchange',31,'end',1,'fields',2,'mode',3,'start',4,'value',5],[],e,s,gg)
var oRXC=_n('view')
_rz(z,oRXC,'class',37,e,s,gg)
var cSXC=_oz(z,38,e,s,gg)
_(oRXC,cSXC)
_(hQXC,oRXC)
_(cPXC,hQXC)
_(oLXC,cPXC)
_(bKXC,oLXC)
_(eJXC,bKXC)
_(b7WC,eJXC)
var oTXC=_n('view')
_rz(z,oTXC,'class',39,e,s,gg)
var lUXC=_mz(z,'tui-list-cell',['arrow',40,'radius',1],[],e,s,gg)
var aVXC=_n('view')
_rz(z,aVXC,'class',42,e,s,gg)
var tWXC=_mz(z,'image',['class',43,'mode',1,'src',2],[],e,s,gg)
_(aVXC,tWXC)
var eXXC=_n('text')
_rz(z,eXXC,'class',46,e,s,gg)
var bYXC=_oz(z,47,e,s,gg)
_(eXXC,bYXC)
_(aVXC,eXXC)
var oZXC=_n('view')
_rz(z,oZXC,'class',48,e,s,gg)
var x1XC=_n('view')
_rz(z,x1XC,'class',49,e,s,gg)
var o2XC=_mz(z,'view',['bindtap',50,'class',1,'data-id',2],[],e,s,gg)
var f3XC=_oz(z,53,e,s,gg)
_(o2XC,f3XC)
_(x1XC,o2XC)
var c4XC=_mz(z,'view',['bindtap',54,'class',1,'data-id',2],[],e,s,gg)
var h5XC=_oz(z,57,e,s,gg)
_(c4XC,h5XC)
_(x1XC,c4XC)
var o6XC=_mz(z,'view',['bindtap',58,'class',1,'data-id',2],[],e,s,gg)
var c7XC=_oz(z,61,e,s,gg)
_(o6XC,c7XC)
_(x1XC,o6XC)
var o8XC=_mz(z,'view',['bindtap',62,'class',1,'data-id',2],[],e,s,gg)
var l9XC=_oz(z,65,e,s,gg)
_(o8XC,l9XC)
_(x1XC,o8XC)
_(oZXC,x1XC)
_(aVXC,oZXC)
_(lUXC,aVXC)
_(oTXC,lUXC)
_(b7WC,oTXC)
var a0XC=_n('view')
_rz(z,a0XC,'class',66,e,s,gg)
var tAYC=_mz(z,'tui-list-cell',['arrow',67,'radius',1],[],e,s,gg)
var eBYC=_n('view')
_rz(z,eBYC,'class',69,e,s,gg)
var bCYC=_mz(z,'image',['class',70,'mode',1,'src',2],[],e,s,gg)
_(eBYC,bCYC)
var oDYC=_n('text')
_rz(z,oDYC,'class',73,e,s,gg)
var xEYC=_oz(z,74,e,s,gg)
_(oDYC,xEYC)
_(eBYC,oDYC)
var oFYC=_n('view')
_rz(z,oFYC,'class',75,e,s,gg)
var fGYC=_n('view')
_rz(z,fGYC,'class',76,e,s,gg)
var cHYC=_v()
_(fGYC,cHYC)
var hIYC=function(cKYC,oJYC,oLYC,gg){
var aNYC=_n('view')
_rz(z,aNYC,'class',79,cKYC,oJYC,gg)
var tOYC=_v()
_(aNYC,tOYC)
if(_oz(z,80,cKYC,oJYC,gg)){tOYC.wxVkey=1
var oTYC=_n('tui-tag')
_rz(z,oTYC,'shape',81,cKYC,oJYC,gg)
var fUYC=_oz(z,82,cKYC,oJYC,gg)
_(oTYC,fUYC)
_(tOYC,oTYC)
}
var ePYC=_v()
_(aNYC,ePYC)
if(_oz(z,83,cKYC,oJYC,gg)){ePYC.wxVkey=1
var cVYC=_n('tui-tag')
_rz(z,cVYC,'shape',84,cKYC,oJYC,gg)
var hWYC=_oz(z,85,cKYC,oJYC,gg)
_(cVYC,hWYC)
_(ePYC,cVYC)
}
var bQYC=_v()
_(aNYC,bQYC)
if(_oz(z,86,cKYC,oJYC,gg)){bQYC.wxVkey=1
var oXYC=_n('tui-tag')
_rz(z,oXYC,'shape',87,cKYC,oJYC,gg)
var cYYC=_oz(z,88,cKYC,oJYC,gg)
_(oXYC,cYYC)
_(bQYC,oXYC)
}
var oRYC=_v()
_(aNYC,oRYC)
if(_oz(z,89,cKYC,oJYC,gg)){oRYC.wxVkey=1
var oZYC=_n('tui-tag')
_rz(z,oZYC,'shape',90,cKYC,oJYC,gg)
var l1YC=_oz(z,91,cKYC,oJYC,gg)
_(oZYC,l1YC)
_(oRYC,oZYC)
}
var xSYC=_v()
_(aNYC,xSYC)
if(_oz(z,92,cKYC,oJYC,gg)){xSYC.wxVkey=1
var a2YC=_n('tui-tag')
_rz(z,a2YC,'shape',93,cKYC,oJYC,gg)
var t3YC=_oz(z,94,cKYC,oJYC,gg)
_(a2YC,t3YC)
_(xSYC,a2YC)
}
tOYC.wxXCkey=1
tOYC.wxXCkey=3
ePYC.wxXCkey=1
ePYC.wxXCkey=3
bQYC.wxXCkey=1
bQYC.wxXCkey=3
oRYC.wxXCkey=1
oRYC.wxXCkey=3
xSYC.wxXCkey=1
xSYC.wxXCkey=3
_(oLYC,aNYC)
return oLYC
}
cHYC.wxXCkey=4
_2z(z,77,hIYC,e,s,gg,cHYC,'item','index','index')
_(oFYC,fGYC)
_(eBYC,oFYC)
_(tAYC,eBYC)
_(a0XC,tAYC)
_(b7WC,a0XC)
var o8WC=_v()
_(b7WC,o8WC)
if(_oz(z,95,e,s,gg)){o8WC.wxVkey=1
var e4YC=_n('view')
_rz(z,e4YC,'class',96,e,s,gg)
var b5YC=_mz(z,'tui-list-cell',['arrow',97,'last',1],[],e,s,gg)
var o6YC=_n('view')
_rz(z,o6YC,'class',99,e,s,gg)
var x7YC=_mz(z,'image',['class',100,'mode',1,'src',2],[],e,s,gg)
_(o6YC,x7YC)
var o8YC=_n('text')
_rz(z,o8YC,'class',103,e,s,gg)
var f9YC=_oz(z,104,e,s,gg)
_(o8YC,f9YC)
_(o6YC,o8YC)
var c0YC=_n('view')
_rz(z,c0YC,'class',105,e,s,gg)
var hAZC=_v()
_(c0YC,hAZC)
if(_oz(z,106,e,s,gg)){hAZC.wxVkey=1
var oBZC=_n('text')
var cCZC=_oz(z,107,e,s,gg)
_(oBZC,cCZC)
_(hAZC,oBZC)
}
else{hAZC.wxVkey=2
var oDZC=_n('text')
var lEZC=_oz(z,108,e,s,gg)
_(oDZC,lEZC)
_(hAZC,oDZC)
}
hAZC.wxXCkey=1
_(o6YC,c0YC)
_(b5YC,o6YC)
_(e4YC,b5YC)
_(o8WC,e4YC)
}
var x9WC=_v()
_(b7WC,x9WC)
if(_oz(z,109,e,s,gg)){x9WC.wxVkey=1
var aFZC=_n('view')
_rz(z,aFZC,'class',110,e,s,gg)
var tGZC=_v()
_(aFZC,tGZC)
if(_oz(z,111,e,s,gg)){tGZC.wxVkey=1
var eHZC=_v()
_(tGZC,eHZC)
if(_oz(z,112,e,s,gg)){eHZC.wxVkey=1
var oJZC=_n('view')
var xKZC=_mz(z,'button',['class',113,'openType',1,'style',2],[],e,s,gg)
var oLZC=_oz(z,116,e,s,gg)
_(xKZC,oLZC)
_(oJZC,xKZC)
_(eHZC,oJZC)
}
var bIZC=_v()
_(tGZC,bIZC)
if(_oz(z,117,e,s,gg)){bIZC.wxVkey=1
var fMZC=_n('view')
_rz(z,fMZC,'class',118,e,s,gg)
var cNZC=_mz(z,'button',['bind:tap',119,'class',1,'style',2],[],e,s,gg)
var hOZC=_oz(z,122,e,s,gg)
_(cNZC,hOZC)
_(fMZC,cNZC)
_(bIZC,fMZC)
}
eHZC.wxXCkey=1
bIZC.wxXCkey=1
}
else{tGZC.wxVkey=2
var oPZC=_mz(z,'button',['bind:tap',123,'class',1,'style',2],[],e,s,gg)
var cQZC=_oz(z,126,e,s,gg)
_(oPZC,cQZC)
_(tGZC,oPZC)
}
tGZC.wxXCkey=1
_(x9WC,aFZC)
var oRZC=_n('view')
_rz(z,oRZC,'class',127,e,s,gg)
var lSZC=_mz(z,'button',['bindtap',128,'class',1,'style',2],[],e,s,gg)
var aTZC=_oz(z,131,e,s,gg)
_(lSZC,aTZC)
_(oRZC,lSZC)
_(x9WC,oRZC)
var tUZC=_n('view')
_rz(z,tUZC,'class',132,e,s,gg)
var eVZC=_n('view')
_rz(z,eVZC,'class',133,e,s,gg)
var bWZC=_oz(z,134,e,s,gg)
_(eVZC,bWZC)
_(tUZC,eVZC)
var oXZC=_n('view')
_rz(z,oXZC,'class',135,e,s,gg)
var xYZC=_oz(z,136,e,s,gg)
_(oXZC,xYZC)
_(tUZC,oXZC)
var oZZC=_n('view')
_rz(z,oZZC,'class',137,e,s,gg)
var f1ZC=_oz(z,138,e,s,gg)
_(oZZC,f1ZC)
_(tUZC,oZZC)
var c2ZC=_n('view')
_rz(z,c2ZC,'class',139,e,s,gg)
var h3ZC=_oz(z,140,e,s,gg)
_(c2ZC,h3ZC)
_(tUZC,c2ZC)
_(x9WC,tUZC)
}
else{x9WC.wxVkey=2
var o4ZC=_n('view')
_rz(z,o4ZC,'class',141,e,s,gg)
var c5ZC=_mz(z,'button',['bindtap',142,'class',1,'style',2],[],e,s,gg)
var o6ZC=_oz(z,145,e,s,gg)
_(c5ZC,o6ZC)
_(o4ZC,c5ZC)
_(x9WC,o4ZC)
}
o8WC.wxXCkey=1
o8WC.wxXCkey=3
x9WC.wxXCkey=1
_(r,b7WC)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx_XC_36";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx_XC_36();	if (__vd_version_info__.delayedGwx) __wxAppCode__['pages/set/set.wxml'] = [$gwx_XC_36, './pages/set/set.wxml'];else __wxAppCode__['pages/set/set.wxml'] = $gwx_XC_36( './pages/set/set.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['pages/set/set.wxss']=setCssToHead([".",[1],"tui-set-box{color:#333;padding-bottom:",[0,20],"}\n.",[1],"avatar-wrapper{border-radius:8px;margin-bottom:40px;margin-top:40px;padding:0;width:56px!important}\n.",[1],"avatar{display:block;height:56px;width:56px}\n.",[1],"container{display:-webkit-flex;display:flex}\n.",[1],"confirm{background-color:#5677fc;width:",[0,140],"}\n.",[1],"tui-list-cell{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;font-size:",[0,30],";padding:",[0,24]," ",[0,30],"}\n.",[1],"tui-info-box{font-size:",[0,34],"}\n.",[1],"tui-avatar{height:",[0,140],";margin-right:",[0,20],";width:",[0,140],"}\n.",[1],"tui-item-box{box-sizing:border-box;width:100%}\n.",[1],"tui-item-box,.",[1],"tui-list-cell_name{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-list-cell_name{-webkit-justify-content:center;justify-content:center;padding-left:",[0,20],"}\n.",[1],"tui-ml-auto,.",[1],"tui-right{margin-left:auto}\n.",[1],"tui-right{color:#333;font-size:",[0,26],";margin-right:",[0,34],"}\n.",[1],"tui-logo{-webkit-flex-shrink:0;flex-shrink:0;height:",[0,52],";width:",[0,52],"}\n.",[1],"tui-mtop{margin-top:",[0,20],"}\n.",[1],"tui-exit{padding:",[0,100]," ",[0,24],"}\n.",[1],"tui-line-cell{-webkit-align-items:center;align-items:center;box-sizing:border-box;display:-webkit-flex;display:flex;width:100%}\n.",[1],"tui-input{color:#333;-webkit-flex:1;flex:1;font-size:",[0,32],";overflow:visible;padding-left:",[0,20],"}\n.",[1],"radio-group{-webkit-flex-shrink:0;flex-shrink:0;margin-left:auto;-webkit-transform:scale(.8);transform:scale(.8);-webkit-transform-origin:100% center;transform-origin:100% center}\n.",[1],"tui-radio{display:inline-block;font-size:",[0,36],";padding-left:",[0,28],";vertical-align:middle}\n.",[1],"tui-title{color:#333;font-size:",[0,32],";padding:",[0,30]," 0 ",[0,20],"}\n.",[1],"tui-flex-box{-webkit-align-items:flex-start;align-items:flex-start;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;-webkit-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:flex-start;justify-content:flex-start;margin-bottom:",[0,26],";width:100%}\n.",[1],"tui-page__hd{box-sizing:border-box;padding:40px;width:100%}\n.",[1],"tui-page__bd{margin-top:20px;padding-bottom:40px}\n.",[1],"tui-page__title{font-size:20px;font-weight:400;text-align:left}\n.",[1],"tui-page__desc{color:#888;font-size:14px;margin-top:10px;text-align:left}\n.",[1],"tui-bottom-scroll{font-size:",[0,26],";max-height:60vh;min-height:50vh}\n",],undefined,{path:"./pages/set/set.wxss"});
}