$gwx_XC_20=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx_XC_20 || [];
function gz$gwx_XC_20_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx_XC_20_1)return __WXML_GLOBAL__.ops_cached.$gwx_XC_20_1
__WXML_GLOBAL__.ops_cached.$gwx_XC_20_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([a,[3,'tui-top-dropdown tui-dropdown-box '],[[2,'?:'],[[7],[3,'show']],[1,'tui-dropdown-show'],[1,'']]])
Z([a,[3,'height:'],[[2,'?:'],[[7],[3,'height']],[[12],[[7],[3,'px']],[[5],[[7],[3,'height']]]],[1,'auto']],[3,';background-color:'],[[7],[3,'backgroundColor']],[3,';padding-bottom:'],[[7],[3,'paddingbtm']],[3,'rpx;transform:translateZ(0) translateY('],[[2,'?:'],[[7],[3,'show']],[[2,'+'],[[7],[3,'translatey']],[1,'rpx']],[1,'-100%']],[3,')']])
Z([3,'handleClose'])
Z([a,[3,'tui-dropdown-mask '],[[2,'?:'],[[2,'&&'],[[7],[3,'mask']],[[7],[3,'show']]],[1,'tui-mask-show'],[1,'']]])
})(__WXML_GLOBAL__.ops_cached.$gwx_XC_20_1);return __WXML_GLOBAL__.ops_cached.$gwx_XC_20_1
}
function gz$gwx_XC_20_2(){
if( __WXML_GLOBAL__.ops_cached.$gwx_XC_20_2)return __WXML_GLOBAL__.ops_cached.$gwx_XC_20_2
__WXML_GLOBAL__.ops_cached.$gwx_XC_20_2=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([[2,'!='],[[6],[[7],[3,'cover_big']],[3,'length']],[1,0]])
Z([3,'clickCoverBig'])
Z([3,'bg-img1'])
Z([a,[3,'background-image:url('],[[7],[3,'cover_big']],[3,');height:100%;background-size:cover;']])
Z([3,'playAudioBig'])
Z([3,'cover-title'])
Z([3,'cover-titbox text-white'])
Z([a,[[7],[3,'title']]])
Z(z[1])
Z([3,'enter-tip'])
Z([3,'enter-tip-text'])
Z([3,'点击进入'])
Z([[2,'=='],[[7],[3,'displayMode']],[1,1]])
Z([3,'bannerChangeHandle'])
Z([[7],[3,'isComplete']])
Z([[7],[3,'bannerIndex']])
Z([3,'easeOutCubic'])
Z([1,true])
Z([3,'height:100vh'])
Z([[7],[3,'list']])
Z([3,'index'])
Z([3,'initParagraphs'])
Z(z[2])
Z([a,z[3][1],[[6],[[7],[3,'item']],[3,'img']],[3,');height:100%;']])
Z([[2,'&&'],[[2,'=='],[[7],[3,'autopage_hide']],[1,false]],[[2,'=='],[[7],[3,'showGame']],[1,false]]])
Z([3,'tui-product-title1'])
Z([[2,'=='],[[7],[3,'isTitle_zh']],[1,false]])
Z([3,'pIndex'])
Z([[7],[3,'paragraphs']])
Z(z[20])
Z([3,'padding-left'])
Z([3,'wIndex'])
Z([3,'word'])
Z([[7],[3,'item']])
Z(z[31])
Z([3,'clickWord'])
Z([a,[[2,'?:'],[[2,'==='],[[6],[[7],[3,'word']],[3,'type']],[1,'word']],[1,'title1-text'],[1,'']],[3,' '],[[2,'?:'],[[6],[[7],[3,'word']],[3,'highlight']],[1,'highlighted'],[1,'']]])
Z([[7],[3,'pIndex']])
Z([[7],[3,'wIndex']])
Z([a,[3,'font-size:'],[[6],[[6],[[7],[3,'list']],[[7],[3,'bannerIndex']]],[3,'font']],[3,'rpx;color:'],[[6],[[7],[3,'word']],[3,'color']],[3,';']])
Z([a,[[6],[[7],[3,'word']],[3,'text']]])
Z([3,'title1-text'])
Z([a,[[7],[3,'cur_title_zh']],[3,' ']])
Z([[2,'!='],[[7],[3,'record_content']],[1,'']])
Z([3,'playRecordAudio'])
Z([3,'audio-btn-1'])
Z([3,'audio-icon'])
Z([3,'▶'])
Z([[2,'=='],[[7],[3,'displayMode']],[1,2]])
Z([[2,'=='],[[7],[3,'isPad']],[1,false]])
Z(z[13])
Z(z[14])
Z(z[15])
Z(z[16])
Z(z[17])
Z([a,[3,'height:'],[[7],[3,'phone_image_height']],[3,'rpx;']])
Z(z[19])
Z(z[20])
Z([[7],[3,'index']])
Z(z[21])
Z(z[17])
Z([3,'widthFix'])
Z(z[23][2])
Z([3,'width:100%;height:100%;'])
Z(z[17])
Z(z[24])
Z([3,'tui-product-title2'])
Z(z[27])
Z(z[28])
Z(z[20])
Z([3,'padding-bottom'])
Z(z[31])
Z(z[32])
Z(z[33])
Z(z[31])
Z(z[35])
Z([a,[[2,'?:'],[[2,'==='],[[6],[[7],[3,'word']],[3,'type']],[1,'word']],[1,'title2-text'],[1,'']],z[36][2],z[36][3]])
Z(z[37])
Z(z[38])
Z([a,[3,'color:'],z[39][4],z[39][5]])
Z([a,z[40][1]])
Z([[2,'=='],[[7],[3,'isTitle_zh']],[1,true]])
Z([[7],[3,'paragraphs_zh']])
Z(z[20])
Z([3,'title2-text'])
Z([a,[[7],[3,'item']],z[42][2]])
Z(z[13])
Z(z[14])
Z(z[15])
Z(z[16])
Z(z[17])
Z([a,z[55][1],[[7],[3,'pad_image_height']],[3,'rpx;margin-top:20rpx;']])
Z(z[19])
Z(z[20])
Z([3,'pad-image'])
Z(z[58])
Z(z[21])
Z(z[17])
Z([3,'heightFix'])
Z(z[23][2])
Z([a,z[55][1],z[91][2],z[55][3]])
Z(z[17])
Z(z[24])
Z([3,'tui-product-title3'])
Z(z[27])
Z(z[28])
Z(z[20])
Z(z[31])
Z(z[32])
Z(z[33])
Z(z[31])
Z(z[35])
Z([a,z[76][1],z[36][2],z[36][3]])
Z(z[37])
Z(z[38])
Z([a,z[79][1],z[39][4],z[39][5]])
Z([a,z[40][1]])
Z(z[81])
Z(z[82])
Z(z[58])
Z(z[84])
Z([a,z[85][1],z[42][2]])
Z(z[43])
Z(z[44])
Z([3,'audio-btn-2'])
Z(z[46])
Z(z[47])
Z([3,'top-view'])
Z([3,'setting'])
Z([3,'showSettingModal'])
Z([3,'#ff9b6a'])
Z([3,'setup'])
Z([3,'80'])
Z([3,'rpx'])
Z([3,'deleteRecord'])
Z([3,'star-speak'])
Z([[7],[3,'userStarList']])
Z(z[20])
Z([a,[3,'icon-star-speak '],[[2,'?:'],[[2,'&&'],[[2,'=='],[[7],[3,'bannerIndex']],[[7],[3,'index']]],[[7],[3,'showConfetti']]],[1,'breathe-effect'],[1,'']],z[36][2],[[2,'?:'],[[2,'>'],[[6],[[7],[3,'userStarList']],[3,'length']],[1,10]],[1,'small'],[1,'']]])
Z([[2,'?:'],[[2,'>'],[[7],[3,'item']],[1,3]],[1,'https://qianyufang.top/public/yingyu/images/icon/star_icon.png'],[1,'https://qianyufang.top/public/yingyu/images/icon/star_icon_grey.png']])
Z([3,'share'])
Z(z[140])
Z([3,'true'])
Z([3,'share-image'])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/share.png'])
Z([3,'width:100%;'])
Z([3,'tui-banner-tag'])
Z([3,'12rpx 18rpx'])
Z([3,'circleRight'])
Z([3,'translucent'])
Z([a,[[2,'+'],[[7],[3,'bannerIndex']],[1,1]],[3,'/'],[[6],[[7],[3,'list']],[3,'length']]])
Z([3,'icon-list'])
Z([3,'setAutoPage'])
Z([3,'icon-right2'])
Z([[2,'?:'],[[7],[3,'isAutoPageStatus']],[1,'https://qianyufang.top/public/yingyu/images/icon/switch-open.png'],[1,'https://qianyufang.top/public/yingyu/images/icon/switch-close.png']])
Z([3,'goQuiz'])
Z([3,'icon-right1'])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/quiz.png'])
Z([3,'clickWordGame'])
Z([3,'icon-right3'])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/wrod_select.png'])
Z([3,'playAudioHandle'])
Z(z[156])
Z([[2,'?:'],[[2,'=='],[[7],[3,'audioPlayStatus']],[1,1]],[1,'https://qianyufang.top/public/yingyu/images/icon/pause.png'],[1,'https://qianyufang.top/public/yingyu/images/icon/play.png']])
Z([3,'showTitleZh'])
Z(z[156])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/zh.png'])
Z([3,'clickRecord'])
Z(z[156])
Z([[2,'?:'],[[7],[3,'isRecording']],[1,'https://qianyufang.top/public/yingyu/images/icon/speak_recording.png'],[1,'https://qianyufang.top/public/yingyu/images/icon/speak_record.png']])
Z([3,'hideModal'])
Z([3,'1001'])
Z([[7],[3,'popupShow']])
Z([3,'1002'])
Z([3,'tui-bottom-scroll padding'])
Z([3,'height:60vh;'])
Z([1,false])
Z([3,'10rpx 0rpx'])
Z([3,'thorui-flex__between'])
Z([3,'tui-title'])
Z([3,'1.手动翻页时是否静音'])
Z([3,'changeSetting1'])
Z([[7],[3,'setting_silent']])
Z([3,'blue'])
Z(z[176])
Z(z[177])
Z(z[178])
Z(z[179])
Z([3,'2.音频播放时是否高亮显示'])
Z([3,'changeSetting6'])
Z([[7],[3,'setting_highlight']])
Z(z[183])
Z(z[179])
Z([3,'3.录音模式'])
Z([3,'changeSetting2'])
Z([3,'radio'])
Z([[7],[3,'setting_speak']])
Z([3,'thorui-cells thorui-white__bg thorui-align__center'])
Z([3,'thorui-align__center'])
Z([3,'0'])
Z([3,'tui-text'])
Z([3,'录音测评'])
Z([3,'0 0 0 40rpx'])
Z(z[198])
Z([3,'1'])
Z(z[200])
Z([3,'只录音不测评'])
Z(z[179])
Z([3,'4.播放选择'])
Z([3,'changeSetting5'])
Z(z[195])
Z([[7],[3,'setting_recorder']])
Z(z[197])
Z(z[198])
Z(z[199])
Z(z[200])
Z([3,'原声音频'])
Z(z[202])
Z(z[198])
Z(z[204])
Z(z[200])
Z([3,'跟读录音'])
Z([[7],[3,'speed_mode_exist']])
Z(z[179])
Z([3,'5.速度模式'])
Z([3,'changeSetting7'])
Z(z[195])
Z([[7],[3,'setting_speed_mode']])
Z(z[197])
Z(z[198])
Z(z[204])
Z(z[200])
Z([3,'流利 [感情饱满]'])
Z(z[202])
Z(z[198])
Z(z[199])
Z(z[200])
Z([3,'慢读 [发音清晰]'])
Z(z[179])
Z([3,'5.播放速度'])
Z([3,'#5677fc'])
Z([3,'#c0c0c0'])
Z([3,'changeSetting4'])
Z(z[240])
Z([3,'1.2'])
Z([3,'0.6'])
Z([3,'0.1'])
Z([[7],[3,'setting_speed']])
Z([3,'#f7f7f7'])
Z([3,'已经到底部了'])
Z([3,'hideModalAutoplay'])
Z(z[17])
Z([[7],[3,'modalAutopage']])
Z([3,'tui-page__title padding-sm'])
Z([3,'自动翻页设置'])
Z([3,'padding-xs'])
Z([3,'section section_gap'])
Z([3,'section__title'])
Z([3,'1.自动翻页时间间隔'])
Z([3,'body-view'])
Z(z[240])
Z(z[241])
Z([3,'setAutoPageTime'])
Z(z[240])
Z([3,'3'])
Z(z[199])
Z(z[204])
Z([[7],[3,'autopage_time']])
Z(z[256])
Z(z[257])
Z([3,'2.单个页面重复次数'])
Z(z[259])
Z(z[240])
Z(z[241])
Z([3,'setAutoPageNum'])
Z(z[240])
Z(z[264])
Z(z[204])
Z(z[204])
Z([[7],[3,'autopage_num']])
Z([3,'margin-top'])
Z(z[176])
Z([3,'24rpx 0rpx'])
Z(z[178])
Z([3,'3.是否隐藏底部文字'])
Z([3,'changeAutopage2'])
Z([[7],[3,'autopage_hide']])
Z(z[183])
Z([3,'margin-top-xs'])
Z(z[176])
Z(z[282])
Z(z[178])
Z([3,'4.是否播放中文音频'])
Z([3,'changeAutopage1'])
Z([[7],[3,'autopage_zh']])
Z(z[183])
Z([[2,'>'],[[7],[3,'vip']],[1,0]])
Z(z[288])
Z(z[176])
Z(z[282])
Z(z[178])
Z([3,'5.是否自动播放下一本'])
Z([3,'changeAutopage3'])
Z([[7],[3,'autopage_next']])
Z(z[183])
Z([3,'tui-modal-custom margin-top'])
Z([3,'startAutoPlay'])
Z([3,'bg-blue'])
Z([3,'72rpx'])
Z([3,'circle'])
Z([3,'28'])
Z([3,'开始自动播放'])
Z([3,'hideModal5'])
Z([3,'560'])
Z([3,'false'])
Z([[7],[3,'modalWordTop']])
Z([3,'z-index:999;'])
Z([3,'tui-order-list'])
Z([[7],[3,'wordClicks']])
Z(z[20])
Z([3,'tui-goods-item'])
Z([3,'downloadWordPoster'])
Z([3,'tui-goods-img'])
Z(z[58])
Z([3,'aspectFill'])
Z(z[23][2])
Z([3,'tui-new-label-finish'])
Z([3,'download-icon'])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/download_square.png'])
Z([3,'tui-goods-center'])
Z([3,'clickWordSpell'])
Z([3,'tui-word-name'])
Z(z[58])
Z([3,'word-container'])
Z([3,'cindex'])
Z([3,'citem'])
Z([[6],[[7],[3,'item']],[3,'name']])
Z(z[20])
Z([a,[3,'letter-box '],[[2,'?:'],[[2,'&&'],[[2,'==='],[[7],[3,'highlightIndex']],[[7],[3,'cindex']]],[[2,'=='],[[7],[3,'clickWordId']],[[7],[3,'index']]]],[1,'highlight'],[1,'']]])
Z([a,[[7],[3,'citem']]])
Z([3,'tui-logo-small margin-left-sm'])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/voice_on.png'])
Z([[6],[[7],[3,'item']],[3,'yinbiao']])
Z([3,'tui-goods-name'])
Z([3,'tui-gray text-xxl'])
Z([a,[3,' ['],[[6],[[7],[3,'item']],[3,'yinbiao']],[3,']']])
Z(z[343])
Z([3,'text-xxl'])
Z([a,[[6],[[7],[3,'item']],[3,'zh']]])
Z([[6],[[7],[3,'item']],[3,'include']])
Z(z[343])
Z(z[334])
Z(z[335])
Z(z[349])
Z(z[20])
Z([3,'clickWordInclude'])
Z([3,'text-xxl text-bold tui-gray'])
Z([[7],[3,'citem']])
Z([a,z[339][1]])
Z([3,'flex'])
Z([3,'clickWordAudioTop'])
Z([3,'tui-logo'])
Z(z[58])
Z([[2,'?:'],[[7],[3,'wordPlaying']],[1,'https://qianyufang.top/public/yingyu/images/icon/pause.png'],[1,'https://qianyufang.top/public/yingyu/images/icon/play.png']])
Z([3,'collectWord'])
Z([3,'tui-logo margin-left-sm'])
Z(z[58])
Z([[2,'?:'],[[6],[[7],[3,'item']],[3,'collect']],[1,'https://qianyufang.top/public/yingyu/images/icon/collect.png'],[1,'https://qianyufang.top/public/yingyu/images/icon/collect_no.png']])
Z([3,'wordExtendTop'])
Z(z[365])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/more.png'])
Z([[6],[[7],[3,'item']],[3,'prompt']])
Z([3,'clickWordPrompt'])
Z([3,'tui-study-prompt'])
Z(z[58])
Z([a,[[12],[[6],[[7],[3,'utils']],[3,'extractSentence']],[[5],[[6],[[7],[3,'item']],[3,'prompt']]]]])
Z([3,'tui-logo-small'])
Z(z[341])
Z([[7],[3,'posterUrl']])
Z([3,'poster-container-word'])
Z([3,'closePosterWord'])
Z([3,'close-btn'])
Z([3,'×'])
Z([3,'poster-img'])
Z(z[61])
Z(z[378])
Z([3,'savePoster'])
Z([3,'save-btn'])
Z([3,'保存到相册'])
Z([3,'hidden-canvas'])
Z([3,'posterCanvas'])
Z([3,'2d'])
Z([[7],[3,'isRecording']])
Z(z[167])
Z([3,'popup-recording-start'])
Z([a,[3,'icon-recording  '],[[7],[3,'animation']]])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/recording.png'])
Z([[2,'||'],[[7],[3,'recordResultShow']],[[7],[3,'isWCPMshow']]])
Z([3,'closeResultShow'])
Z([3,'popup-recording-end'])
Z([[7],[3,'recordResultShow']])
Z([3,'popup-text'])
Z([3,'padding'])
Z([[7],[3,'star']])
Z(z[20])
Z([3,'icon-star padding-xss'])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/star.png'])
Z([[2,'-'],[1,5],[[7],[3,'star']]])
Z(z[20])
Z(z[405])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/star_gray.png'])
Z([3,'value-container'])
Z([[2,'&&'],[[2,'=='],[[7],[3,'value']],[1,100]],[[7],[3,'isConfetti']]])
Z([3,'confetti-gif'])
Z([3,'aspectFit'])
Z([3,'https://qianyufang.top/public/yingyu/images/gif/confetti.gif'])
Z([3,'text-macron value-text'])
Z([a,[[7],[3,'value']]])
Z([3,'result-text'])
Z([3,'text-white text-xl'])
Z([a,[[7],[3,'record_result']]])
Z([[2,'!='],[[7],[3,'value']],[1,100]])
Z([3,'action-bar'])
Z([3,'playReocrdAudio'])
Z([3,'action-item'])
Z(z[204])
Z([3,'icon-circle'])
Z([3,'iconfont icon-play'])
Z([3,'action-label'])
Z([3,'播放原声'])
Z([3,'clickStart'])
Z(z[424])
Z([3,'icon-circle highlight'])
Z(z[427])
Z(z[428])
Z([3,'再次跟读'])
Z(z[423])
Z(z[424])
Z([3,'2'])
Z([3,'icon-circle '])
Z([3,'iconfont icon-mic'])
Z(z[428])
Z([3,'录音回放'])
Z([3,'reward-card'])
Z([3,'light-ray'])
Z([3,'badge-wrapper bounce'])
Z([3,'badge-emoji'])
Z([3,'🏆'])
Z([3,'card-title'])
Z([3,'本课阅读战报'])
Z([3,'divider'])
Z([3,'metrics-area'])
Z([3,'showWCompleteTip'])
Z([3,'metric-row'])
Z([3,'metric-label'])
Z([3,'完成度'])
Z([3,'stars-box'])
Z([1,3])
Z([3,'*this'])
Z([a,[3,'star-icon '],[[2,'?:'],[[2,'<='],[[2,'+'],[[7],[3,'index']],[1,1]],[[7],[3,'completionStars']]],[1,'active-star'],[1,'empty-star']]])
Z([a,[3,'animation-delay:'],[[2,'*'],[[2,'+'],[[7],[3,'index']],[1,1]],[1,0.15]],[3,'s']])
Z([3,'★'])
Z([3,'raw-data-text'])
Z([a,[[7],[3,'completedPages']],z[150][2],[[7],[3,'totalPages']],[3,' 页']])
Z([3,'showAccuracyTip'])
Z(z[453])
Z(z[454])
Z([3,'准确度'])
Z(z[456])
Z(z[457])
Z(z[458])
Z([a,z[459][1],[[2,'?:'],[[2,'<='],[[2,'+'],[[7],[3,'index']],[1,1]],[[7],[3,'accuracyStars']]],[1,'active-star'],[1,'empty-star']]])
Z([a,z[460][1],[[2,'*'],[[2,'+'],[[7],[3,'index']],[1,3]],[1,0.15]],z[460][3]])
Z(z[461])
Z(z[462])
Z([a,[3,'平均 '],[[7],[3,'averageScore']],[3,' 分']])
Z([3,'showWCPMtip'])
Z(z[453])
Z(z[454])
Z([3,'流利度'])
Z(z[456])
Z(z[457])
Z(z[458])
Z([a,z[459][1],[[2,'?:'],[[2,'<='],[[2,'+'],[[7],[3,'index']],[1,1]],[[7],[3,'fluencyStars']]],[1,'active-star'],[1,'empty-star']]])
Z([a,z[460][1],[[2,'*'],[[2,'+'],[[7],[3,'index']],[1,6]],[1,0.15]],z[460][3]])
Z(z[461])
Z(z[462])
Z([a,[[7],[3,'wcpmValue']],[3,' WCPM']])
Z(z[450])
Z([3,'comment-area fade-in-up'])
Z([3,'comment-text'])
Z([a,[[7],[3,'motivationalText']]])
Z([3,'action-buttons fade-in-up-delay'])
Z(z[398])
Z([3,'btn-action btn-close'])
Z([3,'btn-icon'])
Z([3,'✖'])
Z([3,'关闭'])
Z([3,'showAndGeneratePoster'])
Z([3,'btn-action btn-share'])
Z(z[495])
Z([3,'✨'])
Z([3,'分享'])
Z([[7],[3,'showGame']])
Z([3,'game-mask'])
Z([a,[3,'immersive-game-box '],[[2,'?:'],[[7],[3,'isShaking']],[1,'shake-err'],[1,'']]])
Z([[2,'&&'],[[2,'=='],[[7],[3,'isGamePassed']],[1,true]],[[7],[3,'isConfetti']]])
Z(z[413])
Z(z[414])
Z(z[415])
Z([3,'scroll-content'])
Z([3,'flex-center-wrapper'])
Z([3,'answer-area'])
Z([[7],[3,'originalWordsData']])
Z(z[20])
Z([3,'word-slot-wrapper'])
Z([3,'handleWordClick'])
Z([a,[3,'word-slot '],[[2,'?:'],[[6],[[7],[3,'userAnswer']],[[7],[3,'index']]],[1,'filled'],[1,'empty']],z[36][2],[[2,'?:'],[[6],[[7],[3,'itemIsWrong']],[[7],[3,'index']]],[1,'is-error'],[1,'']]])
Z(z[58])
Z([a,z[36][2],[[6],[[7],[3,'userAnswer']],[[7],[3,'index']]]])
Z([3,'word-text'])
Z([a,z[42][2],[[6],[[6],[[7],[3,'userAnswer']],[[7],[3,'index']]],[3,'word']]])
Z([3,'underline-glow'])
Z([[2,'&&'],[[7],[3,'isGamePassed']],[[2,'==='],[[7],[3,'activePhoneticIndex']],[[7],[3,'index']]]])
Z([3,'phonetic-abs-box'])
Z([3,'phonetic-text'])
Z([a,[[6],[[7],[3,'item']],[3,'phonetic']]])
Z([[6],[[7],[3,'item']],[3,'punctuation']])
Z([3,'punctuation-text'])
Z([a,[3,'\n              '],[[6],[[7],[3,'item']],[3,'punctuation']],[3,'\n            ']])
Z([[2,'=='],[[7],[3,'isGamePassed']],[1,false]])
Z([3,'options-pool'])
Z([[7],[3,'shuffledWords']])
Z(z[20])
Z([3,'moveToAnswer'])
Z([a,[3,'word-card-glass '],[[2,'?:'],[[6],[[7],[3,'item']],[3,'selected']],[1,'is-hidden'],[1,'']]])
Z(z[58])
Z([a,[[6],[[7],[3,'item']],[3,'word']]])
Z([3,'glass-action-btns'])
Z([3,'closeGame'])
Z([3,'glass-btn btn-minor'])
Z(z[497])
Z(z[161])
Z([3,'glass-btn btn-main'])
Z([[2,'=='],[[7],[3,'audioPlayStatus']],[1,0]])
Z([3,'听音'])
Z([[2,'=='],[[7],[3,'audioPlayStatus']],[1,1]])
Z([3,'暂停'])
Z([[2,'=='],[[7],[3,'audioPlayStatus']],[1,2]])
Z([3,'继续'])
Z([3,'checkGameResult'])
Z([3,'glass-btn btn-confirm'])
Z([3,'检查'])
Z([[7],[3,'showPoster']])
Z([3,'poster-mask'])
Z([3,'poster-container'])
Z([3,'hide-canvas'])
Z([3,'myPoster'])
Z([3,'width:750px;height:1334px;'])
Z(z[391])
Z([3,'preview-img'])
Z(z[61])
Z([[7],[3,'posterImage']])
Z([3,'poster-btns'])
Z([3,'closePoster'])
Z([3,'btn-action btn-cancel'])
Z([3,'取消'])
Z([3,'saveToPhotosAlbum'])
Z([3,'btn-action btn-save'])
Z(z[388])
})(__WXML_GLOBAL__.ops_cached.$gwx_XC_20_2);return __WXML_GLOBAL__.ops_cached.$gwx_XC_20_2
}
__WXML_GLOBAL__.ops_set.$gwx_XC_20=z;
__WXML_GLOBAL__.ops_init.$gwx_XC_20=true;
var x=['./components/tui-top-dropdown/tui-top-dropdown.wxml','./pages/card/card.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx_XC_20_1()
var e48=_n('view')
var b58=_mz(z,'view',['class',0,'style',1],[],e,s,gg)
var o68=_n('slot')
_(b58,o68)
_(e48,b58)
var x78=_mz(z,'view',['bindtap',2,'class',1],[],e,s,gg)
_(e48,x78)
_(r,e48)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
d_[x[1]]={}
var m1=function(e,s,r,gg){
var z=gz$gwx_XC_20_2()
var f98=_v()
_(r,f98)
if(_oz(z,0,e,s,gg)){f98.wxVkey=1
var lE9=_mz(z,'view',['catch:tap',1,'class',1,'style',2],[],e,s,gg)
_(f98,lE9)
var aF9=_mz(z,'view',['bind:tap',4,'class',1],[],e,s,gg)
var tG9=_n('view')
_rz(z,tG9,'class',6,e,s,gg)
var eH9=_oz(z,7,e,s,gg)
_(tG9,eH9)
_(aF9,tG9)
_(f98,aF9)
var bI9=_mz(z,'view',['catch:tap',8,'class',1],[],e,s,gg)
var oJ9=_n('text')
_rz(z,oJ9,'class',10,e,s,gg)
var xK9=_oz(z,11,e,s,gg)
_(oJ9,xK9)
_(bI9,oJ9)
_(f98,bI9)
}
else{f98.wxVkey=2
var oL9=_v()
_(f98,oL9)
if(_oz(z,12,e,s,gg)){oL9.wxVkey=1
var oP9=_mz(z,'swiper',['bindchange',13,'circular',1,'current',2,'easingFunction',3,'skipHiddenItemLayout',4,'style',5],[],e,s,gg)
var cQ9=_v()
_(oP9,cQ9)
var oR9=function(aT9,lS9,tU9,gg){
var bW9=_n('swiper-item')
var oX9=_mz(z,'view',['bind:tap',21,'class',1,'style',2],[],aT9,lS9,gg)
_(bW9,oX9)
_(tU9,bW9)
return tU9
}
cQ9.wxXCkey=2
_2z(z,19,oR9,e,s,gg,cQ9,'item','index','index')
_(oL9,oP9)
var cN9=_v()
_(oL9,cN9)
if(_oz(z,24,e,s,gg)){cN9.wxVkey=1
var xY9=_n('view')
_rz(z,xY9,'class',25,e,s,gg)
var oZ9=_v()
_(xY9,oZ9)
if(_oz(z,26,e,s,gg)){oZ9.wxVkey=1
var f19=_v()
_(oZ9,f19)
var c29=function(o49,h39,c59,gg){
var l79=_n('view')
_rz(z,l79,'class',30,o49,h39,gg)
var a89=_v()
_(l79,a89)
var t99=function(bA0,e09,oB0,gg){
var oD0=_mz(z,'text',['catch:tap',35,'class',1,'data-p-index',2,'data-w-index',3,'style',4],[],bA0,e09,gg)
var fE0=_oz(z,40,bA0,e09,gg)
_(oD0,fE0)
_(oB0,oD0)
return oB0
}
a89.wxXCkey=2
_2z(z,33,t99,o49,h39,gg,a89,'word','wIndex','wIndex')
_(c59,l79)
return c59
}
f19.wxXCkey=2
_2z(z,28,c29,e,s,gg,f19,'item','pIndex','index')
}
else{oZ9.wxVkey=2
var cF0=_n('text')
_rz(z,cF0,'class',41,e,s,gg)
var hG0=_oz(z,42,e,s,gg)
_(cF0,hG0)
_(oZ9,cF0)
}
oZ9.wxXCkey=1
_(cN9,xY9)
}
var hO9=_v()
_(oL9,hO9)
if(_oz(z,43,e,s,gg)){hO9.wxVkey=1
var oH0=_mz(z,'view',['catch:tap',44,'class',1],[],e,s,gg)
var cI0=_n('text')
_rz(z,cI0,'class',46,e,s,gg)
var oJ0=_oz(z,47,e,s,gg)
_(cI0,oJ0)
_(oH0,cI0)
_(hO9,oH0)
}
cN9.wxXCkey=1
hO9.wxXCkey=1
}
var fM9=_v()
_(f98,fM9)
if(_oz(z,48,e,s,gg)){fM9.wxVkey=1
var lK0=_v()
_(fM9,lK0)
if(_oz(z,49,e,s,gg)){lK0.wxVkey=1
var eN0=_mz(z,'swiper',['bindchange',50,'circular',1,'current',2,'easingFunction',3,'skipHiddenItemLayout',4,'style',5],[],e,s,gg)
var bO0=_v()
_(eN0,bO0)
var oP0=function(oR0,xQ0,fS0,gg){
var hU0=_n('swiper-item')
_rz(z,hU0,'data-index',58,oR0,xQ0,gg)
var oV0=_mz(z,'image',['bind:tap',59,'lazyLoad',1,'mode',2,'src',3,'style',4,'webp',5],[],oR0,xQ0,gg)
_(hU0,oV0)
_(fS0,hU0)
return fS0
}
bO0.wxXCkey=2
_2z(z,56,oP0,e,s,gg,bO0,'item','index','index')
_(lK0,eN0)
var tM0=_v()
_(lK0,tM0)
if(_oz(z,65,e,s,gg)){tM0.wxVkey=1
var cW0=_n('view')
_rz(z,cW0,'class',66,e,s,gg)
var lY0=_v()
_(cW0,lY0)
var aZ0=function(e20,t10,b30,gg){
var x50=_n('view')
_rz(z,x50,'class',70,e20,t10,gg)
var o60=_v()
_(x50,o60)
var f70=function(h90,c80,o00,gg){
var oBAB=_mz(z,'text',['catch:tap',75,'class',1,'data-p-index',2,'data-w-index',3,'style',4],[],h90,c80,gg)
var lCAB=_oz(z,80,h90,c80,gg)
_(oBAB,lCAB)
_(o00,oBAB)
return o00
}
o60.wxXCkey=2
_2z(z,73,f70,e20,t10,gg,o60,'word','wIndex','wIndex')
_(b30,x50)
return b30
}
lY0.wxXCkey=2
_2z(z,68,aZ0,e,s,gg,lY0,'item','pIndex','index')
var oX0=_v()
_(cW0,oX0)
if(_oz(z,81,e,s,gg)){oX0.wxVkey=1
var aDAB=_v()
_(oX0,aDAB)
var tEAB=function(bGAB,eFAB,oHAB,gg){
var oJAB=_n('view')
var fKAB=_n('text')
_rz(z,fKAB,'class',84,bGAB,eFAB,gg)
var cLAB=_oz(z,85,bGAB,eFAB,gg)
_(fKAB,cLAB)
_(oJAB,fKAB)
_(oHAB,oJAB)
return oHAB
}
aDAB.wxXCkey=2
_2z(z,82,tEAB,e,s,gg,aDAB,'item','index','index')
}
oX0.wxXCkey=1
_(tM0,cW0)
}
tM0.wxXCkey=1
}
else{lK0.wxVkey=2
var oNAB=_mz(z,'swiper',['bindchange',86,'circular',1,'current',2,'easingFunction',3,'skipHiddenItemLayout',4,'style',5],[],e,s,gg)
var cOAB=_v()
_(oNAB,cOAB)
var oPAB=function(aRAB,lQAB,tSAB,gg){
var bUAB=_mz(z,'swiper-item',['class',94,'data-index',1],[],aRAB,lQAB,gg)
var oVAB=_mz(z,'image',['bind:tap',96,'lazyLoad',1,'mode',2,'src',3,'style',4,'webp',5],[],aRAB,lQAB,gg)
_(bUAB,oVAB)
_(tSAB,bUAB)
return tSAB
}
cOAB.wxXCkey=2
_2z(z,92,oPAB,e,s,gg,cOAB,'item','index','index')
_(lK0,oNAB)
var hMAB=_v()
_(lK0,hMAB)
if(_oz(z,102,e,s,gg)){hMAB.wxVkey=1
var xWAB=_n('view')
_rz(z,xWAB,'class',103,e,s,gg)
var fYAB=_v()
_(xWAB,fYAB)
var cZAB=function(o2AB,h1AB,c3AB,gg){
var l5AB=_n('view')
var a6AB=_v()
_(l5AB,a6AB)
var t7AB=function(b9AB,e8AB,o0AB,gg){
var oBBB=_mz(z,'text',['catch:tap',111,'class',1,'data-p-index',2,'data-w-index',3,'style',4],[],b9AB,e8AB,gg)
var fCBB=_oz(z,116,b9AB,e8AB,gg)
_(oBBB,fCBB)
_(o0AB,oBBB)
return o0AB
}
a6AB.wxXCkey=2
_2z(z,109,t7AB,o2AB,h1AB,gg,a6AB,'word','wIndex','wIndex')
_(c3AB,l5AB)
return c3AB
}
fYAB.wxXCkey=2
_2z(z,105,cZAB,e,s,gg,fYAB,'item','pIndex','index')
var oXAB=_v()
_(xWAB,oXAB)
if(_oz(z,117,e,s,gg)){oXAB.wxVkey=1
var cDBB=_v()
_(oXAB,cDBB)
var hEBB=function(cGBB,oFBB,oHBB,gg){
var aJBB=_n('view')
var tKBB=_n('text')
_rz(z,tKBB,'class',120,cGBB,oFBB,gg)
var eLBB=_oz(z,121,cGBB,oFBB,gg)
_(tKBB,eLBB)
_(aJBB,tKBB)
_(oHBB,aJBB)
return oHBB
}
cDBB.wxXCkey=2
_2z(z,118,hEBB,e,s,gg,cDBB,'item','index','{{index}}')
}
oXAB.wxXCkey=1
_(hMAB,xWAB)
}
hMAB.wxXCkey=1
}
var aL0=_v()
_(fM9,aL0)
if(_oz(z,122,e,s,gg)){aL0.wxVkey=1
var bMBB=_mz(z,'view',['catch:tap',123,'class',1],[],e,s,gg)
var oNBB=_n('text')
_rz(z,oNBB,'class',125,e,s,gg)
var xOBB=_oz(z,126,e,s,gg)
_(oNBB,xOBB)
_(bMBB,oNBB)
_(aL0,bMBB)
}
lK0.wxXCkey=1
aL0.wxXCkey=1
}
var oPBB=_n('view')
_rz(z,oPBB,'class',127,e,s,gg)
var fQBB=_n('view')
_rz(z,fQBB,'class',128,e,s,gg)
var cRBB=_mz(z,'tui-icon',['bindclick',129,'color',1,'name',2,'size',3,'unit',4],[],e,s,gg)
_(fQBB,cRBB)
_(oPBB,fQBB)
var hSBB=_mz(z,'view',['bindtap',134,'class',1],[],e,s,gg)
var oTBB=_v()
_(hSBB,oTBB)
var cUBB=function(lWBB,oVBB,aXBB,gg){
var eZBB=_mz(z,'image',['class',138,'src',1],[],lWBB,oVBB,gg)
_(aXBB,eZBB)
return aXBB
}
oTBB.wxXCkey=2
_2z(z,136,cUBB,e,s,gg,oTBB,'item','index','index')
_(oPBB,hSBB)
var b1BB=_n('view')
_rz(z,b1BB,'class',140,e,s,gg)
var o2BB=_mz(z,'button',['openType',141,'plain',1],[],e,s,gg)
var x3BB=_mz(z,'image',['class',143,'src',1,'style',2],[],e,s,gg)
_(o2BB,x3BB)
_(b1BB,o2BB)
_(oPBB,b1BB)
_(f98,oPBB)
var o4BB=_n('view')
_rz(z,o4BB,'class',146,e,s,gg)
var f5BB=_mz(z,'tui-tag',['originRight',-1,'padding',147,'shape',1,'type',2],[],e,s,gg)
var c6BB=_oz(z,150,e,s,gg)
_(f5BB,c6BB)
_(o4BB,f5BB)
_(f98,o4BB)
var h7BB=_n('view')
_rz(z,h7BB,'class',151,e,s,gg)
var o8BB=_mz(z,'image',['bindtap',152,'class',1,'src',2],[],e,s,gg)
_(h7BB,o8BB)
var c9BB=_mz(z,'image',['bindtap',155,'class',1,'src',2],[],e,s,gg)
_(h7BB,c9BB)
var o0BB=_mz(z,'image',['bindtap',158,'class',1,'src',2],[],e,s,gg)
_(h7BB,o0BB)
var lACB=_mz(z,'image',['bindtap',161,'class',1,'src',2],[],e,s,gg)
_(h7BB,lACB)
var aBCB=_mz(z,'image',['bindtap',164,'class',1,'src',2],[],e,s,gg)
_(h7BB,aBCB)
var tCCB=_mz(z,'image',['bindtap',167,'class',1,'src',2],[],e,s,gg)
_(h7BB,tCCB)
_(f98,h7BB)
oL9.wxXCkey=1
fM9.wxXCkey=1
}
var eDCB=_mz(z,'tui-bottom-popup',['bindclose',170,'maskZIndex',1,'show',2,'zIndex',3],[],e,s,gg)
var bECB=_mz(z,'scroll-view',['scrollY',-1,'class',174,'style',1],[],e,s,gg)
var xGCB=_mz(z,'tui-list-cell',['hover',176,'padding',1],[],e,s,gg)
var oHCB=_n('view')
_rz(z,oHCB,'class',178,e,s,gg)
var fICB=_n('text')
_rz(z,fICB,'class',179,e,s,gg)
var cJCB=_oz(z,180,e,s,gg)
_(fICB,cJCB)
_(oHCB,fICB)
var hKCB=_mz(z,'switch',['bindchange',181,'checked',1,'class',2],[],e,s,gg)
_(oHCB,hKCB)
_(xGCB,oHCB)
_(bECB,xGCB)
var oLCB=_mz(z,'tui-list-cell',['hover',184,'padding',1],[],e,s,gg)
var cMCB=_n('view')
_rz(z,cMCB,'class',186,e,s,gg)
var oNCB=_n('text')
_rz(z,oNCB,'class',187,e,s,gg)
var lOCB=_oz(z,188,e,s,gg)
_(oNCB,lOCB)
_(cMCB,oNCB)
var aPCB=_mz(z,'switch',['bindchange',189,'checked',1,'class',2],[],e,s,gg)
_(cMCB,aPCB)
_(oLCB,cMCB)
_(bECB,oLCB)
var tQCB=_n('view')
_rz(z,tQCB,'class',192,e,s,gg)
var eRCB=_oz(z,193,e,s,gg)
_(tQCB,eRCB)
_(bECB,tQCB)
var bSCB=_mz(z,'tui-radio-group',['bindchange',194,'name',1,'value',2],[],e,s,gg)
var oTCB=_n('view')
_rz(z,oTCB,'class',197,e,s,gg)
var xUCB=_n('tui-label')
var oVCB=_n('view')
_rz(z,oVCB,'class',198,e,s,gg)
var fWCB=_n('tui-radio')
_rz(z,fWCB,'value',199,e,s,gg)
_(oVCB,fWCB)
var cXCB=_n('text')
_rz(z,cXCB,'class',200,e,s,gg)
var hYCB=_oz(z,201,e,s,gg)
_(cXCB,hYCB)
_(oVCB,cXCB)
_(xUCB,oVCB)
_(oTCB,xUCB)
var oZCB=_n('tui-label')
_rz(z,oZCB,'margin',202,e,s,gg)
var c1CB=_n('view')
_rz(z,c1CB,'class',203,e,s,gg)
var o2CB=_n('tui-radio')
_rz(z,o2CB,'value',204,e,s,gg)
_(c1CB,o2CB)
var l3CB=_n('text')
_rz(z,l3CB,'class',205,e,s,gg)
var a4CB=_oz(z,206,e,s,gg)
_(l3CB,a4CB)
_(c1CB,l3CB)
_(oZCB,c1CB)
_(oTCB,oZCB)
_(bSCB,oTCB)
_(bECB,bSCB)
var t5CB=_n('view')
_rz(z,t5CB,'class',207,e,s,gg)
var e6CB=_oz(z,208,e,s,gg)
_(t5CB,e6CB)
_(bECB,t5CB)
var b7CB=_mz(z,'tui-radio-group',['bindchange',209,'name',1,'value',2],[],e,s,gg)
var o8CB=_n('view')
_rz(z,o8CB,'class',212,e,s,gg)
var x9CB=_n('tui-label')
var o0CB=_n('view')
_rz(z,o0CB,'class',213,e,s,gg)
var fADB=_n('tui-radio')
_rz(z,fADB,'value',214,e,s,gg)
_(o0CB,fADB)
var cBDB=_n('text')
_rz(z,cBDB,'class',215,e,s,gg)
var hCDB=_oz(z,216,e,s,gg)
_(cBDB,hCDB)
_(o0CB,cBDB)
_(x9CB,o0CB)
_(o8CB,x9CB)
var oDDB=_n('tui-label')
_rz(z,oDDB,'margin',217,e,s,gg)
var cEDB=_n('view')
_rz(z,cEDB,'class',218,e,s,gg)
var oFDB=_n('tui-radio')
_rz(z,oFDB,'value',219,e,s,gg)
_(cEDB,oFDB)
var lGDB=_n('text')
_rz(z,lGDB,'class',220,e,s,gg)
var aHDB=_oz(z,221,e,s,gg)
_(lGDB,aHDB)
_(cEDB,lGDB)
_(oDDB,cEDB)
_(o8CB,oDDB)
_(b7CB,o8CB)
_(bECB,b7CB)
var oFCB=_v()
_(bECB,oFCB)
if(_oz(z,222,e,s,gg)){oFCB.wxVkey=1
var tIDB=_n('view')
_rz(z,tIDB,'class',223,e,s,gg)
var eJDB=_oz(z,224,e,s,gg)
_(tIDB,eJDB)
_(oFCB,tIDB)
var bKDB=_mz(z,'tui-radio-group',['bindchange',225,'name',1,'value',2],[],e,s,gg)
var oLDB=_n('view')
_rz(z,oLDB,'class',228,e,s,gg)
var xMDB=_n('tui-label')
var oNDB=_n('view')
_rz(z,oNDB,'class',229,e,s,gg)
var fODB=_n('tui-radio')
_rz(z,fODB,'value',230,e,s,gg)
_(oNDB,fODB)
var cPDB=_n('text')
_rz(z,cPDB,'class',231,e,s,gg)
var hQDB=_oz(z,232,e,s,gg)
_(cPDB,hQDB)
_(oNDB,cPDB)
_(xMDB,oNDB)
_(oLDB,xMDB)
var oRDB=_n('tui-label')
_rz(z,oRDB,'margin',233,e,s,gg)
var cSDB=_n('view')
_rz(z,cSDB,'class',234,e,s,gg)
var oTDB=_n('tui-radio')
_rz(z,oTDB,'value',235,e,s,gg)
_(cSDB,oTDB)
var lUDB=_n('text')
_rz(z,lUDB,'class',236,e,s,gg)
var aVDB=_oz(z,237,e,s,gg)
_(lUDB,aVDB)
_(cSDB,lUDB)
_(oRDB,cSDB)
_(oLDB,oRDB)
_(bKDB,oLDB)
_(oFCB,bKDB)
}
else{oFCB.wxVkey=2
var tWDB=_n('view')
_rz(z,tWDB,'class',238,e,s,gg)
var eXDB=_oz(z,239,e,s,gg)
_(tWDB,eXDB)
_(oFCB,tWDB)
var bYDB=_mz(z,'slider',['showValue',-1,'activeColor',240,'backgroundColor',1,'bindchange',2,'blockColor',3,'max',4,'min',5,'step',6,'value',7],[],e,s,gg)
_(oFCB,bYDB)
}
var oZDB=_mz(z,'tui-nomore',['backgroundColor',248,'text',1],[],e,s,gg)
_(bECB,oZDB)
oFCB.wxXCkey=1
oFCB.wxXCkey=3
_(eDCB,bECB)
_(r,eDCB)
var x1DB=_mz(z,'tui-modal',['bindcancel',250,'custom',1,'show',2],[],e,s,gg)
var o2DB=_n('view')
_rz(z,o2DB,'class',253,e,s,gg)
var f3DB=_oz(z,254,e,s,gg)
_(o2DB,f3DB)
_(x1DB,o2DB)
var c4DB=_n('view')
_rz(z,c4DB,'class',255,e,s,gg)
var o6DB=_n('view')
_rz(z,o6DB,'class',256,e,s,gg)
var c7DB=_n('text')
_rz(z,c7DB,'class',257,e,s,gg)
var o8DB=_oz(z,258,e,s,gg)
_(c7DB,o8DB)
_(o6DB,c7DB)
var l9DB=_n('view')
_rz(z,l9DB,'class',259,e,s,gg)
var a0DB=_mz(z,'slider',['showValue',-1,'activeColor',260,'backgroundColor',1,'bindchange',2,'blockColor',3,'max',4,'min',5,'step',6,'value',7],[],e,s,gg)
_(l9DB,a0DB)
_(o6DB,l9DB)
_(c4DB,o6DB)
var tAEB=_n('view')
_rz(z,tAEB,'class',268,e,s,gg)
var eBEB=_n('text')
_rz(z,eBEB,'class',269,e,s,gg)
var bCEB=_oz(z,270,e,s,gg)
_(eBEB,bCEB)
_(tAEB,eBEB)
var oDEB=_n('view')
_rz(z,oDEB,'class',271,e,s,gg)
var xEEB=_mz(z,'slider',['showValue',-1,'activeColor',272,'backgroundColor',1,'bindchange',2,'blockColor',3,'max',4,'min',5,'step',6,'value',7],[],e,s,gg)
_(oDEB,xEEB)
_(tAEB,oDEB)
_(c4DB,tAEB)
var oFEB=_n('view')
_rz(z,oFEB,'class',280,e,s,gg)
var fGEB=_mz(z,'tui-list-cell',['hover',281,'padding',1],[],e,s,gg)
var cHEB=_n('view')
_rz(z,cHEB,'class',283,e,s,gg)
var hIEB=_n('text')
var oJEB=_oz(z,284,e,s,gg)
_(hIEB,oJEB)
_(cHEB,hIEB)
var cKEB=_mz(z,'switch',['bindchange',285,'checked',1,'class',2],[],e,s,gg)
_(cHEB,cKEB)
_(fGEB,cHEB)
_(oFEB,fGEB)
_(c4DB,oFEB)
var oLEB=_n('view')
_rz(z,oLEB,'class',288,e,s,gg)
var lMEB=_mz(z,'tui-list-cell',['hover',289,'padding',1],[],e,s,gg)
var aNEB=_n('view')
_rz(z,aNEB,'class',291,e,s,gg)
var tOEB=_n('text')
var ePEB=_oz(z,292,e,s,gg)
_(tOEB,ePEB)
_(aNEB,tOEB)
var bQEB=_mz(z,'switch',['bindchange',293,'checked',1,'class',2],[],e,s,gg)
_(aNEB,bQEB)
_(lMEB,aNEB)
_(oLEB,lMEB)
_(c4DB,oLEB)
var h5DB=_v()
_(c4DB,h5DB)
if(_oz(z,296,e,s,gg)){h5DB.wxVkey=1
var oREB=_n('view')
_rz(z,oREB,'class',297,e,s,gg)
var xSEB=_mz(z,'tui-list-cell',['hover',298,'padding',1],[],e,s,gg)
var oTEB=_n('view')
_rz(z,oTEB,'class',300,e,s,gg)
var fUEB=_n('text')
var cVEB=_oz(z,301,e,s,gg)
_(fUEB,cVEB)
_(oTEB,fUEB)
var hWEB=_mz(z,'switch',['bindchange',302,'checked',1,'class',2],[],e,s,gg)
_(oTEB,hWEB)
_(xSEB,oTEB)
_(oREB,xSEB)
_(h5DB,oREB)
}
h5DB.wxXCkey=1
h5DB.wxXCkey=3
_(x1DB,c4DB)
var oXEB=_n('view')
_rz(z,oXEB,'class',305,e,s,gg)
var cYEB=_mz(z,'button',['bindtap',306,'class',1,'height',2,'shape',3,'size',4],[],e,s,gg)
var oZEB=_oz(z,311,e,s,gg)
_(cYEB,oZEB)
_(oXEB,cYEB)
_(x1DB,oXEB)
_(r,x1DB)
var l1EB=_mz(z,'tui-top-dropdown',['bindclose',312,'height',1,'mask',2,'show',3,'style',4],[],e,s,gg)
var a2EB=_mz(z,'scroll-view',['scrollY',-1,'class',317],[],e,s,gg)
var t3EB=_v()
_(a2EB,t3EB)
var e4EB=function(o6EB,b5EB,x7EB,gg){
var c0EB=_n('view')
_rz(z,c0EB,'class',320,o6EB,b5EB,gg)
var hAFB=_mz(z,'image',['bind:tap',321,'class',1,'data-id',2,'mode',3,'src',4],[],o6EB,b5EB,gg)
var oBFB=_n('view')
_rz(z,oBFB,'class',326,o6EB,b5EB,gg)
var cCFB=_mz(z,'image',['class',327,'src',1],[],o6EB,b5EB,gg)
_(oBFB,cCFB)
_(hAFB,oBFB)
_(c0EB,hAFB)
var oDFB=_n('view')
_rz(z,oDFB,'class',329,o6EB,b5EB,gg)
var tGFB=_mz(z,'view',['bindtap',330,'class',1,'data-id',2],[],o6EB,b5EB,gg)
var eHFB=_n('view')
_rz(z,eHFB,'class',333,o6EB,b5EB,gg)
var bIFB=_v()
_(eHFB,bIFB)
var oJFB=function(oLFB,xKFB,fMFB,gg){
var hOFB=_n('text')
_rz(z,hOFB,'class',338,oLFB,xKFB,gg)
var oPFB=_oz(z,339,oLFB,xKFB,gg)
_(hOFB,oPFB)
_(fMFB,hOFB)
return fMFB
}
bIFB.wxXCkey=2
_2z(z,336,oJFB,o6EB,b5EB,gg,bIFB,'citem','cindex','index')
_(tGFB,eHFB)
var cQFB=_mz(z,'image',['class',340,'src',1],[],o6EB,b5EB,gg)
_(tGFB,cQFB)
_(oDFB,tGFB)
var lEFB=_v()
_(oDFB,lEFB)
if(_oz(z,342,o6EB,b5EB,gg)){lEFB.wxVkey=1
var oRFB=_n('view')
_rz(z,oRFB,'class',343,o6EB,b5EB,gg)
var lSFB=_n('text')
_rz(z,lSFB,'class',344,o6EB,b5EB,gg)
var aTFB=_oz(z,345,o6EB,b5EB,gg)
_(lSFB,aTFB)
_(oRFB,lSFB)
_(lEFB,oRFB)
}
var tUFB=_n('view')
_rz(z,tUFB,'class',346,o6EB,b5EB,gg)
var eVFB=_n('text')
_rz(z,eVFB,'class',347,o6EB,b5EB,gg)
var bWFB=_oz(z,348,o6EB,b5EB,gg)
_(eVFB,bWFB)
_(tUFB,eVFB)
_(oDFB,tUFB)
var aFFB=_v()
_(oDFB,aFFB)
if(_oz(z,349,o6EB,b5EB,gg)){aFFB.wxVkey=1
var oXFB=_n('view')
_rz(z,oXFB,'class',350,o6EB,b5EB,gg)
var xYFB=_v()
_(oXFB,xYFB)
var oZFB=function(c2FB,f1FB,h3FB,gg){
var c5FB=_mz(z,'view',['bind:tap',355,'class',1,'data-id',2],[],c2FB,f1FB,gg)
var o6FB=_oz(z,358,c2FB,f1FB,gg)
_(c5FB,o6FB)
_(h3FB,c5FB)
return h3FB
}
xYFB.wxXCkey=2
_2z(z,353,oZFB,o6EB,b5EB,gg,xYFB,'citem','cindex','index')
_(aFFB,oXFB)
}
var l7FB=_n('view')
_rz(z,l7FB,'class',359,o6EB,b5EB,gg)
var a8FB=_mz(z,'image',['bindtap',360,'class',1,'data-id',2,'src',3],[],o6EB,b5EB,gg)
_(l7FB,a8FB)
var t9FB=_mz(z,'image',['bindtap',364,'class',1,'data-id',2,'src',3],[],o6EB,b5EB,gg)
_(l7FB,t9FB)
var e0FB=_mz(z,'image',['bindtap',368,'class',1,'src',2],[],o6EB,b5EB,gg)
_(l7FB,e0FB)
_(oDFB,l7FB)
lEFB.wxXCkey=1
aFFB.wxXCkey=1
_(c0EB,oDFB)
_(x7EB,c0EB)
var f9EB=_v()
_(x7EB,f9EB)
if(_oz(z,371,o6EB,b5EB,gg)){f9EB.wxVkey=1
var bAGB=_mz(z,'view',['bindtap',372,'class',1,'data-id',2],[],o6EB,b5EB,gg)
var oBGB=_n('text')
var xCGB=_oz(z,375,o6EB,b5EB,gg)
_(oBGB,xCGB)
_(bAGB,oBGB)
var oDGB=_mz(z,'image',['class',376,'src',1],[],o6EB,b5EB,gg)
_(bAGB,oDGB)
_(f9EB,bAGB)
}
f9EB.wxXCkey=1
return x7EB
}
t3EB.wxXCkey=2
_2z(z,318,e4EB,e,s,gg,t3EB,'item','index','index')
_(l1EB,a2EB)
_(r,l1EB)
var c08=_v()
_(r,c08)
if(_oz(z,378,e,s,gg)){c08.wxVkey=1
var fEGB=_n('view')
_rz(z,fEGB,'class',379,e,s,gg)
var cFGB=_mz(z,'view',['bindtap',380,'class',1],[],e,s,gg)
var hGGB=_oz(z,382,e,s,gg)
_(cFGB,hGGB)
_(fEGB,cFGB)
var oHGB=_mz(z,'image',['class',383,'mode',1,'src',2],[],e,s,gg)
_(fEGB,oHGB)
var cIGB=_mz(z,'button',['bindtap',386,'class',1],[],e,s,gg)
var oJGB=_oz(z,388,e,s,gg)
_(cIGB,oJGB)
_(fEGB,cIGB)
_(c08,fEGB)
}
var lKGB=_mz(z,'canvas',['class',389,'id',1,'type',2],[],e,s,gg)
_(r,lKGB)
var hA9=_v()
_(r,hA9)
if(_oz(z,392,e,s,gg)){hA9.wxVkey=1
var aLGB=_mz(z,'view',['catch:tap',393,'class',1],[],e,s,gg)
var tMGB=_mz(z,'image',['class',395,'src',1],[],e,s,gg)
_(aLGB,tMGB)
_(hA9,aLGB)
}
var oB9=_v()
_(r,oB9)
if(_oz(z,397,e,s,gg)){oB9.wxVkey=1
var eNGB=_mz(z,'view',['catch:tap',398,'class',1],[],e,s,gg)
var bOGB=_v()
_(eNGB,bOGB)
if(_oz(z,400,e,s,gg)){bOGB.wxVkey=1
var xQGB=_n('view')
_rz(z,xQGB,'class',401,e,s,gg)
var oRGB=_n('view')
_rz(z,oRGB,'class',402,e,s,gg)
var fSGB=_v()
_(oRGB,fSGB)
var cTGB=function(oVGB,hUGB,cWGB,gg){
var lYGB=_mz(z,'image',['class',405,'src',1],[],oVGB,hUGB,gg)
_(cWGB,lYGB)
return cWGB
}
fSGB.wxXCkey=2
_2z(z,403,cTGB,e,s,gg,fSGB,'item','index','index')
var aZGB=_v()
_(oRGB,aZGB)
var t1GB=function(b3GB,e2GB,o4GB,gg){
var o6GB=_mz(z,'image',['class',409,'src',1],[],b3GB,e2GB,gg)
_(o4GB,o6GB)
return o4GB
}
aZGB.wxXCkey=2
_2z(z,407,t1GB,e,s,gg,aZGB,'item','index','index')
_(xQGB,oRGB)
var f7GB=_n('view')
_rz(z,f7GB,'class',411,e,s,gg)
var c8GB=_v()
_(f7GB,c8GB)
if(_oz(z,412,e,s,gg)){c8GB.wxVkey=1
var h9GB=_mz(z,'image',['class',413,'mode',1,'src',2],[],e,s,gg)
_(c8GB,h9GB)
}
var o0GB=_n('text')
_rz(z,o0GB,'class',416,e,s,gg)
var cAHB=_oz(z,417,e,s,gg)
_(o0GB,cAHB)
_(f7GB,o0GB)
c8GB.wxXCkey=1
_(xQGB,f7GB)
_(bOGB,xQGB)
var oBHB=_n('view')
_rz(z,oBHB,'class',418,e,s,gg)
var lCHB=_n('text')
_rz(z,lCHB,'class',419,e,s,gg)
var aDHB=_oz(z,420,e,s,gg)
_(lCHB,aDHB)
_(oBHB,lCHB)
_(bOGB,oBHB)
var oPGB=_v()
_(bOGB,oPGB)
if(_oz(z,421,e,s,gg)){oPGB.wxVkey=1
var tEHB=_n('view')
_rz(z,tEHB,'class',422,e,s,gg)
var eFHB=_mz(z,'view',['catch:tap',423,'class',1,'data-type',2],[],e,s,gg)
var bGHB=_n('view')
_rz(z,bGHB,'class',426,e,s,gg)
var oHHB=_n('text')
_rz(z,oHHB,'class',427,e,s,gg)
_(bGHB,oHHB)
_(eFHB,bGHB)
var xIHB=_n('text')
_rz(z,xIHB,'class',428,e,s,gg)
var oJHB=_oz(z,429,e,s,gg)
_(xIHB,oJHB)
_(eFHB,xIHB)
_(tEHB,eFHB)
var fKHB=_mz(z,'view',['catch:tap',430,'class',1],[],e,s,gg)
var cLHB=_n('view')
_rz(z,cLHB,'class',432,e,s,gg)
var hMHB=_n('text')
_rz(z,hMHB,'class',433,e,s,gg)
_(cLHB,hMHB)
_(fKHB,cLHB)
var oNHB=_n('text')
_rz(z,oNHB,'class',434,e,s,gg)
var cOHB=_oz(z,435,e,s,gg)
_(oNHB,cOHB)
_(fKHB,oNHB)
_(tEHB,fKHB)
var oPHB=_mz(z,'view',['catch:tap',436,'class',1,'data-type',2],[],e,s,gg)
var lQHB=_n('view')
_rz(z,lQHB,'class',439,e,s,gg)
var aRHB=_n('text')
_rz(z,aRHB,'class',440,e,s,gg)
_(lQHB,aRHB)
_(oPHB,lQHB)
var tSHB=_n('text')
_rz(z,tSHB,'class',441,e,s,gg)
var eTHB=_oz(z,442,e,s,gg)
_(tSHB,eTHB)
_(oPHB,tSHB)
_(tEHB,oPHB)
_(oPGB,tEHB)
}
oPGB.wxXCkey=1
}
else{bOGB.wxVkey=2
var bUHB=_n('view')
_rz(z,bUHB,'class',443,e,s,gg)
var oVHB=_n('view')
_rz(z,oVHB,'class',444,e,s,gg)
_(bUHB,oVHB)
var xWHB=_n('view')
_rz(z,xWHB,'class',445,e,s,gg)
var oXHB=_n('text')
_rz(z,oXHB,'class',446,e,s,gg)
var fYHB=_oz(z,447,e,s,gg)
_(oXHB,fYHB)
_(xWHB,oXHB)
_(bUHB,xWHB)
var cZHB=_n('view')
_rz(z,cZHB,'class',448,e,s,gg)
var h1HB=_oz(z,449,e,s,gg)
_(cZHB,h1HB)
_(bUHB,cZHB)
var o2HB=_n('view')
_rz(z,o2HB,'class',450,e,s,gg)
_(bUHB,o2HB)
var c3HB=_n('view')
_rz(z,c3HB,'class',451,e,s,gg)
var o4HB=_mz(z,'view',['catch:tap',452,'class',1],[],e,s,gg)
var l5HB=_n('text')
_rz(z,l5HB,'class',454,e,s,gg)
var a6HB=_oz(z,455,e,s,gg)
_(l5HB,a6HB)
_(o4HB,l5HB)
var t7HB=_n('view')
_rz(z,t7HB,'class',456,e,s,gg)
var e8HB=_v()
_(t7HB,e8HB)
var b9HB=function(xAIB,o0HB,oBIB,gg){
var cDIB=_mz(z,'text',['class',459,'style',1],[],xAIB,o0HB,gg)
var hEIB=_oz(z,461,xAIB,o0HB,gg)
_(cDIB,hEIB)
_(oBIB,cDIB)
return oBIB
}
e8HB.wxXCkey=2
_2z(z,457,b9HB,e,s,gg,e8HB,'item','index','*this')
_(o4HB,t7HB)
var oFIB=_n('text')
_rz(z,oFIB,'class',462,e,s,gg)
var cGIB=_oz(z,463,e,s,gg)
_(oFIB,cGIB)
_(o4HB,oFIB)
_(c3HB,o4HB)
var oHIB=_mz(z,'view',['catch:tap',464,'class',1],[],e,s,gg)
var lIIB=_n('text')
_rz(z,lIIB,'class',466,e,s,gg)
var aJIB=_oz(z,467,e,s,gg)
_(lIIB,aJIB)
_(oHIB,lIIB)
var tKIB=_n('view')
_rz(z,tKIB,'class',468,e,s,gg)
var eLIB=_v()
_(tKIB,eLIB)
var bMIB=function(xOIB,oNIB,oPIB,gg){
var cRIB=_mz(z,'text',['class',471,'style',1],[],xOIB,oNIB,gg)
var hSIB=_oz(z,473,xOIB,oNIB,gg)
_(cRIB,hSIB)
_(oPIB,cRIB)
return oPIB
}
eLIB.wxXCkey=2
_2z(z,469,bMIB,e,s,gg,eLIB,'item','index','*this')
_(oHIB,tKIB)
var oTIB=_n('text')
_rz(z,oTIB,'class',474,e,s,gg)
var cUIB=_oz(z,475,e,s,gg)
_(oTIB,cUIB)
_(oHIB,oTIB)
_(c3HB,oHIB)
var oVIB=_mz(z,'view',['catch:tap',476,'class',1],[],e,s,gg)
var lWIB=_n('text')
_rz(z,lWIB,'class',478,e,s,gg)
var aXIB=_oz(z,479,e,s,gg)
_(lWIB,aXIB)
_(oVIB,lWIB)
var tYIB=_n('view')
_rz(z,tYIB,'class',480,e,s,gg)
var eZIB=_v()
_(tYIB,eZIB)
var b1IB=function(x3IB,o2IB,o4IB,gg){
var c6IB=_mz(z,'text',['class',483,'style',1],[],x3IB,o2IB,gg)
var h7IB=_oz(z,485,x3IB,o2IB,gg)
_(c6IB,h7IB)
_(o4IB,c6IB)
return o4IB
}
eZIB.wxXCkey=2
_2z(z,481,b1IB,e,s,gg,eZIB,'item','index','*this')
_(oVIB,tYIB)
var o8IB=_n('text')
_rz(z,o8IB,'class',486,e,s,gg)
var c9IB=_oz(z,487,e,s,gg)
_(o8IB,c9IB)
_(oVIB,o8IB)
_(c3HB,oVIB)
_(bUHB,c3HB)
var o0IB=_n('view')
_rz(z,o0IB,'class',488,e,s,gg)
_(bUHB,o0IB)
var lAJB=_n('view')
_rz(z,lAJB,'class',489,e,s,gg)
var aBJB=_n('text')
_rz(z,aBJB,'class',490,e,s,gg)
var tCJB=_oz(z,491,e,s,gg)
_(aBJB,tCJB)
_(lAJB,aBJB)
_(bUHB,lAJB)
var eDJB=_n('view')
_rz(z,eDJB,'class',492,e,s,gg)
var bEJB=_mz(z,'button',['catch:tap',493,'class',1],[],e,s,gg)
var oFJB=_n('text')
_rz(z,oFJB,'class',495,e,s,gg)
var xGJB=_oz(z,496,e,s,gg)
_(oFJB,xGJB)
_(bEJB,oFJB)
var oHJB=_oz(z,497,e,s,gg)
_(bEJB,oHJB)
_(eDJB,bEJB)
var fIJB=_mz(z,'button',['catch:tap',498,'class',1],[],e,s,gg)
var cJJB=_n('text')
_rz(z,cJJB,'class',500,e,s,gg)
var hKJB=_oz(z,501,e,s,gg)
_(cJJB,hKJB)
_(fIJB,cJJB)
var oLJB=_oz(z,502,e,s,gg)
_(fIJB,oLJB)
_(eDJB,fIJB)
_(bUHB,eDJB)
_(bOGB,bUHB)
}
bOGB.wxXCkey=1
_(oB9,eNGB)
}
var cC9=_v()
_(r,cC9)
if(_oz(z,503,e,s,gg)){cC9.wxVkey=1
var cMJB=_n('view')
_rz(z,cMJB,'class',504,e,s,gg)
var oNJB=_n('view')
_rz(z,oNJB,'class',505,e,s,gg)
var lOJB=_v()
_(oNJB,lOJB)
if(_oz(z,506,e,s,gg)){lOJB.wxVkey=1
var aPJB=_n('view')
var tQJB=_mz(z,'image',['class',507,'mode',1,'src',2],[],e,s,gg)
_(aPJB,tQJB)
_(lOJB,aPJB)
}
var eRJB=_mz(z,'scroll-view',['scrollY',-1,'class',510],[],e,s,gg)
var bSJB=_n('view')
_rz(z,bSJB,'class',511,e,s,gg)
var xUJB=_n('view')
_rz(z,xUJB,'class',512,e,s,gg)
var oVJB=_v()
_(xUJB,oVJB)
var fWJB=function(hYJB,cXJB,oZJB,gg){
var o2JB=_n('view')
_rz(z,o2JB,'class',515,hYJB,cXJB,gg)
var a4JB=_mz(z,'view',['bindtap',516,'class',1,'data-index',2],[],hYJB,cXJB,gg)
var t5JB=_v()
_(a4JB,t5JB)
if(_oz(z,519,hYJB,cXJB,gg)){t5JB.wxVkey=1
var b7JB=_n('text')
_rz(z,b7JB,'class',520,hYJB,cXJB,gg)
var o8JB=_oz(z,521,hYJB,cXJB,gg)
_(b7JB,o8JB)
_(t5JB,b7JB)
}
var x9JB=_n('view')
_rz(z,x9JB,'class',522,hYJB,cXJB,gg)
_(a4JB,x9JB)
var e6JB=_v()
_(a4JB,e6JB)
if(_oz(z,523,hYJB,cXJB,gg)){e6JB.wxVkey=1
var o0JB=_n('view')
_rz(z,o0JB,'class',524,hYJB,cXJB,gg)
var fAKB=_n('text')
_rz(z,fAKB,'class',525,hYJB,cXJB,gg)
var cBKB=_oz(z,526,hYJB,cXJB,gg)
_(fAKB,cBKB)
_(o0JB,fAKB)
_(e6JB,o0JB)
}
t5JB.wxXCkey=1
e6JB.wxXCkey=1
_(o2JB,a4JB)
var l3JB=_v()
_(o2JB,l3JB)
if(_oz(z,527,hYJB,cXJB,gg)){l3JB.wxVkey=1
var hCKB=_n('text')
_rz(z,hCKB,'class',528,hYJB,cXJB,gg)
var oDKB=_oz(z,529,hYJB,cXJB,gg)
_(hCKB,oDKB)
_(l3JB,hCKB)
}
l3JB.wxXCkey=1
_(oZJB,o2JB)
return oZJB
}
oVJB.wxXCkey=2
_2z(z,513,fWJB,e,s,gg,oVJB,'item','index','index')
_(bSJB,xUJB)
var oTJB=_v()
_(bSJB,oTJB)
if(_oz(z,530,e,s,gg)){oTJB.wxVkey=1
var cEKB=_n('view')
_rz(z,cEKB,'class',531,e,s,gg)
var oFKB=_v()
_(cEKB,oFKB)
var lGKB=function(tIKB,aHKB,eJKB,gg){
var oLKB=_mz(z,'view',['bindtap',534,'class',1,'data-index',2],[],tIKB,aHKB,gg)
var xMKB=_oz(z,537,tIKB,aHKB,gg)
_(oLKB,xMKB)
_(eJKB,oLKB)
return eJKB
}
oFKB.wxXCkey=2
_2z(z,532,lGKB,e,s,gg,oFKB,'item','index','index')
_(oTJB,cEKB)
}
oTJB.wxXCkey=1
_(eRJB,bSJB)
_(oNJB,eRJB)
var oNKB=_n('view')
_rz(z,oNKB,'class',538,e,s,gg)
var fOKB=_mz(z,'view',['bindtap',539,'class',1],[],e,s,gg)
var cPKB=_oz(z,541,e,s,gg)
_(fOKB,cPKB)
_(oNKB,fOKB)
var hQKB=_mz(z,'view',['bindtap',542,'class',1],[],e,s,gg)
var oRKB=_v()
_(hQKB,oRKB)
if(_oz(z,544,e,s,gg)){oRKB.wxVkey=1
var lUKB=_oz(z,545,e,s,gg)
_(oRKB,lUKB)
}
var cSKB=_v()
_(hQKB,cSKB)
if(_oz(z,546,e,s,gg)){cSKB.wxVkey=1
var aVKB=_oz(z,547,e,s,gg)
_(cSKB,aVKB)
}
var oTKB=_v()
_(hQKB,oTKB)
if(_oz(z,548,e,s,gg)){oTKB.wxVkey=1
var tWKB=_oz(z,549,e,s,gg)
_(oTKB,tWKB)
}
oRKB.wxXCkey=1
cSKB.wxXCkey=1
oTKB.wxXCkey=1
_(oNKB,hQKB)
var eXKB=_mz(z,'view',['bindtap',550,'class',1],[],e,s,gg)
var bYKB=_oz(z,552,e,s,gg)
_(eXKB,bYKB)
_(oNKB,eXKB)
_(oNJB,oNKB)
lOJB.wxXCkey=1
_(cMJB,oNJB)
_(cC9,cMJB)
}
var oD9=_v()
_(r,oD9)
if(_oz(z,553,e,s,gg)){oD9.wxVkey=1
var oZKB=_n('view')
_rz(z,oZKB,'class',554,e,s,gg)
var x1KB=_n('view')
_rz(z,x1KB,'class',555,e,s,gg)
var o2KB=_mz(z,'canvas',['class',556,'id',1,'style',2,'type',3],[],e,s,gg)
_(x1KB,o2KB)
var f3KB=_mz(z,'image',['showMenuByLongpress',-1,'class',560,'mode',1,'src',2],[],e,s,gg)
_(x1KB,f3KB)
var c4KB=_n('view')
_rz(z,c4KB,'class',563,e,s,gg)
var h5KB=_mz(z,'button',['bindtap',564,'class',1],[],e,s,gg)
var o6KB=_oz(z,566,e,s,gg)
_(h5KB,o6KB)
_(c4KB,h5KB)
var c7KB=_mz(z,'button',['bindtap',567,'class',1],[],e,s,gg)
var o8KB=_oz(z,569,e,s,gg)
_(c7KB,o8KB)
_(c4KB,c7KB)
_(x1KB,c4KB)
_(oZKB,x1KB)
_(oD9,oZKB)
}
f98.wxXCkey=1
f98.wxXCkey=3
c08.wxXCkey=1
hA9.wxXCkey=1
oB9.wxXCkey=1
cC9.wxXCkey=1
oD9.wxXCkey=1
return r
}
e_[x[1]]={f:m1,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx_XC_20";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx_XC_20();	if (__vd_version_info__.delayedGwx) __wxAppCode__['components/tui-top-dropdown/tui-top-dropdown.wxml'] = [$gwx_XC_20, './components/tui-top-dropdown/tui-top-dropdown.wxml'];else __wxAppCode__['components/tui-top-dropdown/tui-top-dropdown.wxml'] = $gwx_XC_20( './components/tui-top-dropdown/tui-top-dropdown.wxml' );
		if (__vd_version_info__.delayedGwx) __wxAppCode__['pages/card/card.wxml'] = [$gwx_XC_20, './pages/card/card.wxml'];else __wxAppCode__['pages/card/card.wxml'] = $gwx_XC_20( './pages/card/card.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['components/tui-top-dropdown/tui-top-dropdown.wxss']=setCssToHead([".",[1],"tui-dropdown-box{border-bottom-left-radius:",[0,24],";border-bottom-right-radius:",[0,24],";box-sizing:border-box;overflow:hidden;position:fixed;top:0;-webkit-transform:translateZ(0);transform:translateZ(0);transition:all .3s ease-in-out;width:100%;z-index:996}\n.",[1],"tui-dropdown-mask{background-color:rgba(0,0,0,.6);bottom:0;left:0;opacity:0;position:fixed;right:0;top:0;transition:all .3s ease-in-out;visibility:hidden;z-index:986}\n.",[1],"tui-mask-show{opacity:1;visibility:visible}\n",],undefined,{path:"./components/tui-top-dropdown/tui-top-dropdown.wxss"});__wxAppCode__['pages/card/card.wxss']=setCssToHead([[2,"./static/animation.wxss"],"body{margin:0;min-height:100vh;padding:0;width:100%}\n.",[1],"container{padding-bottom:env(safe-area-inset-bottom)}\n.",[1],"tui-banner-swiper{height:100%;position:relative}\n@-webkit-keyframes breathe{0%,100%{opacity:.6;-webkit-transform:scale(.8);transform:scale(.8)}\n50%{opacity:.9;-webkit-transform:scale(1.1);transform:scale(1.1)}\n}@-webkit-keyframes ripple{0%{opacity:.8;-webkit-transform:scale(1);transform:scale(1)}\n100%{opacity:0;-webkit-transform:scale(2.5);transform:scale(2.5)}\n}@keyframes ripple{0%{opacity:.8;-webkit-transform:scale(1);transform:scale(1)}\n100%{opacity:0;-webkit-transform:scale(2.5);transform:scale(2.5)}\n}@-webkit-keyframes blink{0%{opacity:.4;-webkit-transform:scale(.8);transform:scale(.8)}\n50%{opacity:.8;-webkit-transform:scale(1.1);transform:scale(1.1)}\n100%{opacity:.4;-webkit-transform:scale(.8);transform:scale(.8)}\n}@keyframes blink{0%{opacity:.4;-webkit-transform:scale(.8);transform:scale(.8)}\n50%{opacity:.8;-webkit-transform:scale(1.1);transform:scale(1.1)}\n100%{opacity:.4;-webkit-transform:scale(.8);transform:scale(.8)}\n}.",[1],"hotspot-container{height:",[0,120],";position:absolute;-webkit-transform:translate(-50%,-50%);transform:translate(-50%,-50%);width:",[0,120],"}\n.",[1],"hotspot-container,.",[1],"star-wrapper{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center}\n.",[1],"star-wrapper{height:",[0,68],";position:relative;width:",[0,68],";z-index:10}\n.",[1],"blink{-webkit-animation:breathe 1.2s ease-in-out infinite;animation:breathe 1.2s ease-in-out infinite}\n.",[1],"breathe-effect{-webkit-animation:breathe 3s 1 forwards;animation:breathe 3s 1 forwards;transition:all .2s ease}\n.",[1],"ripple::after{-webkit-animation:ripple-ani 1.2s ease-out infinite;animation:ripple-ani 1.2s ease-out infinite;border:",[0,6]," solid gold;border-radius:50%;box-sizing:border-box;content:\x22\x22;height:",[0,100],";left:50%;margin-left:",[0,-50],";margin-top:",[0,-50],";pointer-events:none;position:absolute;top:50%;width:",[0,100],"}\n@-webkit-keyframes ripple-ani{0%{opacity:1;-webkit-transform:scale(1);transform:scale(1)}\n100%{opacity:0;-webkit-transform:scale(2.5);transform:scale(2.5)}\n}@keyframes ripple-ani{0%{opacity:1;-webkit-transform:scale(1);transform:scale(1)}\n100%{opacity:0;-webkit-transform:scale(2.5);transform:scale(2.5)}\n}@keyframes breathe{0%,100%{opacity:.4;-webkit-transform:scale(.8);transform:scale(.8)}\n50%{opacity:.8;-webkit-transform:scale(1.1);transform:scale(1.1)}\n}.",[1],"banner-item{-webkit-flex-direction:column;flex-direction:column}\n.",[1],"banner-item,.",[1],"top-view{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"top-view{-webkit-flex-direction:row;flex-direction:row;-webkit-justify-content:space-between;justify-content:space-between;padding-left:",[0,10],";padding-right:",[0,10],";position:fixed;top:",[0,0],";width:100%;z-index:99}\n.",[1],"setting{left:",[0,20],"}\n.",[1],"tui-banner-tag{color:#fff;left:0;position:fixed;top:",[0,120],"}\n.",[1],"auto_icon{right:0}\n.",[1],"auto_icon_btn{height:",[0,80],";width:",[0,80],"}\n.",[1],"tui-slide-image{border-radius:",[0,12],";height:100%;top:0}\n.",[1],"tui-button-top{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;height:",[0,120],";-webkit-justify-content:center;justify-content:center;width:100%}\n.",[1],"pdf_view{width:100%}\n.",[1],"tui-padding{box-sizing:border-box;padding:0 ",[0,30],"}\n.",[1],"tui-size{font-size:",[0,24],";line-height:",[0,28],"}\n.",[1],"tui-gray{color:#999}\nwx-tui-macaron{color:#ff9b6a}\n.",[1],"bg-macaron{background-color:#ff9b6a;color:var(--black)}\n.",[1],"lines-macaron{color:#ff9b6a}\n.",[1],"tui-icon-red{color:#ff201f}\n.",[1],"tui-mtop{margin-top:",[0,26],"}\n.",[1],"tui-pro-detail{box-sizing:border-box;color:#333}\n.",[1],"bg-img1{background-position:50%;background-size:cover}\n.",[1],"bg-img1,.",[1],"bg-img2{background-attachment:fixed;background-repeat:no-repeat}\n.",[1],"bg-img2{background-position:0 0;background-size:100%}\n.",[1],"bg-img3{background-attachment:fixed;background-position:50%;background-repeat:no-repeat;background-size:cover}\n.",[1],"pad-image,.",[1],"tui-product-title1{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;width:100%}\n.",[1],"tui-product-title1{background:#f1f1f1;border-radius:",[0,50],";bottom:",[0,0],";-webkit-flex-direction:column;flex-direction:column;font-size:",[0,50],";font-weight:500;height:",[0,160],";opacity:.7;position:fixed;z-index:99}\n.",[1],"tui-pro-titbox1{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;font-size:",[0,50],";font-weight:500;padding:",[0,10]," ",[0,14],"}\n.",[1],"tui-product-title2{font-size:",[0,56],";font-weight:500;line-height:1.6;padding:",[0,20]," ",[0,80]," ",[0,20]," ",[0,20],";position:relative;word-spacing:",[0,4],";z-index:99}\n.",[1],"tui-pro-titbox2{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;font-size:",[0,42],";font-weight:500;padding:",[0,10]," ",[0,14],"}\n.",[1],"tui-product-title3{font-size:",[0,42],";font-weight:500;padding:",[0,20]," ",[0,80]," ",[0,20]," ",[0,20],";position:relative;z-index:99}\n.",[1],"tui-pro-titbox3{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;font-size:",[0,42],";font-weight:500;padding:",[0,10]," ",[0,14],"}\n.",[1],"tui-pro-title{padding-top:",[0,20],"}\n.",[1],"tui-share-btn{background:transparent;border:0;border-radius:0;display:block;margin:0;padding:0}\n.",[1],"tui-share-btn::after{border:0}\n.",[1],"tui-share-box{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-share-position{position:absolute;right:0;top:",[0,30],"}\n.",[1],"tui-share-text{padding-left:",[0,8],"}\n.",[1],"tui-sub-title{line-height:",[0,36],";padding:",[0,20]," 0}\n.",[1],"tui-sale-info{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between;padding-top:",[0,20],"}\n.",[1],"tui-discount-box{background:#fff}\n.",[1],"tui-list-cell{-webkit-align-items:center;align-items:center;box-sizing:border-box;display:-webkit-flex;display:flex;font-size:",[0,26],";line-height:",[0,26],";padding:",[0,30],";position:relative;width:100%}\n.",[1],"tui-right{position:absolute;right:",[0,30],";top:",[0,30],"}\n.",[1],"tui-top40{top:",[0,40],"!important}\n.",[1],"tui-bold{font-weight:700}\n.",[1],"tui-last::after{border-bottom:0!important}\n.",[1],"tui-flex-center{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-cell-title{-webkit-flex-shrink:0;flex-shrink:0;padding-right:",[0,30],";width:",[0,66],"}\n.",[1],"tui-promotion-box{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;padding:",[0,10]," 0;width:80%}\n.",[1],"tui-promotion-box wx-text{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;width:70%}\n.",[1],"tui-basic-info{background:#fff}\n.",[1],"tui-addr-box{width:76%}\n.",[1],"tui-addr-item{line-height:",[0,34],";padding:",[0,10],"}\n.",[1],"tui-guarantee{font-size:",[0,24],";margin-bottom:",[0,20],";margin-top:",[0,20],";padding:",[0,20]," ",[0,30]," ",[0,30],"}\n.",[1],"tui-guarantee-item{color:#999;padding-right:",[0,30],";padding-top:",[0,10],"}\n.",[1],"tui-pl{padding-left:",[0,4],"}\n.",[1],"tui-cmt-box{background:#fff}\n.",[1],"tui-between{-webkit-justify-content:space-between!important;justify-content:space-between!important}\n.",[1],"tui-cmt-all{color:#ff201f;padding-right:",[0,8],"}\n.",[1],"tui-cmt-content{font-size:",[0,26],"}\n.",[1],"tui-cmt-user{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-acatar{border-radius:",[0,30],";display:block;height:",[0,60],";margin-right:",[0,16],";width:",[0,60],"}\n.",[1],"tui-cmt{padding:",[0,20]," 0}\n.",[1],"tui-attr{color:#999;font-size:",[0,24],";padding:",[0,6]," 0}\n.",[1],"tui-opacity{opacity:.5}\n.",[1],"tui-scale-small{-webkit-transform:scale(.9);transform:scale(.9);-webkit-transform-origin:center center;transform-origin:center center}\n.",[1],"tui-right-flex{-webkit-justify-content:center;justify-content:center}\n.",[1],"tui-flex,.",[1],"tui-right-flex{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-flex{-webkit-justify-content:space-between;justify-content:space-between}\n.",[1],"tui-level-title{word-wrap:break-word;font-size:",[0,32],";font-weight:500;padding:0 ",[0,10],";word-break:break-all}\n.",[1],"tui-popup-class{border-top-left-radius:",[0,24],";border-top-right-radius:",[0,24],";padding-bottom:env(safe-area-inset-bottom)}\n.",[1],"tui-popup-box{padding:",[0,30]," 0;position:relative}\n.",[1],"tui-popup-btn{bottom:0;left:0;position:absolute;width:100%}\n.",[1],"tui-product-box{-webkit-align-items:flex-end;align-items:flex-end;display:-webkit-flex;display:flex;font-size:",[0,24],";padding-bottom:",[0,30],"}\n.",[1],"tui-popup-img{border-radius:",[0,24],";display:block;height:",[0,200],";width:",[0,200],"}\n.",[1],"tui-popup-price{padding-bottom:",[0,8],";padding-left:",[0,20],"}\n.",[1],"tui-number{color:#999;font-size:",[0,24],";line-height:",[0,24],";padding-top:",[0,12],"}\n.",[1],"tui-attr-title{color:#333;padding:",[0,10]," 0}\n.",[1],"tui-attr-box{font-size:0;padding:",[0,20]," 0}\n.",[1],"tui-safearea-bottom{height:env(safe-area-inset-bottom);width:100%}\n.",[1],"tui-tabbar::before{border-top:",[0,1]," solid #d2d2d2;content:\x22\x22;left:0;position:absolute;top:0;-webkit-transform:scaleY(.5);transform:scaleY(.5);width:100%}\n.",[1],"tui-tabbar-item{-webkit-align-items:center;align-items:center;color:#aaa;display:-webkit-flex;display:flex;-webkit-flex:1;flex:1;-webkit-flex-direction:column;flex-direction:column;font-size:",[0,28],";height:",[0,90],";-webkit-justify-content:space-between;justify-content:space-between;width:25%}\n.",[1],"tui-item-active{color:#00c0fb!important}\n.",[1],"tui-modal-custom{text-align:center}\n.",[1],"tui-modal-custom-text{color:#333;font-size:",[0,30],";padding:",[0,30]," 0 ",[0,20],"}\n.",[1],"tui-header{-webkit-align-items:center;align-items:center;background-color:#fff;border-top-left-radius:",[0,20],";border-top-right-radius:",[0,20],";box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;overflow:hidden;padding:",[0,20],";position:relative;width:100%}\n.",[1],"tui-icon-close{position:absolute;right:",[0,30],";top:50%;-webkit-transform:translateY(-50%);transform:translateY(-50%)}\n.",[1],"tui-flex-box{-webkit-align-items:flex-start;align-items:flex-start;-webkit-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:flex-start;justify-content:flex-start;margin-bottom:",[0,26],";margin-left:",[0,30],";width:100%}\n.",[1],"star-speak,.",[1],"tui-flex-box{display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row}\n.",[1],"star-speak{-webkit-align-items:center;align-items:center;-webkit-justify-content:center;justify-content:center;width:80%}\n.",[1],"icon-star-speak{height:",[0,60],";width:",[0,60],"}\n.",[1],"icon-star-speak.",[1],"small{height:",[0,48],";width:",[0,48],"}\n.",[1],"icon-grid{height:",[0,80],";width:",[0,80],"}\n.",[1],"icon-set{height:",[0,64],";width:",[0,64],"}\n.",[1],"icon-voice{height:",[0,60],";width:",[0,60],"}\n.",[1],"icon-volume{height:",[0,64],";width:",[0,64],"}\n.",[1],"tui-order-list{max-height:",[0,630],";min-height:",[0,560],";padding:0 ",[0,25],"}\n.",[1],"tui-order-list,.",[1],"tui-setting-list{box-sizing:border-box;width:100%;z-index:999}\n.",[1],"tui-setting-list{max-height:",[0,800],"}\n.",[1],"tui-order-item{border-radius:",[0,12],";box-shadow:0 ",[0,5]," ",[0,10]," 0 rgba(0,0,0,.06);margin-bottom:",[0,10],";margin-top:",[0,10],";overflow:hidden}\n.",[1],"tui-goods-item{box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between;padding:",[0,20]," ",[0,0],";width:100%}\n.",[1],"tui-goods-img{border-radius:",[0,12],";display:block;-webkit-flex-shrink:0;flex-shrink:0;height:",[0,480],";width:47%}\n.",[1],"tui-goods-center{box-sizing:border-box;-webkit-flex-direction:column;flex-direction:column;-webkit-justify-content:space-evenly;justify-content:space-evenly;padding-top:",[0,10],";width:47%}\n.",[1],"tui-goods-center,.",[1],"tui-word-name{display:-webkit-flex;display:flex}\n.",[1],"tui-word-name{-webkit-align-items:center;align-items:center;-webkit-flex-direction:row;flex-direction:row;font-size:",[0,32],";-webkit-justify-content:left;justify-content:left;line-height:",[0,42],";min-height:",[0,60],"}\n.",[1],"word-container{white-space:pre-wrap}\n.",[1],"tui-goods-name{font-size:",[0,32],";line-height:",[0,42],";min-height:",[0,60],"}\n.",[1],"list-view{overflow:hidden;position:relative;width:100%}\n.",[1],"list-view::after{border-top:",[0,1]," solid #eaeef1;content:\x22\x22;left:0;position:absolute;right:0;top:0;-webkit-transform:scaleY(.5);transform:scaleY(.5)}\n.",[1],"tui-page__hd{box-sizing:border-box;padding:",[0,20],";width:100%}\n.",[1],"tui-page__bd{margin-top:20px;padding-bottom:40px}\n.",[1],"tui-page__title{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;font-size:",[0,40],";font-weight:400;-webkit-justify-content:center;justify-content:center}\n.",[1],"tui-page__desc{color:#888;font-size:",[0,28],";margin-top:",[0,32],";text-align:left}\n.",[1],"tui-section__title{padding:",[0,20]," ",[0,30],"}\n.",[1],"tui-page__spacing .",[1],"thorui-radio{margin-right:",[0,30],"}\n.",[1],"tui-list-view{margin-top:",[0,30],"}\n.",[1],"tui-list-view .",[1],"thorui-radio{height:100%;width:100%}\n.",[1],"icon-list{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;height:",[0,640],";-webkit-justify-content:space-between;justify-content:space-between;position:fixed;right:",[0,20],";top:50%;-webkit-transform:translateY(-40%);transform:translateY(-40%);z-index:99}\n.",[1],"autoPage{bottom:",[0,850],"}\n.",[1],"autoPage,.",[1],"word{background-size:100%;position:fixed;right:",[0,20],"}\n.",[1],"word{bottom:",[0,700],"}\n.",[1],"quiz{background-size:100%;bottom:",[0,550],";z-index:999}\n.",[1],"quiz,.",[1],"translate{position:fixed;right:",[0,20],"}\n.",[1],"translate{bottom:",[0,390],"}\n.",[1],"recorder{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;-webkit-justify-content:center;justify-content:center;z-index:999}\n.",[1],"recorderSave{bottom:",[0,180],";position:fixed;right:",[0,32],"}\n.",[1],"share{margin-left:",[0,2],"}\n.",[1],"share wx-button{border:none;height:",[0,72],";padding:0;width:",[0,72],"}\n.",[1],"share-image{height:",[0,72],";width:100%}\n.",[1],"icon-right1{height:",[0,90],";width:",[0,90],";z-index:999}\n.",[1],"icon-right2{height:",[0,80],";width:",[0,80],";z-index:999}\n.",[1],"icon-right3{height:",[0,78],";width:",[0,78],";z-index:999}\n.",[1],"icon-right4{height:",[0,72],";width:",[0,72],";z-index:999}\n.",[1],"tui-prompt-title{font-size:",[0,34],";padding-bottom:",[0,20],"}\n.",[1],"tui-button-bottom{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;height:",[0,120],";-webkit-justify-content:center;justify-content:center;width:100%}\n.",[1],"tui-modal-input{border-bottom:",[0,1]," solid #e6e6e6;font-size:",[0,32],";margin:",[0,30]," auto ",[0,50],";width:80%}\n.",[1],"tui-hidden-input{width:0}\n.",[1],"popup-recording-start{background-color:rgba(0,0,0,.2)}\n.",[1],"popup-recording-end,.",[1],"popup-recording-start{-webkit-align-items:center;align-items:center;bottom:0;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;height:100vh;-webkit-justify-content:center;justify-content:center;left:0;position:fixed;right:0;top:0;width:100vw;z-index:10000}\n.",[1],"popup-recording-end{background-color:rgba(0,0,0,.6)}\n.",[1],"icon-recording{height:",[0,360],";opacity:.7;width:",[0,360],"}\n.",[1],"icon-talk-mode{height:",[0,240],";width:",[0,240],"}\n.",[1],"pop-view{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;-webkit-justify-content:center;justify-content:center;width:100%}\n.",[1],"confetti-area{height:",[0,240],"}\n.",[1],"confetti-area,.",[1],"popup-text{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;width:80vw}\n.",[1],"popup-text{color:#fff;-webkit-flex-direction:column;flex-direction:column;height:",[0,400],"}\n.",[1],"result-text{-webkit-align-items:center;align-items:center;height:",[0,200],";-webkit-justify-content:center;justify-content:center;width:80vw}\n.",[1],"action-bar,.",[1],"result-text{display:-webkit-flex;display:flex}\n.",[1],"action-bar{-webkit-justify-content:space-around;justify-content:space-around;margin-top:",[0,60],";width:70%}\n.",[1],"action-item{-webkit-flex:1;flex:1;-webkit-flex-direction:column;flex-direction:column}\n.",[1],"action-item,.",[1],"icon-circle{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"icon-circle{background:hsla(0,0%,100%,.2);border:",[0,2]," solid hsla(0,0%,100%,.4);border-radius:50%;height:",[0,100],";-webkit-justify-content:center;justify-content:center;margin-bottom:",[0,16],";transition:all .2s;width:",[0,100],"}\n.",[1],"icon-circle.",[1],"highlight{background:rgba(255,215,0,.2);border-color:gold}\n.",[1],"action-item:active .",[1],"icon-circle{background:hsla(0,0%,100%,.4);-webkit-transform:scale(.9);transform:scale(.9)}\n.",[1],"action-label{color:#fff;font-size:",[0,26],";font-weight:300}\n.",[1],"icon-star{height:",[0,100],";width:",[0,100],"}\n.",[1],"icon-circle.",[1],"main-btn{-webkit-align-items:center;align-items:center;background:gold;border-radius:50%;box-shadow:0 4px 15px rgba(255,215,0,.4);display:-webkit-flex;display:flex;height:",[0,130],";-webkit-justify-content:center;justify-content:center;margin-bottom:",[0,15],";width:",[0,130],"}\n.",[1],"highlight-text{color:gold;font-weight:700}\n.",[1],"value-text{font-family:Times New Roman,Times,serif;font-size:",[0,300],";font-style:italic;font-weight:700}\n.",[1],"title1-text,.",[1],"title2-text{color:#2d3436;font-family:Arial,Microsoft YaHei,黑体,宋体,sans-serif;font-weight:500;letter-spacing:.5px;line-height:1.4}\n.",[1],"title2-text{font-size:",[0,56],"}\n.",[1],"tui-title{box-sizing:border-box;color:#888;font-size:",[0,30],";font-weight:500;padding:",[0,20],";width:100%}\n.",[1],"tui-text{font-size:",[0,30],";padding-left:",[0,12],"}\n.",[1],"tui-bottom-scroll{font-size:",[0,26],";height:800}\n.",[1],"tui-popup-scroll{font-size:",[0,28],";height:",[0,750],"}\n.",[1],"tui-top-scroll{font-size:",[0,28],";height:",[0,580],"}\n.",[1],"tui-banner-item{box-sizing:border-box;-webkit-flex-direction:column;flex-direction:column}\n.",[1],"tui-banner-item,.",[1],"tui-product-title{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center}\n.",[1],"tui-product-title{font-size:",[0,50],";font-weight:500;min-height:",[0,120],";width:100%}\n.",[1],"tui-pro-titbox{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;font-size:",[0,50],";font-weight:500;padding:",[0,10]," ",[0,14],"}\n.",[1],"tui-card{position:relative}\n.",[1],"tui-content{background-color:#fff;color:#555;font-size:",[0,32],";padding:",[0,5]," ",[0,20],"}\n.",[1],"tui-item-box{box-sizing:border-box;width:100%}\n.",[1],"tui-item-box,.",[1],"tui-list-cell_name{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-list-cell_name{font-size:large;-webkit-justify-content:center;justify-content:center;padding-left:",[0,20],"}\n.",[1],"tui-logo-ssmall{height:",[0,36],";width:",[0,36],"}\n.",[1],"tui-logo-small{height:",[0,60],";width:",[0,60],"}\n.",[1],"letter-box{font-size:",[0,52],";font-weight:700}\n.",[1],"letter-box.",[1],"highlight{color:#f44336;transition:background-color .3s,border-color .3s}\n.",[1],"tui-logo{-webkit-flex-shrink:0;flex-shrink:0;height:",[0,90],";width:",[0,90],"}\n.",[1],"tui-logo1{height:",[0,72],";margin-right:",[0,20],";width:",[0,72],"}\n.",[1],"tui-logo1,.",[1],"tui-right{-webkit-align-items:center;align-items:center;-webkit-justify-content:center;justify-content:center}\n.",[1],"tui-right{color:#333;font-size:",[0,26],";margin-left:auto;margin-right:",[0,34],"}\n.",[1],"word{border-radius:",[0,4],";color:#333;padding:",[0,2]," ",[0,4],"}\n.",[1],"highlighted{background-color:gold}\n.",[1],"image-container{height:100%;position:relative;width:100%}\n.",[1],"recording-overlay{background-color:rgba(0,0,0,.5);height:100%;left:0;position:absolute;top:0}\n.",[1],"cover-title,.",[1],"recording-overlay{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;width:100%}\n.",[1],"cover-title{border-radius:",[0,60],";bottom:",[0,160],";min-height:",[0,200],";padding:",[0,40]," 0;position:fixed}\n.",[1],"cover-titbox{-webkit-align-items:center;align-items:center;box-sizing:border-box;display:-webkit-flex;display:flex;font-size:",[0,96],";font-weight:500;padding:",[0,10]," ",[0,30],";position:relative}\n.",[1],"download-img{bottom:",[0,60],";height:",[0,80],";left:",[0,60],";width:",[0,100],"}\n.",[1],"download-img,.",[1],"enter-tip{-webkit-align-items:center;align-items:center;background:#f1f1f1;border-radius:",[0,40],";display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;font-size:",[0,32],";font-weight:500;-webkit-justify-content:center;justify-content:center;opacity:.7;position:fixed;z-index:99}\n.",[1],"enter-tip{bottom:",[0,66],";box-shadow:0 ",[0,4]," ",[0,8]," rgba(0,0,0,.05);height:",[0,82],";right:",[0,60],";width:",[0,180],"}\n.",[1],"talk-tip{-webkit-align-items:center;align-items:center;border-radius:",[0,40],";bottom:",[0,60],";display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;font-size:",[0,32],";font-weight:500;height:",[0,96],";-webkit-justify-content:center;justify-content:center;left:",[0,62],";position:fixed;width:",[0,120],";z-index:99}\n.",[1],"cover-setting{left:",[0,20],";position:fixed;top:",[0,20],"}\n.",[1],"cover-switch-icon{height:",[0,90],";width:",[0,90],"}\n.",[1],"download-image{height:",[0,60],";width:",[0,60],"}\n.",[1],"gif-icon{height:",[0,52],";width:",[0,62],"}\n.",[1],"download-icon{height:",[0,68],";width:",[0,68],"}\n.",[1],"tui-new-label-finish{border-radius:12%;height:",[0,76],";-webkit-justify-content:center;justify-content:center;position:absolute;right:",[0,6],";top:",[0,6],";width:",[0,76],"}\n.",[1],"tui-new-label-finish,.",[1],"tui-study-prompt{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-study-prompt{font-size:",[0,36],"}\n.",[1],"value-container{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;position:relative}\n.",[1],"confetti-gif{height:",[0,240],";left:50%;pointer-events:none;position:absolute;top:50%;-webkit-transform:translate(-50%,-50%);transform:translate(-50%,-50%);width:",[0,240],";z-index:5}\n.",[1],"word-hotspot{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;position:absolute;-webkit-transform:translate(",[0,-20],",-50%);transform:translate(",[0,-20],",-50%)}\n.",[1],"star-icon{height:",[0,60],";margin-right:",[0,6],";opacity:.8;width:",[0,60],";z-index:10}\n.",[1],"blink{-webkit-animation:star-blink 1.5s ease-in-out infinite;animation:star-blink 1.5s ease-in-out infinite}\n@-webkit-keyframes star-blink{0%,100%{opacity:1;-webkit-transform:scale(1);transform:scale(1)}\n50%{opacity:.4;-webkit-transform:scale(.8);transform:scale(.8)}\n}@keyframes star-blink{0%,100%{opacity:1;-webkit-transform:scale(1);transform:scale(1)}\n50%{opacity:.4;-webkit-transform:scale(.8);transform:scale(.8)}\n}.",[1],"word-text-wrapper{background:hsla(0,0%,100%,.5);border-radius:",[0,30],";padding:",[0,10]," ",[0,20],";position:relative;transition:all .5s ease}\n.",[1],"english-word{color:#333;font-size:",[0,32],";font-weight:700}\n.",[1],"fade-out{background:hsla(0,0%,100%,.4);opacity:.5;-webkit-transform:scale(.95);transform:scale(.95)}\n.",[1],"word-text-wrapper:active{background:#fff;-webkit-transform:scale(1.1);transform:scale(1.1)}\n.",[1],"game-container{background:#fff;border-radius:",[0,30],";-webkit-flex-direction:column;flex-direction:column;padding:",[0,40]," ",[0,20],";transition:all .3s;width:90%}\n.",[1],"answer-area,.",[1],"game-container{display:-webkit-flex;display:flex}\n.",[1],"answer-area{background:radial-gradient(circle,rgba(0,0,0,.4) 0,transparent 80%);-webkit-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;margin-bottom:",[0,60],";min-height:",[0,120],"}\n.",[1],"word-slot{margin:",[0,10],";min-width:",[0,60],"}\n.",[1],"word-slot.",[1],"is-error .",[1],"word-text{color:#ff4d4f;transition:color .2s}\n.",[1],"word-slot.",[1],"is-error .",[1],"underline{background:#ff4d4f}\n.",[1],"word-text{-webkit-animation:fadeIn .2s ease-out;animation:fadeIn .2s ease-out;color:#333;font-size:",[0,36],";padding:0 ",[0,10],"}\n@-webkit-keyframes fadeIn{from{opacity:0;-webkit-transform:translateY(",[0,10],");transform:translateY(",[0,10],")}\nto{opacity:1;-webkit-transform:translateY(0);transform:translateY(0)}\n}.",[1],"word-slot.",[1],"empty .",[1],"underline-glow{background:hsla(0,0%,100%,.2)}\n.",[1],"underline{background:#ddd;height:",[0,4],";margin-top:",[0,8],";width:100%}\n.",[1],"word-slot.",[1],"filled .",[1],"underline{background:transparent}\n.",[1],"options-pool{-webkit-align-content:flex-start;align-content:flex-start;background:#f9f9f9;border-radius:",[0,20],";display:-webkit-flex;display:flex;-webkit-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;min-height:",[0,180],";opacity:.9;padding:",[0,30],"}\n.",[1],"word-card{background:#fff;border:",[0,2]," solid #eee;border-radius:",[0,12],";box-shadow:0 ",[0,4]," 0 #ddd;font-size:",[0,32],";margin:",[0,12],";padding:",[0,15]," ",[0,30],"}\n.",[1],"is-hidden{visibility:hidden}\n.",[1],"action-btns{display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between;margin-top:",[0,60],"}\n.",[1],"btn{border-radius:",[0,45],";-webkit-flex:1;flex:1;font-size:",[0,28],";height:",[0,90],";line-height:",[0,90],";margin:0 ",[0,10],";text-align:center}\n.",[1],"btn-close{background:#eee;color:#666}\n.",[1],"btn-audio{background:#e3f2fd;color:#2196f3}\n.",[1],"btn-check{background:#4caf50;color:#fff;font-weight:700}\n@-webkit-keyframes shake{0%,100%{-webkit-transform:translateX(0);transform:translateX(0)}\n25%{-webkit-transform:translateX(",[0,-15],");transform:translateX(",[0,-15],")}\n75%{-webkit-transform:translateX(",[0,15],");transform:translateX(",[0,15],")}\n}@keyframes shake{0%,100%{-webkit-transform:translateX(0);transform:translateX(0)}\n25%{-webkit-transform:translateX(",[0,-15],");transform:translateX(",[0,-15],")}\n75%{-webkit-transform:translateX(",[0,15],");transform:translateX(",[0,15],")}\n}.",[1],"shake-err{-webkit-animation:shake 1s ease-in-out;animation:shake 1s ease-in-out}\n.",[1],"game-mask{-webkit-align-items:center;align-items:center;-webkit-backdrop-filter:blur(4px);backdrop-filter:blur(4px);background:rgba(0,0,0,.3);bottom:0;-webkit-justify-content:center;justify-content:center;left:0;position:fixed;right:0;top:0;z-index:9999}\n.",[1],"game-mask,.",[1],"immersive-game-box{display:-webkit-flex;display:flex}\n.",[1],"immersive-game-box{-webkit-flex-direction:column;flex-direction:column;height:90vh;width:95%}\n.",[1],"scroll-content{-webkit-flex:1;flex:1;overflow-y:auto;padding-bottom:",[0,30],"}\n.",[1],"flex-center-wrapper{-webkit-align-items:center;align-items:center;box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;-webkit-justify-content:center;justify-content:center;min-height:100%;padding:",[0,40]," 0}\n.",[1],"underline-glow{border-radius:",[0,3],";box-shadow:0 0 ",[0,10]," hsla(0,0%,100%,.3);height:",[0,6],"}\n.",[1],"word-card-glass{background:hsla(0,0%,100%,.9);border-radius:",[0,50],";box-shadow:0 ",[0,8]," ",[0,20]," rgba(0,0,0,.2);color:#333;font-size:",[0,34],";font-weight:500;margin:",[0,15],";padding:",[0,20]," ",[0,40],";transition:-webkit-transform active .1s;transition:transform active .1s;transition:transform active .1s,-webkit-transform active .1s}\n.",[1],"word-card-glass:active{-webkit-transform:scale(.9);transform:scale(.9)}\n.",[1],"glass-action-btns{border-radius:",[0,20],";display:-webkit-flex;display:flex;-webkit-flex-shrink:0;flex-shrink:0;-webkit-justify-content:space-around;justify-content:space-around;padding:",[0,40]," 0}\n.",[1],"glass-action-btns,.",[1],"glass-btn{-webkit-backdrop-filter:blur(5px);backdrop-filter:blur(5px)}\n.",[1],"glass-btn{border-radius:",[0,100],";font-size:",[0,28],";padding:",[0,20]," ",[0,45],"}\n.",[1],"btn-minor{background:hsla(0,0%,100%,.2);border:",[0,1]," solid hsla(0,0%,100%,.3);color:#fff}\n.",[1],"btn-main{background:#ffca28;color:#5d4037;font-weight:700}\n.",[1],"btn-confirm{background:#4caf50;color:#fff}\n.",[1],"is-error .",[1],"word-text{color:#ff5252}\n.",[1],"is-error .",[1],"underline-glow{background:#ff5252;box-shadow:0 0 ",[0,15]," #ff5252}\n.",[1],"word-slot-wrapper{-webkit-align-items:flex-end;align-items:flex-end;display:-webkit-flex;display:flex;margin:0 ",[0,5],"}\n.",[1],"word-slot{height:",[0,80],";min-width:",[0,70],"}\n.",[1],"punctuation-text{color:#fff;font-size:",[0,40],";font-weight:700;margin-bottom:",[0,10],";margin-left:",[0,-5],";text-shadow:0 ",[0,2]," ",[0,10]," rgba(0,0,0,.5)}\n.",[1],"is-error+.",[1],"punctuation-text{color:#ff5252}\n.",[1],"word-slot{height:",[0,120],";-webkit-justify-content:center;justify-content:center;margin:",[0,10]," ",[0,5],";min-width:",[0,80],"}\n.",[1],"phonetic-container{-webkit-animation:fadeInDown .3s ease-out;animation:fadeInDown .3s ease-out;bottom:",[0,-20],";left:50%;position:absolute;-webkit-transform:translateX(-50%);transform:translateX(-50%);white-space:nowrap}\n.",[1],"phonetic-text{color:#ffca28;font-family:Arial;font-size:",[0,32],";text-shadow:0 ",[0,2]," ",[0,4]," rgba(0,0,0,.5)}\n@-webkit-keyframes fadeInDown{from{opacity:0;-webkit-transform:translate(-50%,",[0,-10],");transform:translate(-50%,",[0,-10],")}\nto{opacity:1;-webkit-transform:translate(-50%,0);transform:translate(-50%,0)}\n}@keyframes fadeInDown{from{opacity:0;-webkit-transform:translate(-50%,",[0,-10],");transform:translate(-50%,",[0,-10],")}\nto{opacity:1;-webkit-transform:translate(-50%,0);transform:translate(-50%,0)}\n}.",[1],"word-slot{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;height:",[0,100],";-webkit-justify-content:flex-end;justify-content:flex-end;margin:",[0,10]," ",[0,8],";min-width:",[0,90],";position:relative}\n.",[1],"word-text{color:#fff;display:inline-block;font-size:",[0,40],";font-weight:700;line-height:",[0,50],";text-shadow:0 ",[0,2]," ",[0,10]," rgba(0,0,0,.5);transition:-webkit-transform .1s ease;transition:transform .1s ease;transition:transform .1s ease,-webkit-transform .1s ease}\n.",[1],"word-text:active{opacity:.8;-webkit-transform:scale(.9);transform:scale(.9)}\n.",[1],"underline-glow{background:hsla(0,0%,100%,.5);border-radius:",[0,2],";height:",[0,4],";margin-top:",[0,8],";width:100%}\n.",[1],"phonetic-abs-box{-webkit-animation:fadeIn .3s ease-out;animation:fadeIn .3s ease-out;left:50%;padding-top:0;pointer-events:none;position:absolute;top:100%;-webkit-transform:translateX(-50%);transform:translateX(-50%);white-space:nowrap}\n@keyframes fadeIn{from{opacity:0;-webkit-transform:translate(-50%,",[0,-5],");transform:translate(-50%,",[0,-5],")}\nto{opacity:1;-webkit-transform:translate(-50%,0);transform:translate(-50%,0)}\n}.",[1],"reward-card{background:#fff;border-radius:",[0,48],";box-shadow:0 20px 40px rgba(162,182,208,.3);-webkit-flex-direction:column;flex-direction:column;max-width:",[0,640],";overflow:hidden;padding:",[0,60]," ",[0,40],";position:relative;width:100%}\n.",[1],"badge-wrapper,.",[1],"reward-card{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"badge-wrapper{background:linear-gradient(135deg,#fff6e0,#ffe099);border-radius:50%;box-shadow:0 8px 16px rgba(255,197,66,.2);height:",[0,140],";-webkit-justify-content:center;justify-content:center;margin-bottom:",[0,20],";width:",[0,140],"}\n.",[1],"badge-emoji{font-size:",[0,80],"}\n.",[1],"card-title{color:#2c3e50;font-size:",[0,40],";font-weight:700;letter-spacing:",[0,2],";margin-bottom:",[0,30],"}\n.",[1],"divider{background:#f0f3f7;height:",[0,2],";margin:",[0,10]," 0;width:90%}\n.",[1],"metrics-area{display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;gap:",[0,36],";padding:",[0,20]," ",[0,10],";width:100%}\n.",[1],"empty-star{color:#e0e6ed}\n.",[1],"active-star{-webkit-animation:starPop .5s cubic-bezier(.175,.885,.32,1.275) forwards;animation:starPop .5s cubic-bezier(.175,.885,.32,1.275) forwards;color:#ffbe1a;display:inline-block;text-shadow:0 2px 8px rgba(255,190,26,.4);-webkit-transform:scale(0);transform:scale(0)}\n.",[1],"comment-area{background:#f7fafc;border:",[0,1]," solid #edf2f7;border-radius:",[0,24],";box-sizing:border-box;margin-top:",[0,20],";padding:",[0,28]," ",[0,32],";width:100%}\n.",[1],"comment-text{color:#4a5568;display:block;font-size:",[0,28],";line-height:1.6;text-align:center}\n@-webkit-keyframes popIn{0%{opacity:0;-webkit-transform:scale(.9);transform:scale(.9)}\n100%{opacity:1;-webkit-transform:scale(1);transform:scale(1)}\n}@keyframes popIn{0%{opacity:0;-webkit-transform:scale(.9);transform:scale(.9)}\n100%{opacity:1;-webkit-transform:scale(1);transform:scale(1)}\n}.",[1],"pop-in{-webkit-animation:popIn .4s cubic-bezier(.25,.46,.45,.94) both;animation:popIn .4s cubic-bezier(.25,.46,.45,.94) both}\n@-webkit-keyframes floating{0%{-webkit-transform:translateY(0);transform:translateY(0)}\n50%{-webkit-transform:translateY(",[0,-10],");transform:translateY(",[0,-10],")}\n100%{-webkit-transform:translateY(0);transform:translateY(0)}\n}@keyframes floating{0%{-webkit-transform:translateY(0);transform:translateY(0)}\n50%{-webkit-transform:translateY(",[0,-10],");transform:translateY(",[0,-10],")}\n100%{-webkit-transform:translateY(0);transform:translateY(0)}\n}.",[1],"bounce{-webkit-animation:floating 3s ease-in-out infinite;animation:floating 3s ease-in-out infinite}\n@-webkit-keyframes starPop{0%{-webkit-transform:scale(0);transform:scale(0)}\n80%{-webkit-transform:scale(1.2);transform:scale(1.2)}\n100%{-webkit-transform:scale(1);transform:scale(1)}\n}@keyframes starPop{0%{-webkit-transform:scale(0);transform:scale(0)}\n80%{-webkit-transform:scale(1.2);transform:scale(1.2)}\n100%{-webkit-transform:scale(1);transform:scale(1)}\n}@-webkit-keyframes fadeInUp{0%{opacity:0;-webkit-transform:translateY(",[0,20],");transform:translateY(",[0,20],")}\n100%{opacity:1;-webkit-transform:translateY(0);transform:translateY(0)}\n}.",[1],"fade-in-up{-webkit-animation:fadeInUp .6s ease-out 1.2s both;animation:fadeInUp .6s ease-out 1.2s both}\n.",[1],"action-buttons{gap:",[0,24],";-webkit-justify-content:space-between;justify-content:space-between;margin-top:",[0,40],";width:100%}\n.",[1],"action-buttons,.",[1],"btn-action{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"btn-action{border-radius:",[0,44],";box-sizing:border-box;height:",[0,88],";-webkit-justify-content:center;justify-content:center;line-height:",[0,88],";transition:all .2s ease}\n.",[1],"btn-icon{font-size:",[0,32],";margin-right:",[0,8],"}\n.",[1],"btn-close{background:#f0f4f8;color:#7f8c8d}\n.",[1],"btn-close:active{background:#e2e8f0;-webkit-transform:scale(.97);transform:scale(.97)}\n.",[1],"btn-share{-webkit-animation:buttonPulse 2s ease-in-out infinite;animation:buttonPulse 2s ease-in-out infinite;background:linear-gradient(135deg,#ff9f43,#ff6b6b);box-shadow:0 6px 16px hsla(0,100%,71%,.3);color:#fff}\n.",[1],"btn-share:active{box-shadow:0 3px 8px hsla(0,100%,71%,.2);-webkit-transform:scale(.97);transform:scale(.97)}\n@keyframes fadeInUp{0%{opacity:0;-webkit-transform:translateY(",[0,20],");transform:translateY(",[0,20],")}\n100%{opacity:1;-webkit-transform:translateY(0);transform:translateY(0)}\n}.",[1],"fade-in-up-delay{-webkit-animation:fadeInUp .6s ease-out 1.5s both;animation:fadeInUp .6s ease-out 1.5s both}\n@-webkit-keyframes buttonPulse{0%{-webkit-transform:scale(1);transform:scale(1)}\n50%{box-shadow:0 8px 20px hsla(0,100%,71%,.4);-webkit-transform:scale(1.03);transform:scale(1.03)}\n100%{-webkit-transform:scale(1);transform:scale(1)}\n}@keyframes buttonPulse{0%{-webkit-transform:scale(1);transform:scale(1)}\n50%{box-shadow:0 8px 20px hsla(0,100%,71%,.4);-webkit-transform:scale(1.03);transform:scale(1.03)}\n100%{-webkit-transform:scale(1);transform:scale(1)}\n}.",[1],"metric-row{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between;padding:",[0,10]," 0;width:100%}\n.",[1],"metric-label{color:#5c6b73;font-size:",[0,32],";font-weight:500;width:31%}\n.",[1],"metric-value-box{-webkit-flex-direction:row;flex-direction:row;gap:",[0,4],"}\n.",[1],"metric-value-box,.",[1],"stars-box{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"stars-box{gap:",[0,12],";width:44%}\n.",[1],"star-icon{display:inline-block;font-size:",[0,52],";line-height:1}\n.",[1],"raw-data-text{color:#a0aec0;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;font-size:",[0,24],";font-weight:700;line-height:1.2;padding-right:",[0,4],";width:25%}\n.",[1],"hide-canvas{height:1334px;left:",[0,-9999],";opacity:0;pointer-events:none;position:absolute;top:",[0,-9999],";width:750px}\n.",[1],"poster-mask{background:rgba(0,0,0,.65);bottom:0;-webkit-justify-content:center;justify-content:center;left:0;position:fixed;right:0;top:0;z-index:9999}\n.",[1],"poster-container,.",[1],"poster-mask{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"poster-container{-webkit-animation:popScaleUp .35s cubic-bezier(.34,1.56,.64,1) both;animation:popScaleUp .35s cubic-bezier(.34,1.56,.64,1) both;-webkit-flex-direction:column;flex-direction:column;width:80%}\n.",[1],"preview-img{border-radius:",[0,36],";box-shadow:0 12px 36px rgba(0,0,0,.4);width:100%}\n.",[1],"poster-btns{display:-webkit-flex;display:flex;gap:",[0,24],";-webkit-justify-content:space-between;justify-content:space-between;margin-top:",[0,40],";width:100%}\n.",[1],"btn-action{border:none;border-radius:",[0,46],";-webkit-flex:1;flex:1;font-size:",[0,30],";font-weight:700;height:",[0,92],";line-height:",[0,92],";padding:0;text-align:center}\n.",[1],"btn-action::after{border:none}\n.",[1],"btn-cancel{background:hsla(0,0%,100%,.2);color:#fff}\n.",[1],"btn-save{background:linear-gradient(135deg,#ff9f43,#ff6b6b);box-shadow:0 6px 16px hsla(0,100%,71%,.3);color:#fff}\n@-webkit-keyframes popScaleUp{0%{opacity:0;-webkit-transform:scale(.85);transform:scale(.85)}\n100%{opacity:1;-webkit-transform:scale(1);transform:scale(1)}\n}@keyframes popScaleUp{0%{opacity:0;-webkit-transform:scale(.85);transform:scale(.85)}\n100%{opacity:1;-webkit-transform:scale(1);transform:scale(1)}\n}.",[1],"poster-container-word{-webkit-align-items:center;align-items:center;background-color:rgba(0,0,0,.7);display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;height:100vh;-webkit-justify-content:center;justify-content:center;left:0;position:fixed;top:0;width:100vw;z-index:9999}\n.",[1],"poster-img{border-radius:",[0,16],";box-shadow:0 ",[0,12]," ",[0,32]," rgba(0,0,0,.3);height:",[0,1080],";width:",[0,600],"}\n.",[1],"save-btn{background-color:#ff9800;border-radius:",[0,40],";color:#fff;font-size:",[0,30],";margin-top:",[0,40],";width:",[0,400],";z-index:10000}\n.",[1],"hidden-canvas{height:540px;left:-9999px;position:absolute;top:-9999px;width:300px;z-index:-1}\n.",[1],"close-btn{-webkit-align-items:center;align-items:center;background-color:hsla(0,0%,100%,.25);border-radius:50%;color:#fff;display:-webkit-flex;display:flex;font-size:",[0,44],";font-weight:300;height:",[0,60],";-webkit-justify-content:center;justify-content:center;line-height:1;position:absolute;right:",[0,60],";top:",[0,80],";width:",[0,60],";z-index:10001}\n.",[1],"close-btn:active{background-color:hsla(0,0%,100%,.4)}\n.",[1],"audio-btn-1{bottom:",[0,180],";right:",[0,26],"}\n.",[1],"audio-btn-1,.",[1],"audio-btn-2{-webkit-align-items:center;align-items:center;background:#fff2bd;border-radius:50%;box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;height:",[0,80],";-webkit-justify-content:center;justify-content:center;position:fixed;width:",[0,80],"}\n.",[1],"audio-btn-2{bottom:",[0,40],";left:50%;-webkit-transform:translate(-50%,-50%);transform:translate(-50%,-50%);z-index:199}\n.",[1],"audio-icon{color:#4d4430;font-size:",[0,28],";margin-left:",[0,3],"}\n",],"Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./pages/card/card.wxss:1:69)",{path:"./pages/card/card.wxss"});
}