$gwx_XC_39=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx_XC_39 || [];
function gz$gwx_XC_39_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx_XC_39_1)return __WXML_GLOBAL__.ops_cached.$gwx_XC_39_1
__WXML_GLOBAL__.ops_cached.$gwx_XC_39_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([[7],[3,'isFinish']])
Z([3,'page'])
Z([3,'ability-section'])
Z([3,'ability-grid'])
Z([[7],[3,'quizStarList']])
Z([3,'index'])
Z([3,'showResult'])
Z([3,'ability-card ability-card-wide ability-card-weak'])
Z([[7],[3,'index']])
Z([3,'wide-left'])
Z([3,'wide-content'])
Z([3,'wide-title-row'])
Z([3,'ability-name wide-name'])
Z([a,[[6],[[7],[3,'item']],[3,'title']]])
Z([3,'stars'])
Z([3,'#ffbd26'])
Z([[6],[[7],[3,'item']],[3,'star']])
Z([1,true])
Z([3,'5'])
Z([3,'28'])
Z([[2,'=='],[[6],[[7],[3,'item']],[3,'star']],[1,5]])
Z([3,'ability-status status-mastered'])
Z([3,'已掌握'])
Z([3,'action-section'])
Z([3,'action-button primary-button'])
Z([3,'share'])
Z([3,'button-icon'])
Z([3,'👫'])
Z([3,'邀请同学一起挑战'])
Z([3,'again'])
Z([3,'retry-button'])
Z([3,'再测一遍'])
Z([3,'back'])
Z([3,'home-button'])
Z([3,'返回首页'])
Z([3,'safe-bottom'])
Z([3,'margin-top-xl margin-bottom text-center'])
Z([[7],[3,'activeSteps']])
Z([[7],[3,'items']])
Z([3,'180rpx'])
Z([3,'2'])
Z([[2,'=='],[[7],[3,'activeSteps']],[1,0]])
Z([3,'tui-banner-item'])
Z([3,'tui-card'])
Z([3,'tui-slide-image'])
Z([3,'heightFix'])
Z([[6],[[7],[3,'wordSpeakCurrent']],[3,'img']])
Z([3,'tui-new-label-voice'])
Z([a,[[2,'+'],[[7],[3,'wordCur_index']],[1,1]],[3,'/'],[[7],[3,'wordsLength']]])
Z([3,'tui-word-title'])
Z([3,'clickWordFuxiTip'])
Z([3,'tui-pro-titbox-study-name'])
Z([3,'text-bold'])
Z([a,[[6],[[7],[3,'wordSpeakCurrent']],[3,'word']]])
Z([[2,'!='],[[7],[3,'record_content']],[1,'']])
Z([3,'playRecordAudio'])
Z([3,'audio-btn'])
Z([3,'audio-icon'])
Z([3,'▶'])
Z([3,'tui-button-bottom'])
Z([3,'playWordAudio'])
Z([3,'bottom-icon-shanka'])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/voice.png'])
Z([3,'clickRecord'])
Z(z[61])
Z([[2,'?:'],[[7],[3,'isRecording']],[1,'https://qianyufang.top/public/yingyu/images/icon/speak_recording.png'],[1,'https://qianyufang.top/public/yingyu/images/icon/speak_record.png']])
Z([3,'clickSpeakNext'])
Z(z[61])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/next.png'])
Z([[2,'=='],[[7],[3,'activeSteps']],[1,1]])
Z([3,'cu-list grid col-2'])
Z([[7],[3,'cardList']])
Z(z[5])
Z([3,'clickCardQuiz'])
Z([3,'cu-card'])
Z([[6],[[7],[3,'item']],[3,'id']])
Z(z[8])
Z([3,'cu-item text-center'])
Z([[2,'?:'],[[2,'=='],[[7],[3,'index']],[[7],[3,'clickIndex']]],[[7],[3,'animation']],[1,'']])
Z([3,'aspectFill'])
Z([[6],[[7],[3,'item']],[3,'img']])
Z([a,[3,'width:100%;height:'],[[7],[3,'heightImg']],[3,'rpx;']])
Z(z[59])
Z([3,'handleClickAudio'])
Z(z[61])
Z(z[62])
Z([[2,'=='],[[7],[3,'activeSteps']],[1,2]])
Z(z[71])
Z([3,'tui-page__spacing'])
Z(z[73])
Z([a,[3,'tui-product-title1 '],z[78]])
Z(z[75])
Z(z[8])
Z([3,'title1-text text-white'])
Z([a,[[6],[[7],[3,'item']],[3,'word']]])
Z(z[59])
Z(z[83])
Z(z[61])
Z(z[62])
Z([[2,'=='],[[7],[3,'activeSteps']],[1,3]])
Z([3,'tui-pindu-title'])
Z([3,'text-ssl'])
Z([a,[3,'['],[[6],[[7],[3,'wordPindu_detail']],[3,'yinbiao']],[3,']']])
Z([3,'text-ssl margin-left margin-right-sm'])
Z([a,[[6],[[7],[3,'wordPindu_detail']],[3,'zh']]])
Z([3,'pindu_container'])
Z([a,[3,'input-area '],[[2,'?:'],[[7],[3,'isCompleted']],[1,'completed'],[1,'']]])
Z(z[5])
Z([[7],[3,'inputLetters']])
Z(z[5])
Z([a,[3,'letter-box '],[[2,'?:'],[[2,'==='],[[7],[3,'highlightIndex']],[[7],[3,'index']]],[1,'highlight'],[1,'']]])
Z([a,[3,'width:'],[[7],[3,'letterBoxSize']],[3,'rpx;height:'],[[7],[3,'letterBoxSize']],[3,'rpx;line-height:'],[[7],[3,'letterBoxSize']],z[81][3]])
Z([a,[[7],[3,'item']],[3,'\n        ']])
Z([[7],[3,'emptySlots']])
Z(z[5])
Z([3,'letter-box empty'])
Z([a,z[111][1],z[111][2],z[111][3],z[111][2],z[111][5],z[111][2],z[81][3]])
Z([3,'-\n        '])
Z([[2,'=='],[[7],[3,'isCompleted']],[1,false]])
Z([3,'letters-area margin-top'])
Z([[7],[3,'shuffledLetters']])
Z(z[5])
Z([3,'handleLetterTap'])
Z([a,[3,'letter-btn '],z[78]])
Z(z[8])
Z([[6],[[7],[3,'item']],[3,'disabled']])
Z([a,z[111][1],[[7],[3,'buttonSize']],z[81][3]])
Z([a,[[6],[[7],[3,'item']],[3,'letter']]])
Z(z[59])
Z(z[60])
Z(z[61])
Z(z[62])
Z([3,'switchPinduHardLevel'])
Z(z[61])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/switch.png'])
Z([3,'clickNextWordPindu'])
Z(z[61])
Z(z[68])
Z([[2,'=='],[[7],[3,'activeSteps']],[1,4]])
Z(z[42])
Z(z[43])
Z(z[44])
Z(z[45])
Z([[6],[[6],[[7],[3,'describeList']],[[7],[3,'sentence_index']]],[3,'img']])
Z(z[47])
Z([a,[[2,'+'],[[7],[3,'sentence_index']],[1,1]],z[48][2],[[6],[[7],[3,'describeList']],[3,'length']]])
Z(z[49])
Z([3,'tui-pro-titbox-describe'])
Z([a,[[6],[[6],[[7],[3,'describeList']],[[7],[3,'sentence_index']]],[3,'sentence']]])
Z(z[54])
Z(z[55])
Z(z[56])
Z(z[57])
Z(z[58])
Z(z[59])
Z(z[60])
Z(z[61])
Z(z[62])
Z(z[63])
Z(z[61])
Z(z[65])
Z([3,'clickDescribeNext'])
Z(z[61])
Z(z[68])
Z([[7],[3,'isRecording']])
Z(z[63])
Z([3,'popup-recording-start'])
Z([a,[3,'icon-recording  '],[[7],[3,'animation']]])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/recording.png'])
Z([[7],[3,'recordResultShow']])
Z([3,'popup-recording-end'])
Z([3,'popup-text'])
Z([3,'value-container'])
Z([3,'text-macron value-font'])
Z([a,[[7],[3,'value']]])
Z([3,'result-text'])
Z([3,'text-white text-xl'])
Z([a,[[7],[3,'record_result']]])
Z([3,'hideModal'])
Z([3,'1001'])
Z([[7],[3,'modalResult']])
Z([3,'1002'])
Z([3,'tui-popup-scroll'])
Z([3,'result-title'])
Z([a,[[7],[3,'resultTitle']]])
Z([[7],[3,'resultList']])
Z(z[5])
Z([3,'tui-rate-container'])
Z([3,'tui-title'])
Z([a,z[94][1]])
Z(z[15])
Z(z[16])
Z(z[17])
Z(z[18])
Z([3,'30'])
Z([3,'#f7f7f7'])
Z([3,'没有更多了'])
})(__WXML_GLOBAL__.ops_cached.$gwx_XC_39_1);return __WXML_GLOBAL__.ops_cached.$gwx_XC_39_1
}
__WXML_GLOBAL__.ops_set.$gwx_XC_39=z;
__WXML_GLOBAL__.ops_init.$gwx_XC_39=true;
var x=['./pages/unitQuiz/unitQuiz.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx_XC_39_1()
var xE6C=_v()
_(r,xE6C)
if(_oz(z,0,e,s,gg)){xE6C.wxVkey=1
var cH6C=_n('view')
_rz(z,cH6C,'class',1,e,s,gg)
var hI6C=_n('view')
_rz(z,hI6C,'class',2,e,s,gg)
var oJ6C=_n('view')
_rz(z,oJ6C,'class',3,e,s,gg)
var cK6C=_v()
_(oJ6C,cK6C)
var oL6C=function(aN6C,lM6C,tO6C,gg){
var bQ6C=_mz(z,'view',['bind:tap',6,'class',1,'data-id',2],[],aN6C,lM6C,gg)
var xS6C=_n('view')
_rz(z,xS6C,'class',9,aN6C,lM6C,gg)
var oT6C=_n('view')
_rz(z,oT6C,'class',10,aN6C,lM6C,gg)
var fU6C=_n('view')
_rz(z,fU6C,'class',11,aN6C,lM6C,gg)
var cV6C=_n('text')
_rz(z,cV6C,'class',12,aN6C,lM6C,gg)
var hW6C=_oz(z,13,aN6C,lM6C,gg)
_(cV6C,hW6C)
_(fU6C,cV6C)
_(oT6C,fU6C)
var oX6C=_n('view')
_rz(z,oX6C,'class',14,aN6C,lM6C,gg)
var cY6C=_mz(z,'tui-rate',['active',15,'current',1,'disabled',2,'quantity',3,'size',4],[],aN6C,lM6C,gg)
_(oX6C,cY6C)
_(oT6C,oX6C)
_(xS6C,oT6C)
_(bQ6C,xS6C)
var oR6C=_v()
_(bQ6C,oR6C)
if(_oz(z,20,aN6C,lM6C,gg)){oR6C.wxVkey=1
var oZ6C=_n('view')
_rz(z,oZ6C,'class',21,aN6C,lM6C,gg)
var l16C=_oz(z,22,aN6C,lM6C,gg)
_(oZ6C,l16C)
_(oR6C,oZ6C)
}
oR6C.wxXCkey=1
_(tO6C,bQ6C)
return tO6C
}
cK6C.wxXCkey=4
_2z(z,4,oL6C,e,s,gg,cK6C,'item','index','index')
_(hI6C,oJ6C)
_(cH6C,hI6C)
var a26C=_n('view')
_rz(z,a26C,'class',23,e,s,gg)
var t36C=_mz(z,'button',['class',24,'openType',1],[],e,s,gg)
var e46C=_n('text')
_rz(z,e46C,'class',26,e,s,gg)
var b56C=_oz(z,27,e,s,gg)
_(e46C,b56C)
_(t36C,e46C)
var o66C=_n('text')
var x76C=_oz(z,28,e,s,gg)
_(o66C,x76C)
_(t36C,o66C)
_(a26C,t36C)
var o86C=_mz(z,'view',['bindtap',29,'class',1],[],e,s,gg)
var f96C=_oz(z,31,e,s,gg)
_(o86C,f96C)
_(a26C,o86C)
var c06C=_mz(z,'view',['bindtap',32,'class',1],[],e,s,gg)
var hA7C=_oz(z,34,e,s,gg)
_(c06C,hA7C)
_(a26C,c06C)
_(cH6C,a26C)
var oB7C=_n('view')
_rz(z,oB7C,'class',35,e,s,gg)
_(cH6C,oB7C)
_(xE6C,cH6C)
}
else{xE6C.wxVkey=2
var eH7C=_n('view')
_rz(z,eH7C,'class',36,e,s,gg)
var bI7C=_mz(z,'tui-steps',['activeSteps',37,'items',1,'spacing',2,'type',3],[],e,s,gg)
_(eH7C,bI7C)
_(xE6C,eH7C)
var cC7C=_v()
_(xE6C,cC7C)
if(_oz(z,41,e,s,gg)){cC7C.wxVkey=1
var oJ7C=_n('view')
_rz(z,oJ7C,'class',42,e,s,gg)
var xK7C=_n('view')
_rz(z,xK7C,'class',43,e,s,gg)
var oL7C=_mz(z,'image',['class',44,'mode',1,'src',2],[],e,s,gg)
var fM7C=_n('view')
_rz(z,fM7C,'class',47,e,s,gg)
var cN7C=_n('view')
var hO7C=_oz(z,48,e,s,gg)
_(cN7C,hO7C)
_(fM7C,cN7C)
_(oL7C,fM7C)
_(xK7C,oL7C)
_(oJ7C,xK7C)
var oP7C=_n('view')
_rz(z,oP7C,'class',49,e,s,gg)
var oR7C=_mz(z,'view',['bindtap',50,'class',1],[],e,s,gg)
var lS7C=_n('text')
_rz(z,lS7C,'class',52,e,s,gg)
var aT7C=_oz(z,53,e,s,gg)
_(lS7C,aT7C)
_(oR7C,lS7C)
_(oP7C,oR7C)
var cQ7C=_v()
_(oP7C,cQ7C)
if(_oz(z,54,e,s,gg)){cQ7C.wxVkey=1
var tU7C=_mz(z,'view',['catch:tap',55,'class',1],[],e,s,gg)
var eV7C=_n('text')
_rz(z,eV7C,'class',57,e,s,gg)
var bW7C=_oz(z,58,e,s,gg)
_(eV7C,bW7C)
_(tU7C,eV7C)
_(cQ7C,tU7C)
}
cQ7C.wxXCkey=1
_(oJ7C,oP7C)
_(cC7C,oJ7C)
var oX7C=_n('view')
_rz(z,oX7C,'class',59,e,s,gg)
var xY7C=_mz(z,'image',['bindtap',60,'class',1,'src',2],[],e,s,gg)
_(oX7C,xY7C)
var oZ7C=_mz(z,'image',['bind:tap',63,'class',1,'src',2],[],e,s,gg)
_(oX7C,oZ7C)
var f17C=_mz(z,'image',['bindtap',66,'class',1,'src',2],[],e,s,gg)
_(oX7C,f17C)
_(cC7C,oX7C)
}
var oD7C=_v()
_(xE6C,oD7C)
if(_oz(z,69,e,s,gg)){oD7C.wxVkey=1
var c27C=_n('view')
_rz(z,c27C,'class',70,e,s,gg)
var h37C=_v()
_(c27C,h37C)
var o47C=function(o67C,c57C,l77C,gg){
var t97C=_mz(z,'view',['bindtap',73,'class',1,'data-id',2,'data-index',3],[],o67C,c57C,gg)
var e07C=_n('view')
_rz(z,e07C,'class',77,o67C,c57C,gg)
var bA8C=_mz(z,'image',['class',78,'mode',1,'src',2,'style',3],[],o67C,c57C,gg)
_(e07C,bA8C)
_(t97C,e07C)
_(l77C,t97C)
return l77C
}
h37C.wxXCkey=2
_2z(z,71,o47C,e,s,gg,h37C,'item','index','index')
_(oD7C,c27C)
var oB8C=_n('view')
_rz(z,oB8C,'class',82,e,s,gg)
var xC8C=_mz(z,'image',['bindtap',83,'class',1,'src',2],[],e,s,gg)
_(oB8C,xC8C)
_(oD7C,oB8C)
}
var lE7C=_v()
_(xE6C,lE7C)
if(_oz(z,86,e,s,gg)){lE7C.wxVkey=1
var oD8C=_v()
_(lE7C,oD8C)
var fE8C=function(hG8C,cF8C,oH8C,gg){
var oJ8C=_n('view')
_rz(z,oJ8C,'class',88,hG8C,cF8C,gg)
var lK8C=_mz(z,'view',['bindtap',89,'class',1,'data-id',2,'data-index',3],[],hG8C,cF8C,gg)
var aL8C=_n('text')
_rz(z,aL8C,'class',93,hG8C,cF8C,gg)
var tM8C=_oz(z,94,hG8C,cF8C,gg)
_(aL8C,tM8C)
_(lK8C,aL8C)
_(oJ8C,lK8C)
_(oH8C,oJ8C)
return oH8C
}
oD8C.wxXCkey=2
_2z(z,87,fE8C,e,s,gg,oD8C,'item','index','')
var eN8C=_n('view')
_rz(z,eN8C,'class',95,e,s,gg)
var bO8C=_mz(z,'image',['bindtap',96,'class',1,'src',2],[],e,s,gg)
_(eN8C,bO8C)
_(lE7C,eN8C)
}
var aF7C=_v()
_(xE6C,aF7C)
if(_oz(z,99,e,s,gg)){aF7C.wxVkey=1
var oP8C=_n('view')
_rz(z,oP8C,'class',100,e,s,gg)
var xQ8C=_n('text')
_rz(z,xQ8C,'class',101,e,s,gg)
var oR8C=_oz(z,102,e,s,gg)
_(xQ8C,oR8C)
_(oP8C,xQ8C)
var fS8C=_n('text')
_rz(z,fS8C,'class',103,e,s,gg)
var cT8C=_oz(z,104,e,s,gg)
_(fS8C,cT8C)
_(oP8C,fS8C)
_(aF7C,oP8C)
var hU8C=_n('view')
_rz(z,hU8C,'class',105,e,s,gg)
var cW8C=_n('view')
_rz(z,cW8C,'class',106,e,s,gg)
var oX8C=_v()
_(cW8C,oX8C)
var lY8C=function(t18C,aZ8C,e28C,gg){
var o48C=_mz(z,'text',['class',110,'style',1],[],t18C,aZ8C,gg)
var x58C=_oz(z,112,t18C,aZ8C,gg)
_(o48C,x58C)
_(e28C,o48C)
return e28C
}
oX8C.wxXCkey=2
_2z(z,108,lY8C,e,s,gg,oX8C,'item','index','index')
var o68C=_v()
_(cW8C,o68C)
var f78C=function(h98C,c88C,o08C,gg){
var oB9C=_mz(z,'text',['class',115,'style',1],[],h98C,c88C,gg)
var lC9C=_oz(z,117,h98C,c88C,gg)
_(oB9C,lC9C)
_(o08C,oB9C)
return o08C
}
o68C.wxXCkey=2
_2z(z,113,f78C,e,s,gg,o68C,'item','index','index')
_(hU8C,cW8C)
var oV8C=_v()
_(hU8C,oV8C)
if(_oz(z,118,e,s,gg)){oV8C.wxVkey=1
var aD9C=_n('view')
_rz(z,aD9C,'class',119,e,s,gg)
var tE9C=_v()
_(aD9C,tE9C)
var eF9C=function(oH9C,bG9C,xI9C,gg){
var fK9C=_mz(z,'button',['bindtap',122,'class',1,'data-index',2,'disabled',3,'style',4],[],oH9C,bG9C,gg)
var cL9C=_oz(z,127,oH9C,bG9C,gg)
_(fK9C,cL9C)
_(xI9C,fK9C)
return xI9C
}
tE9C.wxXCkey=2
_2z(z,120,eF9C,e,s,gg,tE9C,'item','index','index')
_(oV8C,aD9C)
}
oV8C.wxXCkey=1
_(aF7C,hU8C)
var hM9C=_n('view')
_rz(z,hM9C,'class',128,e,s,gg)
var oN9C=_mz(z,'image',['bindtap',129,'class',1,'src',2],[],e,s,gg)
_(hM9C,oN9C)
var cO9C=_mz(z,'image',['bindtap',132,'class',1,'src',2],[],e,s,gg)
_(hM9C,cO9C)
var oP9C=_mz(z,'image',['bindtap',135,'class',1,'src',2],[],e,s,gg)
_(hM9C,oP9C)
_(aF7C,hM9C)
}
var tG7C=_v()
_(xE6C,tG7C)
if(_oz(z,138,e,s,gg)){tG7C.wxVkey=1
var lQ9C=_n('view')
_rz(z,lQ9C,'class',139,e,s,gg)
var tS9C=_n('view')
_rz(z,tS9C,'class',140,e,s,gg)
var eT9C=_mz(z,'image',['class',141,'mode',1,'src',2],[],e,s,gg)
var bU9C=_n('view')
_rz(z,bU9C,'class',144,e,s,gg)
var oV9C=_n('view')
var xW9C=_oz(z,145,e,s,gg)
_(oV9C,xW9C)
_(bU9C,oV9C)
_(eT9C,bU9C)
_(tS9C,eT9C)
_(lQ9C,tS9C)
var oX9C=_n('view')
_rz(z,oX9C,'class',146,e,s,gg)
var fY9C=_n('view')
_rz(z,fY9C,'class',147,e,s,gg)
var cZ9C=_oz(z,148,e,s,gg)
_(fY9C,cZ9C)
_(oX9C,fY9C)
_(lQ9C,oX9C)
var aR9C=_v()
_(lQ9C,aR9C)
if(_oz(z,149,e,s,gg)){aR9C.wxVkey=1
var h19C=_mz(z,'view',['catch:tap',150,'class',1],[],e,s,gg)
var o29C=_n('text')
_rz(z,o29C,'class',152,e,s,gg)
var c39C=_oz(z,153,e,s,gg)
_(o29C,c39C)
_(h19C,o29C)
_(aR9C,h19C)
}
aR9C.wxXCkey=1
_(tG7C,lQ9C)
var o49C=_n('view')
_rz(z,o49C,'class',154,e,s,gg)
var l59C=_mz(z,'image',['bindtap',155,'class',1,'src',2],[],e,s,gg)
_(o49C,l59C)
var a69C=_mz(z,'image',['bindtap',158,'class',1,'src',2],[],e,s,gg)
_(o49C,a69C)
var t79C=_mz(z,'image',['bindtap',161,'class',1,'src',2],[],e,s,gg)
_(o49C,t79C)
_(tG7C,o49C)
}
cC7C.wxXCkey=1
oD7C.wxXCkey=1
lE7C.wxXCkey=1
aF7C.wxXCkey=1
tG7C.wxXCkey=1
}
var oF6C=_v()
_(r,oF6C)
if(_oz(z,164,e,s,gg)){oF6C.wxVkey=1
var e89C=_mz(z,'view',['catch:tap',165,'class',1],[],e,s,gg)
var b99C=_mz(z,'image',['class',167,'src',1],[],e,s,gg)
_(e89C,b99C)
_(oF6C,e89C)
}
var fG6C=_v()
_(r,fG6C)
if(_oz(z,169,e,s,gg)){fG6C.wxVkey=1
var o09C=_n('view')
_rz(z,o09C,'class',170,e,s,gg)
var xA0C=_n('view')
_rz(z,xA0C,'class',171,e,s,gg)
var oB0C=_n('view')
_rz(z,oB0C,'class',172,e,s,gg)
var fC0C=_n('text')
_rz(z,fC0C,'class',173,e,s,gg)
var cD0C=_oz(z,174,e,s,gg)
_(fC0C,cD0C)
_(oB0C,fC0C)
_(xA0C,oB0C)
_(o09C,xA0C)
var hE0C=_n('view')
_rz(z,hE0C,'class',175,e,s,gg)
var oF0C=_n('text')
_rz(z,oF0C,'class',176,e,s,gg)
var cG0C=_oz(z,177,e,s,gg)
_(oF0C,cG0C)
_(hE0C,oF0C)
_(o09C,hE0C)
_(fG6C,o09C)
}
var oH0C=_mz(z,'tui-bottom-popup',['bindclose',178,'maskZIndex',1,'show',2,'zIndex',3],[],e,s,gg)
var lI0C=_mz(z,'scroll-view',['scrollY',-1,'class',182],[],e,s,gg)
var aJ0C=_n('view')
_rz(z,aJ0C,'class',183,e,s,gg)
var tK0C=_oz(z,184,e,s,gg)
_(aJ0C,tK0C)
_(lI0C,aJ0C)
var eL0C=_v()
_(lI0C,eL0C)
var bM0C=function(xO0C,oN0C,oP0C,gg){
var cR0C=_n('view')
_rz(z,cR0C,'class',187,xO0C,oN0C,gg)
var hS0C=_n('view')
_rz(z,hS0C,'class',188,xO0C,oN0C,gg)
var oT0C=_oz(z,189,xO0C,oN0C,gg)
_(hS0C,oT0C)
_(cR0C,hS0C)
var cU0C=_mz(z,'tui-rate',['active',190,'current',1,'disabled',2,'quantity',3,'size',4],[],xO0C,oN0C,gg)
_(cR0C,cU0C)
_(oP0C,cR0C)
return oP0C
}
eL0C.wxXCkey=4
_2z(z,185,bM0C,e,s,gg,eL0C,'item','index','index')
_(oH0C,lI0C)
var oV0C=_mz(z,'tui-nomore',['backgroundColor',195,'text',1],[],e,s,gg)
_(oH0C,oV0C)
_(r,oH0C)
xE6C.wxXCkey=1
xE6C.wxXCkey=3
xE6C.wxXCkey=3
oF6C.wxXCkey=1
fG6C.wxXCkey=1
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx_XC_39";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx_XC_39();	if (__vd_version_info__.delayedGwx) __wxAppCode__['pages/unitQuiz/unitQuiz.wxml'] = [$gwx_XC_39, './pages/unitQuiz/unitQuiz.wxml'];else __wxAppCode__['pages/unitQuiz/unitQuiz.wxml'] = $gwx_XC_39( './pages/unitQuiz/unitQuiz.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['pages/unitQuiz/unitQuiz.wxss']=setCssToHead([[2,"./static/animation.wxss"],".",[1],"tui-banner-box-fuxi{box-sizing:border-box;height:66vh;width:100%;z-index:99}\n.",[1],"tui-banner-item{-webkit-align-items:center;align-items:center;box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;-webkit-justify-content:center;justify-content:center}\n.",[1],"tui-card{position:relative}\n.",[1],"tui-slide-image{border-radius:",[0,18],";display:block;height:60vh;transition:all .05s linear;width:100%}\n.",[1],"tui-word-title{-webkit-flex-direction:row;flex-direction:row;-webkit-justify-content:center;justify-content:center;min-height:",[0,140],";width:100%}\n.",[1],"tui-page__spacing,.",[1],"tui-word-title{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-page__spacing{-webkit-flex-direction:column;flex-direction:column;padding:",[0,60],"}\n.",[1],"tui-product-title1{background:#6f8af7;border-radius:",[0,50],";-webkit-flex-direction:column;flex-direction:column;font-size:",[0,60],";font-weight:500;height:",[0,108],";opacity:.7;width:66%;z-index:99}\n.",[1],"tui-pindu-title,.",[1],"tui-product-title1{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center}\n.",[1],"tui-pindu-title{-webkit-flex-direction:row;flex-direction:row;margin-top:",[0,20],";min-height:",[0,120],";width:100%}\n.",[1],"pindu_container{-webkit-align-items:center;align-items:center;-webkit-flex-direction:column;flex-direction:column;height:40vh;padding:",[0,20],"}\n.",[1],"input-area,.",[1],"pindu_container{display:-webkit-flex;display:flex}\n.",[1],"input-area{-webkit-flex-wrap:wrap;flex-wrap:wrap;gap:",[0,10],";-webkit-justify-content:center;justify-content:center;margin-bottom:",[0,40],";margin-top:",[0,20],"}\n.",[1],"input-area.",[1],"completed{-webkit-animation:celebrate .5s ease-in-out;animation:celebrate .5s ease-in-out}\n.",[1],"letter-box{-webkit-align-items:center;align-items:center;border:",[0,2]," solid #333;box-sizing:border-box;color:#333;display:-webkit-flex;display:flex;font-size:",[0,64],";-webkit-justify-content:center;justify-content:center;margin-top:",[0,20],";text-align:center}\n.",[1],"letter-box.",[1],"empty{color:#ccc}\n.",[1],"letter-box.",[1],"highlight{background-color:#ffeb3b;border-color:#f44336;transition:background-color .3s,border-color .3s}\n.",[1],"letters-area{-webkit-flex-wrap:wrap;flex-wrap:wrap;gap:",[0,15],";margin-bottom:",[0,40],"}\n.",[1],"letter-btn,.",[1],"letters-area{display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center}\n.",[1],"letter-btn{-webkit-align-items:center;align-items:center;background-color:#f0f0f0;border:",[0,2]," solid #333;border-radius:",[0,10],";box-sizing:border-box;font-size:",[0,64],";height:",[0,120],"}\n.",[1],"tui-pro-titbox-study-name{font-size:",[0,88],"}\n.",[1],"tui-pro-titbox-describe,.",[1],"tui-pro-titbox-study-name{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-pro-titbox-describe{font-size:",[0,72],"}\n.",[1],"tui-button-bottom{-webkit-align-items:center;align-items:center;bottom:",[0,0],";display:-webkit-flex;display:flex;height:",[0,240],";-webkit-justify-content:center;justify-content:center;position:relative;width:100%;z-index:99}\n.",[1],"bottom-icon-shanka{height:",[0,138],";margin:",[0,24],";width:",[0,138],";z-index:999}\n.",[1],"tui-new-label-voice{background:#f0f0f0;border-radius:12%;height:",[0,60],";left:",[0,6],";opacity:.7;position:absolute;top:",[0,6],";width:",[0,90],"}\n.",[1],"quiz-volume,.",[1],"tui-new-label-voice{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center}\n.",[1],"quiz-volume{height:",[0,108],";margin-top:",[0,10],";width:100%;z-index:1}\n.",[1],"volume-icon{height:",[0,108],";width:",[0,108],";z-index:999}\n.",[1],"popup-recording-start{background-color:rgba(0,0,0,.2)}\n.",[1],"popup-recording-end,.",[1],"popup-recording-start{-webkit-align-items:center;align-items:center;bottom:0;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;height:100vh;-webkit-justify-content:center;justify-content:center;left:0;position:fixed;right:0;top:0;width:100vw;z-index:10000}\n.",[1],"popup-recording-end{background-color:rgba(0,0,0,.6)}\n.",[1],"icon-recording{height:",[0,360],";opacity:.9;width:",[0,360],"}\n.",[1],"popup-text{color:#fff;-webkit-flex-direction:column;flex-direction:column;height:",[0,400],";width:80vw}\n.",[1],"popup-text,.",[1],"value-container{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center}\n.",[1],"value-container{position:relative}\n.",[1],"confetti-gif{height:",[0,240],";left:50%;pointer-events:none;position:absolute;top:50%;-webkit-transform:translate(-50%,-50%);transform:translate(-50%,-50%);width:",[0,240],";z-index:5}\n.",[1],"result-text{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;height:",[0,200],";-webkit-justify-content:center;justify-content:center;width:80vw}\n.",[1],"value-font{font-family:Times New Roman,Times,serif;font-size:",[0,300],";font-style:italic;font-weight:700}\n.",[1],"tui-rate-container{-webkit-align-items:center;align-items:center;background:#fff;box-sizing:border-box;display:-webkit-flex;display:flex;font-size:",[0,28],";-webkit-justify-content:space-between;justify-content:space-between;margin-bottom:",[0,10],";padding:",[0,10],"}\n.",[1],"tui-title{font-size:",[0,38],"}\n.",[1],"result-title{color:#555;font-size:",[0,64],";font-weight:500;padding:",[0,20],";text-align:center;width:100%}\n.",[1],"quiz-star-grid{display:-webkit-flex;display:flex;-webkit-flex-wrap:wrap;flex-wrap:wrap;margin:0 ",[0,-8],"}\n.",[1],"quiz-star-card{-webkit-align-items:center;align-items:center;background:#fff;border-radius:",[0,20],";box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;-webkit-justify-content:center;justify-content:center;min-height:",[0,240],";padding:",[0,10],";width:50%}\n.",[1],"quiz-star-title{color:#555;font-size:",[0,32],";font-weight:500;overflow:hidden;text-align:center;text-overflow:ellipsis;white-space:nowrap;width:100%}\n.",[1],"quiz-star-rate{display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;margin-top:",[0,12],";-webkit-transform:scale(.92);transform:scale(.92)}\n.",[1],"tui-popup-scroll{height:55vh;padding:",[0,10],"}\n.",[1],"audio-btn{-webkit-align-items:center;align-items:center;background:#fff2bd;border-radius:50%;box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-flex:0 0 ",[0,60],";flex:0 0 ",[0,60],";-webkit-flex-direction:row;flex-direction:row;height:",[0,60],";-webkit-justify-content:center;justify-content:center;margin-left:",[0,16],";width:",[0,60],"}\n.",[1],"audio-icon{color:#4d4430;font-size:",[0,28],";margin-left:",[0,3],"}\n.",[1],"audio-btn:active{-webkit-transform:scale(.94);transform:scale(.94)}\nbody{background:#fff9f2;color:#333;min-height:100%}\nwx-button::after{border:none}\n.",[1],"page{min-height:100vh;padding-bottom:",[0,40],"}\n.",[1],"nav-bar,.",[1],"page{box-sizing:border-box}\n.",[1],"nav-bar{-webkit-align-items:center;align-items:center;background:#fff9f2;display:-webkit-flex;display:flex;height:",[0,96],";-webkit-justify-content:space-between;justify-content:space-between;padding:0 ",[0,28],"}\n.",[1],"nav-back,.",[1],"nav-placeholder{height:",[0,72],";width:",[0,72],"}\n.",[1],"nav-back{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center}\n.",[1],"nav-arrow{color:#444;font-size:",[0,64],";font-weight:300;line-height:1;-webkit-transform:translateY(",[0,-4],");transform:translateY(",[0,-4],")}\n.",[1],"nav-title{color:#333;font-size:",[0,34],";font-weight:600}\n.",[1],"result-header{background:linear-gradient(145deg,#fff3d7,#ffe6b7);border:",[0,2]," solid rgba(255,184,70,.2);border-radius:",[0,36],";box-shadow:0 ",[0,14]," ",[0,34]," rgba(231,151,42,.12);margin:0 ",[0,28],";overflow:hidden;padding:",[0,30]," ",[0,30]," ",[0,40],";position:relative;text-align:center}\n.",[1],"result-decoration{background:hsla(0,0%,100%,.35);border-radius:50%;height:",[0,170],";position:absolute;width:",[0,170],"}\n.",[1],"decoration-left{left:",[0,-65],";top:",[0,-85],"}\n.",[1],"decoration-right{bottom:",[0,-100],";right:",[0,-70],"}\n.",[1],"trophy-wrap{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;height:",[0,126],";-webkit-justify-content:center;justify-content:center;margin:0 auto ",[0,12],";position:relative;width:",[0,126],"}\n.",[1],"trophy-light{background:hsla(0,0%,100%,.65);border-radius:50%;box-shadow:0 0 0 ",[0,14]," hsla(0,0%,100%,.24);height:",[0,110],";position:absolute;width:",[0,110],"}\n.",[1],"trophy{font-size:",[0,76],";line-height:1;position:relative;z-index:2}\n.",[1],"result-title{color:#7a4a11;font-size:",[0,32],";font-weight:600}\n.",[1],"score-row{-webkit-align-items:baseline;align-items:baseline;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;margin-top:",[0,10],"}\n.",[1],"score-current{color:#ff8d3b;font-size:",[0,72],";font-weight:700;line-height:1.15}\n.",[1],"score-total{color:#8b673d;font-size:",[0,28],";font-weight:500}\n.",[1],"result-summary{color:#826745;font-size:",[0,26],";margin-top:",[0,16],"}\n.",[1],"summary-number{color:#36a874;font-size:",[0,30],";font-weight:700;margin:0 ",[0,6],"}\n.",[1],"warning-number{color:#ff794f}\n.",[1],"ability-section{margin:",[0,28]," ",[0,28]," 0}\n.",[1],"section-header{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between;padding:0 ",[0,4]," ",[0,20],"}\n.",[1],"section-title{color:#333;font-size:",[0,34],";font-weight:700}\n.",[1],"section-subtitle{color:#999;font-size:",[0,24],";margin-top:",[0,6],"}\n.",[1],"star-total{-webkit-align-items:center;align-items:center;background:#fff0cc;border-radius:",[0,27],";color:#ba7910;display:-webkit-flex;display:flex;font-size:",[0,26],";font-weight:600;height:",[0,54],";padding:0 ",[0,20],"}\n.",[1],"star-total-icon{color:#ffb51b;margin-right:",[0,8],"}\n.",[1],"ability-grid{display:-webkit-flex;display:flex;-webkit-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:space-between;justify-content:space-between}\n.",[1],"ability-card{background:#fff;border:",[0,2]," solid transparent;border-radius:",[0,26],";box-shadow:0 ",[0,10]," ",[0,28]," rgba(92,72,50,.07);box-sizing:border-box;margin-bottom:",[0,20],";min-height:",[0,240],";padding:",[0,22],";width:calc(50% - ",[0,10],")}\n.",[1],"ability-card-mastered{border-color:#e8f6ee}\n.",[1],"ability-card-weak{background:linear-gradient(150deg,#fff,#fffaf7);border-color:#ffe3d7}\n.",[1],"ability-top{-webkit-justify-content:space-between;justify-content:space-between}\n.",[1],"ability-icon,.",[1],"ability-top{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"ability-icon{border-radius:",[0,20],";font-size:",[0,34],";height:",[0,64],";-webkit-justify-content:center;justify-content:center;width:",[0,64],"}\n.",[1],"icon-repeat{background:#ffebe3}\n.",[1],"icon-listen{background:#fff1c9}\n.",[1],"icon-recognize{background:#e2f4ff}\n.",[1],"icon-spell{background:#e8f6ed}\n.",[1],"icon-expression{background:#eee9ff}\n.",[1],"ability-status{border-radius:",[0,18],";font-size:",[0,20],";font-weight:500;padding:",[0,7]," ",[0,12],"}\n.",[1],"status-mastered{background:#e9f8f0;color:#349467}\n.",[1],"status-practice{background:#fff0e9;color:#e86c48}\n.",[1],"ability-name{color:#444;font-size:",[0,30],";font-weight:600;margin-top:",[0,18],"}\n.",[1],"stars{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;margin-top:",[0,12],";white-space:nowrap}\n.",[1],"star{font-size:",[0,35],";line-height:1;margin-right:",[0,4],"}\n.",[1],"star:last-child{margin-right:0}\n.",[1],"star-active{color:#ffb51b;text-shadow:0 ",[0,3]," ",[0,6]," rgba(255,181,27,.2)}\n.",[1],"star-empty{color:#d8d8d8}\n.",[1],"ability-bottom{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between;margin-top:",[0,18],"}\n.",[1],"ability-score{color:#aaa;font-size:",[0,22],"}\n.",[1],"practice-link{color:#ff754f}\n.",[1],"mastered-text,.",[1],"practice-link{font-size:",[0,23],";font-weight:600}\n.",[1],"mastered-text{color:#47a878}\n.",[1],"ability-card-wide{-webkit-justify-content:space-between;justify-content:space-between;min-height:",[0,170],";padding:",[0,26]," ",[0,24],";width:100%}\n.",[1],"ability-card-wide,.",[1],"wide-left{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"wide-content,.",[1],"wide-left{-webkit-flex:1;flex:1;min-width:0}\n.",[1],"wide-content{margin-left:",[0,22],"}\n.",[1],"wide-title-row{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"wide-name{margin-right:",[0,16],";margin-top:0}\n.",[1],"wide-description{color:#999;font-size:",[0,22],";margin-top:",[0,10],";overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n.",[1],"wide-action{-webkit-align-items:center;align-items:center;background:#ff8f65;border-radius:",[0,32],";box-shadow:0 ",[0,8]," ",[0,18]," rgba(255,126,82,.22);color:#fff;display:-webkit-flex;display:flex;font-size:",[0,24],";font-weight:600;height:",[0,64],";margin-left:",[0,18],";padding:0 ",[0,22],"}\n.",[1],"wide-arrow{font-size:",[0,34],";font-weight:300;margin-left:",[0,8],"}\n.",[1],"encourage-card{background:#fff3d6;border-radius:",[0,24],";margin:",[0,8]," ",[0,28]," 0;padding:",[0,24]," ",[0,26],"}\n.",[1],"encourage-card,.",[1],"encourage-icon{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"encourage-icon{background:hsla(0,0%,100%,.75);border-radius:",[0,22],";-webkit-flex-shrink:0;flex-shrink:0;font-size:",[0,34],";height:",[0,66],";-webkit-justify-content:center;justify-content:center;width:",[0,66],"}\n.",[1],"encourage-content{margin-left:",[0,20],"}\n.",[1],"encourage-title{color:#7d591f;font-size:",[0,27],";font-weight:600}\n.",[1],"encourage-text{color:#9b7948;font-size:",[0,23],";line-height:1.5;margin-top:",[0,6],"}\n.",[1],"action-section{margin:",[0,34]," ",[0,48]," 0;text-align:center}\n.",[1],"action-button{-webkit-align-items:center;align-items:center;border-radius:",[0,46],";display:-webkit-flex;display:flex;font-size:",[0,30],";font-weight:600;height:",[0,92],";-webkit-justify-content:center;justify-content:center;line-height:",[0,92],";margin:0 0 ",[0,22],";padding:0;width:100%}\n.",[1],"primary-button{background:linear-gradient(135deg,#ff9e68,#ff7e54);box-shadow:0 ",[0,14]," ",[0,28]," rgba(255,126,84,.24);color:#fff}\n.",[1],"secondary-button{background:#fff;border:",[0,2]," solid #ffb598;box-sizing:border-box;color:#f17a51}\n.",[1],"button-icon{font-size:",[0,31],";margin-right:",[0,12],"}\n.",[1],"retry-button{color:#747474;font-size:",[0,27],";font-weight:500;height:",[0,74],"}\n.",[1],"home-button,.",[1],"retry-button{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center}\n.",[1],"home-button{color:#aaa;font-size:",[0,25],";height:",[0,68],"}\n.",[1],"safe-bottom{height:env(safe-area-inset-bottom)}\n",],"Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./pages/unitQuiz/unitQuiz.wxss:1:69)",{path:"./pages/unitQuiz/unitQuiz.wxss"});
}