$gwx_XC_42=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx_XC_42 || [];
function gz$gwx_XC_42_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx_XC_42_1)return __WXML_GLOBAL__.ops_cached.$gwx_XC_42_1
__WXML_GLOBAL__.ops_cached.$gwx_XC_42_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'nav text-center'])
Z([3,'tabSelect'])
Z([a,[3,'cu-item '],[[2,'?:'],[[2,'=='],[1,0],[[7],[3,'currentTab']]],[1,'text-blue cur'],[1,'']]])
Z([3,'0'])
Z([3,'测验'])
Z(z[1])
Z([a,z[2][1],[[2,'?:'],[[2,'=='],[1,5],[[7],[3,'currentTab']]],[1,'text-blue cur'],[1,'']]])
Z([3,'5'])
Z([3,'复习'])
Z(z[1])
Z([a,z[2][1],[[2,'?:'],[[2,'=='],[1,3],[[7],[3,'currentTab']]],[1,'text-blue cur'],[1,'']]])
Z([3,'3'])
Z([3,'收藏'])
Z(z[1])
Z([a,z[2][1],[[2,'?:'],[[2,'=='],[1,1],[[7],[3,'currentTab']]],[1,'text-blue cur'],[1,'']]])
Z([3,'1'])
Z([3,'拼读'])
Z(z[1])
Z([a,z[2][1],[[2,'?:'],[[2,'=='],[1,2],[[7],[3,'currentTab']]],[1,'text-blue cur'],[1,'']]])
Z([3,'2'])
Z([3,'闪卡'])
Z(z[1])
Z([a,z[2][1],[[2,'?:'],[[2,'=='],[1,4],[[7],[3,'currentTab']]],[1,'text-blue cur'],[1,'']]])
Z([3,'4'])
Z([3,'统计'])
Z([[2,'=='],[[7],[3,'currentTab']],[1,0]])
Z([[7],[3,'isEmpty']])
Z([3,'padding flex flex-direction text-center margin-top-xl'])
Z([3,'text-xl text-grey margin-top'])
Z([3,'当前暂无可测验的单词'])
Z([3,'text-grey margin-top-xl'])
Z([3,'首次点击学习的单词，会被自动加入到测验列表里'])
Z(z[30])
Z([3,'采用艾宾浩斯模式，按照1 2 4 7 15天的规律来重复'])
Z([3,'thorui-flex__center margin-top-xl'])
Z([[7],[3,'wordImgs2']])
Z([3,'tui-item__row tui-color__white'])
Z([3,'padding-xss'])
Z([3,'widthFix'])
Z([[7],[3,'item']])
Z([[2,'=='],[[7],[3,'isFinish']],[1,false]])
Z([3,'cu-progress round sm'])
Z([a,[3,'background-color:#ff9b6a;width:'],[[7],[3,'progress']],[3,';']])
Z([[2,'=='],[[7],[3,'isTextMode']],[1,false]])
Z([[2,'=='],[[7],[3,'isPad']],[1,false]])
Z([3,'cu-list grid col-2'])
Z([[7],[3,'quizList']])
Z([3,'index'])
Z([3,'delete'])
Z([3,'clickWordTest'])
Z([3,'cu-card'])
Z([[7],[3,'index']])
Z([3,'cu-item'])
Z([[2,'?:'],[[2,'=='],[[7],[3,'index']],[[7],[3,'clickIndex']]],[[7],[3,'animation']],[1,'']])
Z([[6],[[7],[3,'item']],[3,'img']])
Z([a,[3,'width:100%;height:'],[[7],[3,'heightImg']],[3,'rpx;']])
Z(z[46])
Z(z[47])
Z([1,2])
Z(z[48])
Z(z[49])
Z([3,'tui-grid-img'])
Z(z[51])
Z(z[53])
Z([3,'true'])
Z([3,'aspectFit'])
Z(z[54])
Z([3,'quiz-volume'])
Z([3,'deleteQuizWord'])
Z([3,'tui-logo margin-right-sm'])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/delete.png'])
Z([3,'handleClickAudio'])
Z([3,'tui-product-title'])
Z([3,'title1-text text-white'])
Z([a,[[7],[3,'cur_title']]])
Z([3,'#ff9b6a'])
Z([3,'news-fill'])
Z([3,'64'])
Z([3,'rpx'])
Z([3,'showTextMode'])
Z([3,'tui-logo margin-left-sm'])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/switch.png'])
Z(z[46])
Z([3,'tui-page__spacing'])
Z(z[48])
Z(z[49])
Z([a,[3,'tui-product-title1 '],z[53]])
Z(z[51])
Z(z[73])
Z([a,[[6],[[7],[3,'item']],[3,'word']]])
Z([[7],[3,'isTipShow']])
Z([3,'tui-word-title'])
Z([3,'tui-pro-titbox'])
Z([3,'text-xxl text-gray margin-left'])
Z([a,[3,'['],[[7],[3,'wordtip_yinbiao']],[3,']']])
Z([3,'text-xxl text-gray margin-left margin-right-sm'])
Z([a,[[7],[3,'wordtip_zh']]])
Z([3,'tui-button-bottom'])
Z([a,[3,'position:'],[[2,'?:'],[[7],[3,'isPad']],[1,'relative'],[1,'fixed']]])
Z(z[79])
Z([3,'bottom-icon-shanka'])
Z(z[81])
Z(z[71])
Z(z[100])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/voice.png'])
Z([3,'clickQuizPromot'])
Z(z[100])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/tip.png'])
Z([3,'margin-top text-center'])
Z([3,'padding text-xl text-bold title-display'])
Z([[2,'>='],[[7],[3,'passRate']],[1,90]])
Z([3,'icon-yanhua'])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/yanhua.png'])
Z([[2,'?:'],[[2,'>='],[[7],[3,'passRate']],[1,90]],[1,'text-red'],[1,'text-macron']])
Z([a,[3,'本次测验结果：通过率 '],[[7],[3,'passRate']],[3,'%']])
Z(z[110])
Z(z[111])
Z(z[112])
Z(z[110])
Z([3,'confetti-gif'])
Z(z[65])
Z([3,'https://qianyufang.top/public/yingyu/images/gif/Trophy.gif'])
Z([[7],[3,'dataList']])
Z(z[47])
Z([3,'showStarlist'])
Z([[6],[[7],[3,'item']],[3,'current']])
Z(z[51])
Z([3,'title'])
Z([3,'tui-rate-container'])
Z([[6],[[7],[3,'item']],[3,'star']])
Z(z[64])
Z(z[11])
Z([3,'36'])
Z([3,'tui-title'])
Z([a,[[6],[[7],[3,'item']],[3,'num']],[3,' 个']])
Z([3,'content'])
Z([3,'cindex'])
Z([3,'citem'])
Z([[6],[[7],[3,'item']],[3,'list']])
Z(z[47])
Z([3,'tui-content'])
Z([3,'showWordsList'])
Z(z[51])
Z([[7],[3,'citem']])
Z([a,[[7],[3,'citem']]])
Z([3,'margin-top-xl'])
Z([3,'again'])
Z([3,'bg-macron'])
Z([3,'width:50%;'])
Z([3,'再测一次'])
Z([[2,'=='],[[7],[3,'currentTab']],[1,5]])
Z([[2,'=='],[[7],[3,'wordFuxi_empty']],[1,true]])
Z([3,'padding flex flex-direction text-center margin-top'])
Z(z[28])
Z([3,'当前暂无可复习的单词'])
Z(z[30])
Z([3,'此处单词列表来自于已学习的课程内容'])
Z(z[30])
Z([3,'采用艾宾浩斯模式，点击检测可标记是否掌握'])
Z(z[30])
Z(z[34])
Z([[7],[3,'wordImgs1']])
Z(z[47])
Z(z[36])
Z(z[37])
Z(z[38])
Z(z[39])
Z([3,'tui-banner-box-fuxi'])
Z([3,'changeWordFuxi'])
Z([1,true])
Z([[7],[3,'wordFuxi_index']])
Z([3,'150'])
Z([1,false])
Z([3,'68rpx'])
Z(z[173])
Z([3,'height:80vh'])
Z([[7],[3,'wordFuxiList']])
Z(z[47])
Z([3,'tui-banner-item'])
Z([3,'tui-card'])
Z([3,'clickWordFuxiTip'])
Z([3,'tui-slide-image'])
Z([3,'heightFix'])
Z(z[54])
Z([3,'tui-new-label-voice'])
Z([3,'voice-icon'])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/voice_on.png'])
Z([3,'downloadWordPoster'])
Z([3,'tui-new-label-download'])
Z([3,'download-icon'])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/download_square.png'])
Z(z[91])
Z([[2,'=='],[[7],[3,'isWordFuxiTest']],[1,false]])
Z(z[180])
Z([3,'tui-pro-titbox-study-name'])
Z([3,'text-bold'])
Z([a,z[89][1]])
Z([[2,'&&'],[[2,'=='],[[7],[3,'isWordFuxiTest']],[1,true]],[[2,'=='],[[7],[3,'wordFuxi_index']],[[7],[3,'index']]]])
Z([[7],[3,'wordFuxiTest']])
Z(z[47])
Z([3,'clickWordFuxiTest'])
Z([3,'tui-word-button'])
Z(z[51])
Z(z[195])
Z([a,[[7],[3,'item']]])
Z([3,'tui-new-label-like'])
Z([[2,'&&'],[[7],[3,'showLike']],[[2,'=='],[[7],[3,'like_id']],[[7],[3,'index']]]])
Z(z[119])
Z(z[65])
Z([3,'https://qianyufang.top/public/yingyu/images/gif/like.gif'])
Z(z[97])
Z([a,z[98][1],z[98][2]])
Z([3,'collectFuxiWord'])
Z(z[100])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/add.png'])
Z([3,'clickFuxiAuto'])
Z(z[100])
Z([[2,'?:'],[[7],[3,'isWordFuxiAuto']],[1,'https://qianyufang.top/public/yingyu/images/icon/pause.png'],[1,'https://qianyufang.top/public/yingyu/images/icon/play.png']])
Z([3,'showWordFuxiTest'])
Z(z[100])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/check.png'])
Z([3,'clickWordExtend'])
Z(z[100])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/more.png'])
Z([[2,'=='],[[7],[3,'currentTab']],[1,3]])
Z([[2,'=='],[[7],[3,'myWords_empty']],[1,true]])
Z(z[27])
Z(z[28])
Z([3,'当前暂无收藏的单词'])
Z(z[30])
Z([3,'在课程中点击文中单词，在弹出卡片中点击\x22+\x22进行收藏'])
Z(z[30])
Z([3,'收藏的单词会在此进行列表展示，点击可查看单词详情'])
Z(z[34])
Z([[7],[3,'wordImgs']])
Z(z[36])
Z(z[37])
Z(z[38])
Z(z[39])
Z([[2,'=='],[[7],[3,'list_mode']],[1,true]])
Z([3,'height:100%;'])
Z(z[172])
Z([3,'10rpx 10rpx'])
Z([3,'flex__between'])
Z([3,'word-mode-title'])
Z([[7],[3,'word_collect_ibhs']])
Z([a,[3,'艾宾浩斯模式，符合展示的收藏单词'],[[6],[[7],[3,'myWords']],[3,'length']],[3,'个']])
Z([a,[3,'列表模式，符合展示的收藏单词'],z[246][2],z[246][3]])
Z([3,'changeCollectSetting'])
Z(z[245])
Z([3,'blue'])
Z([[7],[3,'myWords']])
Z(z[47])
Z(z[3])
Z([3,'showFavorDetail'])
Z([3,'tui-item-box'])
Z(z[51])
Z([3,'tui-msg-box'])
Z([3,'tui-msg-pic'])
Z([3,'aspectFill'])
Z(z[54])
Z([3,'tui-msg-item'])
Z([3,'tui-msg-name'])
Z([a,[[6],[[7],[3,'item']],[3,'name']]])
Z([3,'tui-msg-content'])
Z([a,z[94][1],[[6],[[7],[3,'item']],[3,'yinbiao']],[3,'] '],[[6],[[7],[3,'item']],[3,'zh']]])
Z([3,'tui-msg-right'])
Z([3,'clickListModeAudio'])
Z(z[75])
Z(z[51])
Z(z[76])
Z([3,'58'])
Z(z[78])
Z([[2,'&&'],[[2,'=='],[[6],[[7],[3,'myWords']],[3,'length']],[1,0]],[[7],[3,'word_collect_ibhs']]])
Z([3,'text-center'])
Z(z[30])
Z([3,'艾宾浩斯模式下按单词收藏时间进行展示'])
Z(z[30])
Z([3,'一个单词收藏的第1、2、4、7、15、30天'])
Z([3,'#f7f7f7'])
Z([[2,'?:'],[[2,'>'],[[6],[[7],[3,'myWords']],[3,'length']],[1,100]],[1,'展示上限为100个'],[1,'没有更多了']])
Z([3,'clickWordAudio'])
Z(z[91])
Z(z[92])
Z(z[195])
Z([a,[[6],[[7],[3,'wordDetail']],[3,'name']]])
Z([[6],[[7],[3,'wordDetail']],[3,'yinbiao']])
Z(z[93])
Z([a,z[94][1],[[6],[[7],[3,'wordDetail']],[3,'yinbiao']],z[94][3]])
Z(z[95])
Z([a,[[6],[[7],[3,'wordDetail']],[3,'zh']]])
Z(z[75])
Z(z[76])
Z(z[271])
Z(z[78])
Z([3,'tui-banner-box'])
Z([3,'changeWordImage'])
Z(z[169])
Z([[7],[3,'image_index']])
Z(z[171])
Z([3,'#fff'])
Z(z[169])
Z(z[173])
Z(z[173])
Z([3,'height:60vh'])
Z([[7],[3,'wordExtend']])
Z(z[47])
Z(z[178])
Z(z[179])
Z([3,'playWordAudio'])
Z(z[181])
Z(z[182])
Z(z[54])
Z(z[187])
Z(z[188])
Z(z[189])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/download.png'])
Z([3,'tui-card-title'])
Z([a,[[6],[[7],[3,'item']],[3,'title']]])
Z(z[97])
Z([a,z[98][1],z[98][2]])
Z([3,'showListModeFavor'])
Z(z[100])
Z(z[81])
Z([3,'deleteCollectWord'])
Z(z[100])
Z(z[70])
Z([3,'clickListenWord'])
Z(z[100])
Z([[2,'?:'],[[7],[3,'isWordListen']],[1,'https://qianyufang.top/public/yingyu/images/icon/pause.png'],[1,'https://qianyufang.top/public/yingyu/images/icon/play.png']])
Z([3,'clickNextWord'])
Z(z[100])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/next.png'])
Z([[2,'=='],[[7],[3,'currentTab']],[1,1]])
Z([[2,'=='],[[7],[3,'wordPindu_empty']],[1,true]])
Z(z[27])
Z(z[28])
Z([3,'当前暂无可拼读的单词'])
Z([3,'playWordPinduAudio'])
Z([3,'tui-pindu-title'])
Z([3,'text-sl'])
Z([a,z[94][1],[[6],[[7],[3,'wordPindu_detail']],[3,'yinbiao']],z[94][3]])
Z([3,'text-sl margin-left margin-right-sm'])
Z([a,[[6],[[7],[3,'wordPindu_detail']],[3,'zh']]])
Z(z[75])
Z(z[76])
Z([3,'68'])
Z(z[78])
Z([3,'pindu_container'])
Z([3,'clickWordSpell'])
Z([a,[3,'input-area '],[[2,'?:'],[[7],[3,'isCompleted']],[1,'completed'],[1,'']]])
Z(z[47])
Z([[7],[3,'inputLetters']])
Z(z[47])
Z([a,[3,'letter-box '],[[2,'?:'],[[2,'==='],[[7],[3,'highlightIndex']],[[7],[3,'index']]],[1,'highlight'],[1,'']]])
Z([a,[3,'width:'],[[7],[3,'letterBoxSize']],[3,'rpx;height:'],[[7],[3,'letterBoxSize']],[3,'rpx;line-height:'],[[7],[3,'letterBoxSize']],z[55][3]])
Z([a,z[204][1],[3,'\n        ']])
Z([[7],[3,'emptySlots']])
Z(z[47])
Z([3,'letter-box empty'])
Z([a,z[355][1],z[355][2],z[355][3],z[355][2],z[355][5],z[355][2],z[55][3]])
Z([3,'-\n        '])
Z([[2,'=='],[[7],[3,'isCompleted']],[1,false]])
Z([3,'letters-area margin-top'])
Z([[7],[3,'shuffledLetters']])
Z(z[47])
Z([3,'handleLetterTap'])
Z([a,[3,'letter-btn '],z[53]])
Z(z[51])
Z([[6],[[7],[3,'item']],[3,'disabled']])
Z([a,z[355][1],[[7],[3,'buttonSize']],z[55][3]])
Z([a,[[6],[[7],[3,'item']],[3,'letter']]])
Z([[7],[3,'isCompleted']])
Z([3,'tui-card-img'])
Z([3,'tui-pindu-image'])
Z(z[182])
Z([[2,'?:'],[[6],[[7],[3,'wordPindu_detail']],[3,'gif']],[[6],[[7],[3,'wordPindu_detail']],[3,'gif']],[[6],[[7],[3,'wordPindu_detail']],[3,'img']]])
Z(z[97])
Z([a,z[98][1],z[98][2]])
Z([3,'deletePinduWord'])
Z(z[100])
Z(z[70])
Z([3,'collectPinduWord'])
Z(z[100])
Z(z[214])
Z([3,'switchPinduHardLevel'])
Z(z[100])
Z(z[81])
Z([3,'clickNextWordPindu'])
Z(z[100])
Z(z[332])
Z([[2,'=='],[[7],[3,'currentTab']],[1,2]])
Z([[2,'=='],[[7],[3,'wordShanka_empty']],[1,true]])
Z(z[27])
Z(z[28])
Z([3,'当前暂无可学习的单词'])
Z(z[30])
Z([3,'在课程中点击文中单词，即代表已学习'])
Z(z[30])
Z([3,'已学习的单词，会按时间选取前100个进行展示'])
Z(z[34])
Z(z[35])
Z(z[47])
Z(z[36])
Z(z[37])
Z(z[38])
Z(z[39])
Z([3,'tui-banner-box margin-top'])
Z([3,'changeWordShanka'])
Z(z[169])
Z([[7],[3,'wordShanka_index']])
Z(z[171])
Z(z[172])
Z(z[173])
Z(z[173])
Z(z[304])
Z([[7],[3,'wordShankaList']])
Z(z[47])
Z(z[178])
Z(z[179])
Z([3,'clickWordName'])
Z(z[181])
Z(z[182])
Z(z[54])
Z(z[184])
Z(z[185])
Z(z[186])
Z([3,'tui-word-title margin-top'])
Z([a,[3,'tui-pro-titbox-study-name '],z[350][2]])
Z([3,'text-bold margin-top'])
Z([a,[[7],[3,'wordShanka_name']]])
Z([[2,'!='],[[6],[[7],[3,'wordShanka_prompt']],[3,'length']],[1,0]])
Z([3,'clickWordPrompt'])
Z([3,'tui-pro-titbox-study-prompt padding-sm'])
Z([3,'tui-logo-small'])
Z(z[186])
Z([3,'margin-left-sm'])
Z([a,[[7],[3,'wordShanka_prompt']]])
Z(z[97])
Z([a,z[98][1],z[98][2]])
Z([3,'deleteShankaWord'])
Z(z[100])
Z(z[70])
Z([3,'clickWordCollect'])
Z(z[100])
Z(z[214])
Z(z[187])
Z(z[100])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/download_round.png'])
Z([3,'clickNextStudy'])
Z(z[100])
Z(z[332])
Z([[2,'=='],[[7],[3,'currentTab']],[1,4]])
Z([3,'tui-page__bd'])
Z([3,'tui-charts-box'])
Z([3,'getWordsPie'])
Z(z[15])
Z([3,'20'])
Z([3,'round'])
Z([[6],[[7],[3,'options']],[3,'dataset']])
Z([3,'tui_column'])
Z([[6],[[7],[3,'options']],[3,'Ymax']])
Z([[6],[[7],[3,'options']],[3,'splitNumber']])
Z([[6],[[7],[3,'options']],[3,'xAxis']])
Z([[6],[[7],[3,'options']],[3,'xAxisVal']])
Z([[2,'!='],[[6],[[7],[3,'pieData']],[3,'length']],[1,0]])
Z(z[453])
Z([3,'tui-charts-pie'])
Z([3,'tui_pie_1'])
Z(z[58])
Z([3,'header'])
Z(z[127])
Z([3,'Tips'])
Z([3,'sub-title'])
Z([3,'1、系统根据艾宾浩斯记忆曲线来展示单词测验列表'])
Z(z[473])
Z([3,'2、如果一个新单词测验通过后，会在1天后出现；再次通过后，会在2天后出现；这个时间规律是1 2 4 7 15 30天'])
Z(z[473])
Z([3,'3、通过1次为一星，通过2次为二星。。。最高为六星'])
Z(z[473])
Z([3,'4、点击柱状图，可以查看该星级下面的单词级别统计'])
Z(z[473])
Z([3,'5、长按单词，可从测验列表中移除'])
Z([3,'hideModal'])
Z([3,'1001'])
Z([[7],[3,'modalWord']])
Z([3,'1002'])
Z([3,'tui-popup-scroll'])
Z([3,'clickWordShowAudio'])
Z(z[91])
Z(z[92])
Z(z[195])
Z([a,[[6],[[7],[3,'wordShow']],[3,'name']]])
Z([[6],[[7],[3,'wordShow']],[3,'yinbiao']])
Z(z[93])
Z([a,z[94][1],[[6],[[7],[3,'wordShow']],[3,'yinbiao']],z[94][3]])
Z(z[93])
Z([a,[[6],[[7],[3,'wordShow']],[3,'zh']]])
Z([3,'switchWord'])
Z(z[169])
Z([[7],[3,'word_index']])
Z(z[171])
Z(z[169])
Z([3,'60rpx'])
Z(z[503])
Z([3,'height:660rpx'])
Z([[7],[3,'wordsList']])
Z(z[47])
Z(z[178])
Z([3,'showWordImg'])
Z([3,'tui-word-image'])
Z(z[182])
Z(z[54])
Z([3,'tui-word-bottom'])
Z(z[488])
Z([3,'quiz-bottom-icon'])
Z(z[104])
Z([3,'collectWord'])
Z([3,'quiz-bottom-icon margin-left'])
Z([[2,'?:'],[[2,'=='],[[7],[3,'collect_status']],[1,false]],[1,'https://qianyufang.top/public/yingyu/images/icon/collect_no.png'],[1,'https://qianyufang.top/public/yingyu/images/icon/collect.png']])
Z([3,'goCardWord'])
Z(z[518])
Z(z[223])
Z([1,800])
Z([3,'fade'])
Z([[7],[3,'isRecording']])
Z([[7],[3,'styles']])
Z([3,'clickRecord'])
Z([3,'popup-recording'])
Z([a,[3,'icon-recording '],[[7],[3,'animation']]])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/recording.png'])
Z([3,'closePopup'])
Z(z[523])
Z(z[524])
Z([[7],[3,'transShow']])
Z(z[526])
Z([3,'pop-view'])
Z([3,'popup-text'])
Z([3,'text-macron value-text'])
Z([a,[[7],[3,'value']]])
Z([3,'result-text'])
Z([3,'text-white text-xl'])
Z([a,[[7],[3,'record_result']]])
Z([[7],[3,'posterUrl']])
Z([3,'poster-container'])
Z([3,'closePoster'])
Z([3,'close-btn'])
Z([3,'×'])
Z([3,'poster-img'])
Z(z[38])
Z(z[543])
Z([3,'savePoster'])
Z([3,'save-btn'])
Z([3,'保存到相册'])
Z([3,'hidden-canvas'])
Z([3,'posterCanvas'])
Z([3,'2d'])
})(__WXML_GLOBAL__.ops_cached.$gwx_XC_42_1);return __WXML_GLOBAL__.ops_cached.$gwx_XC_42_1
}
__WXML_GLOBAL__.ops_set.$gwx_XC_42=z;
__WXML_GLOBAL__.ops_init.$gwx_XC_42=true;
var x=['./pages/word/word.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx_XC_42_1()
var t3CD=_mz(z,'scroll-view',['scrollX',-1,'class',0],[],e,s,gg)
var e4CD=_mz(z,'view',['bindtap',1,'class',1,'data-id',2],[],e,s,gg)
var b5CD=_oz(z,4,e,s,gg)
_(e4CD,b5CD)
_(t3CD,e4CD)
var o6CD=_mz(z,'view',['bindtap',5,'class',1,'data-id',2],[],e,s,gg)
var x7CD=_oz(z,8,e,s,gg)
_(o6CD,x7CD)
_(t3CD,o6CD)
var o8CD=_mz(z,'view',['bindtap',9,'class',1,'data-id',2],[],e,s,gg)
var f9CD=_oz(z,12,e,s,gg)
_(o8CD,f9CD)
_(t3CD,o8CD)
var c0CD=_mz(z,'view',['bindtap',13,'class',1,'data-id',2],[],e,s,gg)
var hADD=_oz(z,16,e,s,gg)
_(c0CD,hADD)
_(t3CD,c0CD)
var oBDD=_mz(z,'view',['bindtap',17,'class',1,'data-id',2],[],e,s,gg)
var cCDD=_oz(z,20,e,s,gg)
_(oBDD,cCDD)
_(t3CD,oBDD)
var oDDD=_mz(z,'view',['bindtap',21,'class',1,'data-id',2],[],e,s,gg)
var lEDD=_oz(z,24,e,s,gg)
_(oDDD,lEDD)
_(t3CD,oDDD)
_(r,t3CD)
var cVCD=_v()
_(r,cVCD)
if(_oz(z,25,e,s,gg)){cVCD.wxVkey=1
var aFDD=_v()
_(cVCD,aFDD)
if(_oz(z,26,e,s,gg)){aFDD.wxVkey=1
var tGDD=_n('view')
_rz(z,tGDD,'class',27,e,s,gg)
var eHDD=_n('text')
_rz(z,eHDD,'class',28,e,s,gg)
var bIDD=_oz(z,29,e,s,gg)
_(eHDD,bIDD)
_(tGDD,eHDD)
var oJDD=_n('text')
_rz(z,oJDD,'class',30,e,s,gg)
var xKDD=_oz(z,31,e,s,gg)
_(oJDD,xKDD)
_(tGDD,oJDD)
var oLDD=_n('text')
_rz(z,oLDD,'class',32,e,s,gg)
var fMDD=_oz(z,33,e,s,gg)
_(oLDD,fMDD)
_(tGDD,oLDD)
var cNDD=_n('view')
_rz(z,cNDD,'class',34,e,s,gg)
var hODD=_v()
_(cNDD,hODD)
var oPDD=function(oRDD,cQDD,lSDD,gg){
var tUDD=_n('view')
_rz(z,tUDD,'class',36,oRDD,cQDD,gg)
var eVDD=_mz(z,'image',['class',37,'mode',1,'src',2],[],oRDD,cQDD,gg)
_(tUDD,eVDD)
_(lSDD,tUDD)
return lSDD
}
hODD.wxXCkey=2
_2z(z,35,oPDD,e,s,gg,hODD,'item','index','')
_(tGDD,cNDD)
_(aFDD,tGDD)
}
else{aFDD.wxVkey=2
var bWDD=_v()
_(aFDD,bWDD)
if(_oz(z,40,e,s,gg)){bWDD.wxVkey=1
var xYDD=_n('view')
_rz(z,xYDD,'class',41,e,s,gg)
var oZDD=_n('view')
_rz(z,oZDD,'style',42,e,s,gg)
_(xYDD,oZDD)
_(bWDD,xYDD)
var oXDD=_v()
_(bWDD,oXDD)
if(_oz(z,43,e,s,gg)){oXDD.wxVkey=1
var f1DD=_v()
_(oXDD,f1DD)
if(_oz(z,44,e,s,gg)){f1DD.wxVkey=1
var c2DD=_n('view')
_rz(z,c2DD,'class',45,e,s,gg)
var h3DD=_v()
_(c2DD,h3DD)
var o4DD=function(o6DD,c5DD,l7DD,gg){
var t9DD=_mz(z,'view',['bind:longpress',48,'bindtap',1,'class',2,'data-index',3],[],o6DD,c5DD,gg)
var e0DD=_n('view')
_rz(z,e0DD,'class',52,o6DD,c5DD,gg)
var bAED=_mz(z,'image',['class',53,'src',1,'style',2],[],o6DD,c5DD,gg)
_(e0DD,bAED)
_(t9DD,e0DD)
_(l7DD,t9DD)
return l7DD
}
h3DD.wxXCkey=2
_2z(z,46,o4DD,e,s,gg,h3DD,'item','index','index')
_(f1DD,c2DD)
}
else{f1DD.wxVkey=2
var oBED=_n('tui-grid')
var xCED=_v()
_(oBED,xCED)
var oDED=function(cFED,fEED,hGED,gg){
var cIED=_n('tui-grid-item')
_rz(z,cIED,'cell',58,cFED,fEED,gg)
var oJED=_mz(z,'view',['bind:longpress',59,'bindtap',1,'class',2,'data-index',3],[],cFED,fEED,gg)
var lKED=_mz(z,'image',['class',63,'lazyLoad',1,'mode',2,'src',3],[],cFED,fEED,gg)
_(oJED,lKED)
_(cIED,oJED)
_(hGED,cIED)
return hGED
}
xCED.wxXCkey=4
_2z(z,56,oDED,e,s,gg,xCED,'item','index','index')
_(f1DD,oBED)
}
var aLED=_n('view')
_rz(z,aLED,'class',67,e,s,gg)
var tMED=_mz(z,'image',['bindtap',68,'class',1,'src',2],[],e,s,gg)
_(aLED,tMED)
var eNED=_mz(z,'view',['bind:tap',71,'class',1],[],e,s,gg)
var bOED=_n('text')
_rz(z,bOED,'class',73,e,s,gg)
var oPED=_oz(z,74,e,s,gg)
_(bOED,oPED)
_(eNED,bOED)
var xQED=_mz(z,'tui-icon',['color',75,'name',1,'size',2,'unit',3],[],e,s,gg)
_(eNED,xQED)
_(aLED,eNED)
var oRED=_mz(z,'image',['bindtap',79,'class',1,'src',2],[],e,s,gg)
_(aLED,oRED)
_(oXDD,aLED)
f1DD.wxXCkey=1
f1DD.wxXCkey=3
}
else{oXDD.wxVkey=2
var cTED=_v()
_(oXDD,cTED)
var hUED=function(cWED,oVED,oXED,gg){
var aZED=_n('view')
_rz(z,aZED,'class',83,cWED,oVED,gg)
var t1ED=_mz(z,'view',['bind:longpress',84,'bindtap',1,'class',2,'data-index',3],[],cWED,oVED,gg)
var e2ED=_n('text')
_rz(z,e2ED,'class',88,cWED,oVED,gg)
var b3ED=_oz(z,89,cWED,oVED,gg)
_(e2ED,b3ED)
_(t1ED,e2ED)
_(aZED,t1ED)
_(oXED,aZED)
return oXED
}
cTED.wxXCkey=2
_2z(z,82,hUED,e,s,gg,cTED,'item','index','')
var fSED=_v()
_(oXDD,fSED)
if(_oz(z,90,e,s,gg)){fSED.wxVkey=1
var o4ED=_n('view')
_rz(z,o4ED,'class',91,e,s,gg)
var x5ED=_n('view')
_rz(z,x5ED,'class',92,e,s,gg)
var o6ED=_n('text')
_rz(z,o6ED,'class',93,e,s,gg)
var f7ED=_oz(z,94,e,s,gg)
_(o6ED,f7ED)
_(x5ED,o6ED)
var c8ED=_n('text')
_rz(z,c8ED,'class',95,e,s,gg)
var h9ED=_oz(z,96,e,s,gg)
_(c8ED,h9ED)
_(x5ED,c8ED)
_(o4ED,x5ED)
_(fSED,o4ED)
}
var o0ED=_mz(z,'view',['class',97,'style',1],[],e,s,gg)
var cAFD=_mz(z,'image',['bindtap',99,'class',1,'src',2],[],e,s,gg)
_(o0ED,cAFD)
var oBFD=_mz(z,'image',['bindtap',102,'class',1,'src',2],[],e,s,gg)
_(o0ED,oBFD)
var lCFD=_mz(z,'image',['bindtap',105,'class',1,'src',2],[],e,s,gg)
_(o0ED,lCFD)
_(oXDD,o0ED)
fSED.wxXCkey=1
}
oXDD.wxXCkey=1
oXDD.wxXCkey=3
}
else{bWDD.wxVkey=2
var aDFD=_n('view')
_rz(z,aDFD,'class',108,e,s,gg)
var tEFD=_n('view')
_rz(z,tEFD,'class',109,e,s,gg)
var eFFD=_v()
_(tEFD,eFFD)
if(_oz(z,110,e,s,gg)){eFFD.wxVkey=1
var xIFD=_mz(z,'image',['class',111,'src',1],[],e,s,gg)
_(eFFD,xIFD)
}
var oJFD=_n('text')
_rz(z,oJFD,'class',113,e,s,gg)
var fKFD=_oz(z,114,e,s,gg)
_(oJFD,fKFD)
_(tEFD,oJFD)
var bGFD=_v()
_(tEFD,bGFD)
if(_oz(z,115,e,s,gg)){bGFD.wxVkey=1
var cLFD=_mz(z,'image',['class',116,'src',1],[],e,s,gg)
_(bGFD,cLFD)
}
var oHFD=_v()
_(tEFD,oHFD)
if(_oz(z,118,e,s,gg)){oHFD.wxVkey=1
var hMFD=_mz(z,'image',['class',119,'mode',1,'src',2],[],e,s,gg)
_(oHFD,hMFD)
}
eFFD.wxXCkey=1
bGFD.wxXCkey=1
oHFD.wxXCkey=1
_(aDFD,tEFD)
_(bWDD,aDFD)
var oNFD=_v()
_(bWDD,oNFD)
var cOFD=function(lQFD,oPFD,aRFD,gg){
var eTFD=_n('view')
var bUFD=_mz(z,'tui-collapse',['bindclick',124,'current',1,'index',2],[],lQFD,oPFD,gg)
var oVFD=_n('view')
_rz(z,oVFD,'slot',127,lQFD,oPFD,gg)
var xWFD=_n('view')
_rz(z,xWFD,'class',128,lQFD,oPFD,gg)
var oXFD=_mz(z,'tui-rate',['current',129,'disabled',1,'quantity',2,'size',3],[],lQFD,oPFD,gg)
_(xWFD,oXFD)
var fYFD=_n('view')
_rz(z,fYFD,'class',133,lQFD,oPFD,gg)
var cZFD=_oz(z,134,lQFD,oPFD,gg)
_(fYFD,cZFD)
_(xWFD,fYFD)
_(oVFD,xWFD)
_(bUFD,oVFD)
var h1FD=_n('view')
_rz(z,h1FD,'slot',135,lQFD,oPFD,gg)
var o2FD=_v()
_(h1FD,o2FD)
var c3FD=function(l5FD,o4FD,a6FD,gg){
var e8FD=_n('view')
_rz(z,e8FD,'class',140,l5FD,o4FD,gg)
var b9FD=_mz(z,'tui-list-cell',['bindtap',141,'data-index',1,'data-word',2],[],l5FD,o4FD,gg)
var o0FD=_oz(z,144,l5FD,o4FD,gg)
_(b9FD,o0FD)
_(e8FD,b9FD)
_(a6FD,e8FD)
return a6FD
}
o2FD.wxXCkey=4
_2z(z,138,c3FD,lQFD,oPFD,gg,o2FD,'citem','cindex','index')
_(bUFD,h1FD)
_(eTFD,bUFD)
_(aRFD,eTFD)
return aRFD
}
oNFD.wxXCkey=4
_2z(z,122,cOFD,e,s,gg,oNFD,'item','index','index')
var xAGD=_n('view')
_rz(z,xAGD,'class',145,e,s,gg)
var oBGD=_mz(z,'button',['bindtap',146,'class',1,'style',2],[],e,s,gg)
var fCGD=_oz(z,149,e,s,gg)
_(oBGD,fCGD)
_(xAGD,oBGD)
_(bWDD,xAGD)
}
bWDD.wxXCkey=1
bWDD.wxXCkey=3
bWDD.wxXCkey=3
}
aFDD.wxXCkey=1
aFDD.wxXCkey=3
}
var hWCD=_v()
_(r,hWCD)
if(_oz(z,150,e,s,gg)){hWCD.wxVkey=1
var cDGD=_v()
_(hWCD,cDGD)
if(_oz(z,151,e,s,gg)){cDGD.wxVkey=1
var hEGD=_n('view')
_rz(z,hEGD,'class',152,e,s,gg)
var oFGD=_n('text')
_rz(z,oFGD,'class',153,e,s,gg)
var cGGD=_oz(z,154,e,s,gg)
_(oFGD,cGGD)
_(hEGD,oFGD)
var oHGD=_n('text')
_rz(z,oHGD,'class',155,e,s,gg)
var lIGD=_oz(z,156,e,s,gg)
_(oHGD,lIGD)
_(hEGD,oHGD)
var aJGD=_n('text')
_rz(z,aJGD,'class',157,e,s,gg)
var tKGD=_oz(z,158,e,s,gg)
_(aJGD,tKGD)
_(hEGD,aJGD)
var eLGD=_n('text')
_rz(z,eLGD,'class',159,e,s,gg)
_(hEGD,eLGD)
var bMGD=_n('view')
_rz(z,bMGD,'class',160,e,s,gg)
var oNGD=_v()
_(bMGD,oNGD)
var xOGD=function(fQGD,oPGD,cRGD,gg){
var oTGD=_n('view')
_rz(z,oTGD,'class',163,fQGD,oPGD,gg)
var cUGD=_mz(z,'image',['class',164,'mode',1,'src',2],[],fQGD,oPGD,gg)
_(oTGD,cUGD)
_(cRGD,oTGD)
return cRGD
}
oNGD.wxXCkey=2
_2z(z,161,xOGD,e,s,gg,oNGD,'item','index','index')
_(hEGD,bMGD)
_(cDGD,hEGD)
}
else{cDGD.wxVkey=2
var oVGD=_n('view')
_rz(z,oVGD,'class',167,e,s,gg)
var lWGD=_mz(z,'swiper',['bindchange',168,'circular',1,'current',2,'duration',3,'indicatorDots',4,'nextMargin',5,'previousMargin',6,'style',7],[],e,s,gg)
var aXGD=_v()
_(lWGD,aXGD)
var tYGD=function(b1GD,eZGD,o2GD,gg){
var o4GD=_n('swiper-item')
_rz(z,o4GD,'class',178,b1GD,eZGD,gg)
var f5GD=_n('view')
_rz(z,f5GD,'class',179,b1GD,eZGD,gg)
var c6GD=_mz(z,'image',['bindtap',180,'class',1,'mode',2,'src',3],[],b1GD,eZGD,gg)
var h7GD=_n('view')
_rz(z,h7GD,'class',184,b1GD,eZGD,gg)
var o8GD=_mz(z,'image',['class',185,'src',1],[],b1GD,eZGD,gg)
_(h7GD,o8GD)
_(c6GD,h7GD)
var c9GD=_mz(z,'view',['catch:tap',187,'class',1],[],b1GD,eZGD,gg)
var o0GD=_mz(z,'image',['class',189,'src',1],[],b1GD,eZGD,gg)
_(c9GD,o0GD)
_(c6GD,c9GD)
_(f5GD,c6GD)
_(o4GD,f5GD)
var lAHD=_n('view')
_rz(z,lAHD,'class',191,b1GD,eZGD,gg)
var aBHD=_v()
_(lAHD,aBHD)
if(_oz(z,192,b1GD,eZGD,gg)){aBHD.wxVkey=1
var eDHD=_mz(z,'view',['bindtap',193,'class',1],[],b1GD,eZGD,gg)
var bEHD=_n('text')
_rz(z,bEHD,'class',195,b1GD,eZGD,gg)
var oFHD=_oz(z,196,b1GD,eZGD,gg)
_(bEHD,oFHD)
_(eDHD,bEHD)
_(aBHD,eDHD)
}
var tCHD=_v()
_(lAHD,tCHD)
if(_oz(z,197,b1GD,eZGD,gg)){tCHD.wxVkey=1
var xGHD=_v()
_(tCHD,xGHD)
var oHHD=function(cJHD,fIHD,hKHD,gg){
var cMHD=_mz(z,'view',['bind:tap',200,'class',1,'data-id',2],[],cJHD,fIHD,gg)
var oNHD=_n('text')
_rz(z,oNHD,'class',203,cJHD,fIHD,gg)
var lOHD=_oz(z,204,cJHD,fIHD,gg)
_(oNHD,lOHD)
_(cMHD,oNHD)
var aPHD=_n('view')
_rz(z,aPHD,'class',205,cJHD,fIHD,gg)
var tQHD=_v()
_(aPHD,tQHD)
if(_oz(z,206,cJHD,fIHD,gg)){tQHD.wxVkey=1
var eRHD=_mz(z,'image',['class',207,'mode',1,'src',2],[],cJHD,fIHD,gg)
_(tQHD,eRHD)
}
tQHD.wxXCkey=1
_(cMHD,aPHD)
_(hKHD,cMHD)
return hKHD
}
xGHD.wxXCkey=2
_2z(z,198,oHHD,b1GD,eZGD,gg,xGHD,'item','index','index')
}
aBHD.wxXCkey=1
tCHD.wxXCkey=1
_(o4GD,lAHD)
_(o2GD,o4GD)
return o2GD
}
aXGD.wxXCkey=2
_2z(z,176,tYGD,e,s,gg,aXGD,'item','index','index')
_(oVGD,lWGD)
_(cDGD,oVGD)
var bSHD=_mz(z,'view',['class',210,'style',1],[],e,s,gg)
var oTHD=_mz(z,'image',['bindtap',212,'class',1,'src',2],[],e,s,gg)
_(bSHD,oTHD)
var xUHD=_mz(z,'image',['bindtap',215,'class',1,'src',2],[],e,s,gg)
_(bSHD,xUHD)
var oVHD=_mz(z,'image',['bindtap',218,'class',1,'src',2],[],e,s,gg)
_(bSHD,oVHD)
var fWHD=_mz(z,'image',['bindtap',221,'class',1,'src',2],[],e,s,gg)
_(bSHD,fWHD)
_(cDGD,bSHD)
}
cDGD.wxXCkey=1
}
var oXCD=_v()
_(r,oXCD)
if(_oz(z,224,e,s,gg)){oXCD.wxVkey=1
var cXHD=_v()
_(oXCD,cXHD)
if(_oz(z,225,e,s,gg)){cXHD.wxVkey=1
var hYHD=_n('view')
_rz(z,hYHD,'class',226,e,s,gg)
var oZHD=_n('text')
_rz(z,oZHD,'class',227,e,s,gg)
var c1HD=_oz(z,228,e,s,gg)
_(oZHD,c1HD)
_(hYHD,oZHD)
var o2HD=_n('text')
_rz(z,o2HD,'class',229,e,s,gg)
var l3HD=_oz(z,230,e,s,gg)
_(o2HD,l3HD)
_(hYHD,o2HD)
var a4HD=_n('text')
_rz(z,a4HD,'class',231,e,s,gg)
var t5HD=_oz(z,232,e,s,gg)
_(a4HD,t5HD)
_(hYHD,a4HD)
var e6HD=_n('view')
_rz(z,e6HD,'class',233,e,s,gg)
var b7HD=_v()
_(e6HD,b7HD)
var o8HD=function(o0HD,x9HD,fAID,gg){
var hCID=_n('view')
_rz(z,hCID,'class',235,o0HD,x9HD,gg)
var oDID=_mz(z,'image',['class',236,'mode',1,'src',2],[],o0HD,x9HD,gg)
_(hCID,oDID)
_(fAID,hCID)
return fAID
}
b7HD.wxXCkey=2
_2z(z,234,o8HD,e,s,gg,b7HD,'item','index','')
_(hYHD,e6HD)
_(cXHD,hYHD)
}
else{cXHD.wxVkey=2
var cEID=_v()
_(cXHD,cEID)
if(_oz(z,239,e,s,gg)){cEID.wxVkey=1
var oFID=_mz(z,'scroll-view',['scrollY',-1,'style',240],[],e,s,gg)
var aHID=_mz(z,'tui-list-cell',['hover',241,'padding',1],[],e,s,gg)
var tIID=_n('view')
_rz(z,tIID,'class',243,e,s,gg)
var eJID=_n('view')
_rz(z,eJID,'class',244,e,s,gg)
var bKID=_v()
_(eJID,bKID)
if(_oz(z,245,e,s,gg)){bKID.wxVkey=1
var oLID=_oz(z,246,e,s,gg)
_(bKID,oLID)
}
else{bKID.wxVkey=2
var xMID=_oz(z,247,e,s,gg)
_(bKID,xMID)
}
bKID.wxXCkey=1
_(tIID,eJID)
var oNID=_mz(z,'switch',['bindchange',248,'checked',1,'class',2],[],e,s,gg)
_(tIID,oNID)
_(aHID,tIID)
_(oFID,aHID)
var fOID=_v()
_(oFID,fOID)
var cPID=function(oRID,hQID,cSID,gg){
var lUID=_n('tui-list-view')
var aVID=_n('tui-list-cell')
_rz(z,aVID,'lineLeft',253,oRID,hQID,gg)
var tWID=_mz(z,'view',['catch:tap',254,'class',1,'data-id',2],[],oRID,hQID,gg)
var eXID=_n('view')
_rz(z,eXID,'class',257,oRID,hQID,gg)
var bYID=_mz(z,'image',['class',258,'mode',1,'src',2],[],oRID,hQID,gg)
_(eXID,bYID)
var oZID=_n('view')
_rz(z,oZID,'class',261,oRID,hQID,gg)
var x1ID=_n('view')
_rz(z,x1ID,'class',262,oRID,hQID,gg)
var o2ID=_oz(z,263,oRID,hQID,gg)
_(x1ID,o2ID)
_(oZID,x1ID)
var f3ID=_n('view')
_rz(z,f3ID,'class',264,oRID,hQID,gg)
var c4ID=_oz(z,265,oRID,hQID,gg)
_(f3ID,c4ID)
_(oZID,f3ID)
_(eXID,oZID)
_(tWID,eXID)
var h5ID=_n('view')
_rz(z,h5ID,'class',266,oRID,hQID,gg)
var o6ID=_mz(z,'tui-icon',['catch:tap',267,'color',1,'data-id',2,'name',3,'size',4,'unit',5],[],oRID,hQID,gg)
_(h5ID,o6ID)
_(tWID,h5ID)
_(aVID,tWID)
_(lUID,aVID)
_(cSID,lUID)
return cSID
}
fOID.wxXCkey=4
_2z(z,251,cPID,e,s,gg,fOID,'item','index','index')
var lGID=_v()
_(oFID,lGID)
if(_oz(z,273,e,s,gg)){lGID.wxVkey=1
var c7ID=_n('view')
_rz(z,c7ID,'class',274,e,s,gg)
var o8ID=_n('view')
_rz(z,o8ID,'class',275,e,s,gg)
var l9ID=_oz(z,276,e,s,gg)
_(o8ID,l9ID)
_(c7ID,o8ID)
var a0ID=_n('view')
_rz(z,a0ID,'class',277,e,s,gg)
var tAJD=_oz(z,278,e,s,gg)
_(a0ID,tAJD)
_(c7ID,a0ID)
_(lGID,c7ID)
}
var eBJD=_mz(z,'tui-nomore',['backgroundColor',279,'text',1],[],e,s,gg)
_(oFID,eBJD)
lGID.wxXCkey=1
_(cEID,oFID)
}
else{cEID.wxVkey=2
var bCJD=_mz(z,'view',['bind:tap',281,'class',1],[],e,s,gg)
var oDJD=_n('view')
_rz(z,oDJD,'class',283,e,s,gg)
var oFJD=_n('text')
_rz(z,oFJD,'class',284,e,s,gg)
var fGJD=_oz(z,285,e,s,gg)
_(oFJD,fGJD)
_(oDJD,oFJD)
var xEJD=_v()
_(oDJD,xEJD)
if(_oz(z,286,e,s,gg)){xEJD.wxVkey=1
var cHJD=_n('text')
_rz(z,cHJD,'class',287,e,s,gg)
var hIJD=_oz(z,288,e,s,gg)
_(cHJD,hIJD)
_(xEJD,cHJD)
}
var oJJD=_n('text')
_rz(z,oJJD,'class',289,e,s,gg)
var cKJD=_oz(z,290,e,s,gg)
_(oJJD,cKJD)
_(oDJD,oJJD)
var oLJD=_mz(z,'tui-icon',['color',291,'name',1,'size',2,'unit',3],[],e,s,gg)
_(oDJD,oLJD)
xEJD.wxXCkey=1
_(bCJD,oDJD)
_(cEID,bCJD)
var lMJD=_n('view')
_rz(z,lMJD,'class',295,e,s,gg)
var aNJD=_mz(z,'swiper',['bindchange',296,'circular',1,'current',2,'duration',3,'indicatorColor',4,'indicatorDots',5,'nextMargin',6,'previousMargin',7,'style',8],[],e,s,gg)
var tOJD=_v()
_(aNJD,tOJD)
var ePJD=function(oRJD,bQJD,xSJD,gg){
var fUJD=_n('swiper-item')
_rz(z,fUJD,'class',307,oRJD,bQJD,gg)
var cVJD=_n('view')
_rz(z,cVJD,'class',308,oRJD,bQJD,gg)
var hWJD=_mz(z,'image',['bind:tap',309,'class',1,'mode',2,'src',3],[],oRJD,bQJD,gg)
var oXJD=_mz(z,'view',['catch:tap',313,'class',1],[],oRJD,bQJD,gg)
var cYJD=_mz(z,'image',['class',315,'src',1],[],oRJD,bQJD,gg)
_(oXJD,cYJD)
_(hWJD,oXJD)
_(cVJD,hWJD)
var oZJD=_n('view')
_rz(z,oZJD,'class',317,oRJD,bQJD,gg)
var l1JD=_oz(z,318,oRJD,bQJD,gg)
_(oZJD,l1JD)
_(cVJD,oZJD)
_(fUJD,cVJD)
_(xSJD,fUJD)
return xSJD
}
tOJD.wxXCkey=2
_2z(z,305,ePJD,e,s,gg,tOJD,'item','index','index')
_(lMJD,aNJD)
_(cEID,lMJD)
var a2JD=_mz(z,'view',['class',319,'style',1],[],e,s,gg)
var t3JD=_mz(z,'image',['bindtap',321,'class',1,'src',2],[],e,s,gg)
_(a2JD,t3JD)
var e4JD=_mz(z,'image',['bindtap',324,'class',1,'src',2],[],e,s,gg)
_(a2JD,e4JD)
var b5JD=_mz(z,'image',['bindtap',327,'class',1,'src',2],[],e,s,gg)
_(a2JD,b5JD)
var o6JD=_mz(z,'image',['bindtap',330,'class',1,'src',2],[],e,s,gg)
_(a2JD,o6JD)
_(cEID,a2JD)
}
cEID.wxXCkey=1
cEID.wxXCkey=3
cEID.wxXCkey=3
}
cXHD.wxXCkey=1
cXHD.wxXCkey=3
}
var cYCD=_v()
_(r,cYCD)
if(_oz(z,333,e,s,gg)){cYCD.wxVkey=1
var x7JD=_v()
_(cYCD,x7JD)
if(_oz(z,334,e,s,gg)){x7JD.wxVkey=1
var o8JD=_n('view')
_rz(z,o8JD,'class',335,e,s,gg)
var f9JD=_n('text')
_rz(z,f9JD,'class',336,e,s,gg)
var c0JD=_oz(z,337,e,s,gg)
_(f9JD,c0JD)
_(o8JD,f9JD)
_(x7JD,o8JD)
}
else{x7JD.wxVkey=2
var oBKD=_mz(z,'view',['bind:tap',338,'class',1],[],e,s,gg)
var cCKD=_n('text')
_rz(z,cCKD,'class',340,e,s,gg)
var oDKD=_oz(z,341,e,s,gg)
_(cCKD,oDKD)
_(oBKD,cCKD)
var lEKD=_n('text')
_rz(z,lEKD,'class',342,e,s,gg)
var aFKD=_oz(z,343,e,s,gg)
_(lEKD,aFKD)
_(oBKD,lEKD)
var tGKD=_mz(z,'tui-icon',['color',344,'name',1,'size',2,'unit',3],[],e,s,gg)
_(oBKD,tGKD)
_(x7JD,oBKD)
var eHKD=_n('view')
_rz(z,eHKD,'class',348,e,s,gg)
var oJKD=_mz(z,'view',['bind:tap',349,'class',1],[],e,s,gg)
var xKKD=_v()
_(oJKD,xKKD)
var oLKD=function(cNKD,fMKD,hOKD,gg){
var cQKD=_mz(z,'text',['class',354,'style',1],[],cNKD,fMKD,gg)
var oRKD=_oz(z,356,cNKD,fMKD,gg)
_(cQKD,oRKD)
_(hOKD,cQKD)
return hOKD
}
xKKD.wxXCkey=2
_2z(z,352,oLKD,e,s,gg,xKKD,'item','index','index')
var lSKD=_v()
_(oJKD,lSKD)
var aTKD=function(eVKD,tUKD,bWKD,gg){
var xYKD=_mz(z,'text',['class',359,'style',1],[],eVKD,tUKD,gg)
var oZKD=_oz(z,361,eVKD,tUKD,gg)
_(xYKD,oZKD)
_(bWKD,xYKD)
return bWKD
}
lSKD.wxXCkey=2
_2z(z,357,aTKD,e,s,gg,lSKD,'item','index','index')
_(eHKD,oJKD)
var bIKD=_v()
_(eHKD,bIKD)
if(_oz(z,362,e,s,gg)){bIKD.wxVkey=1
var f1KD=_n('view')
_rz(z,f1KD,'class',363,e,s,gg)
var c2KD=_v()
_(f1KD,c2KD)
var h3KD=function(c5KD,o4KD,o6KD,gg){
var a8KD=_mz(z,'button',['bindtap',366,'class',1,'data-index',2,'disabled',3,'style',4],[],c5KD,o4KD,gg)
var t9KD=_oz(z,371,c5KD,o4KD,gg)
_(a8KD,t9KD)
_(o6KD,a8KD)
return o6KD
}
c2KD.wxXCkey=2
_2z(z,364,h3KD,e,s,gg,c2KD,'item','index','index')
_(bIKD,f1KD)
}
bIKD.wxXCkey=1
_(x7JD,eHKD)
var hAKD=_v()
_(x7JD,hAKD)
if(_oz(z,372,e,s,gg)){hAKD.wxVkey=1
var e0KD=_n('view')
_rz(z,e0KD,'class',373,e,s,gg)
var bALD=_mz(z,'image',['class',374,'mode',1,'src',2],[],e,s,gg)
_(e0KD,bALD)
_(hAKD,e0KD)
}
var oBLD=_mz(z,'view',['class',377,'style',1],[],e,s,gg)
var xCLD=_mz(z,'image',['bindtap',379,'class',1,'src',2],[],e,s,gg)
_(oBLD,xCLD)
var oDLD=_mz(z,'image',['bindtap',382,'class',1,'src',2],[],e,s,gg)
_(oBLD,oDLD)
var fELD=_mz(z,'image',['bindtap',385,'class',1,'src',2],[],e,s,gg)
_(oBLD,fELD)
var cFLD=_mz(z,'image',['bindtap',388,'class',1,'src',2],[],e,s,gg)
_(oBLD,cFLD)
_(x7JD,oBLD)
hAKD.wxXCkey=1
}
x7JD.wxXCkey=1
x7JD.wxXCkey=3
}
var oZCD=_v()
_(r,oZCD)
if(_oz(z,391,e,s,gg)){oZCD.wxVkey=1
var hGLD=_v()
_(oZCD,hGLD)
if(_oz(z,392,e,s,gg)){hGLD.wxVkey=1
var oHLD=_n('view')
_rz(z,oHLD,'class',393,e,s,gg)
var cILD=_n('text')
_rz(z,cILD,'class',394,e,s,gg)
var oJLD=_oz(z,395,e,s,gg)
_(cILD,oJLD)
_(oHLD,cILD)
var lKLD=_n('text')
_rz(z,lKLD,'class',396,e,s,gg)
var aLLD=_oz(z,397,e,s,gg)
_(lKLD,aLLD)
_(oHLD,lKLD)
var tMLD=_n('text')
_rz(z,tMLD,'class',398,e,s,gg)
var eNLD=_oz(z,399,e,s,gg)
_(tMLD,eNLD)
_(oHLD,tMLD)
var bOLD=_n('view')
_rz(z,bOLD,'class',400,e,s,gg)
var oPLD=_v()
_(bOLD,oPLD)
var xQLD=function(fSLD,oRLD,cTLD,gg){
var oVLD=_n('view')
_rz(z,oVLD,'class',403,fSLD,oRLD,gg)
var cWLD=_mz(z,'image',['class',404,'mode',1,'src',2],[],fSLD,oRLD,gg)
_(oVLD,cWLD)
_(cTLD,oVLD)
return cTLD
}
oPLD.wxXCkey=2
_2z(z,401,xQLD,e,s,gg,oPLD,'item','index','index')
_(oHLD,bOLD)
_(hGLD,oHLD)
}
else{hGLD.wxVkey=2
var oXLD=_n('view')
_rz(z,oXLD,'class',407,e,s,gg)
var lYLD=_mz(z,'swiper',['bindchange',408,'circular',1,'current',2,'duration',3,'indicatorDots',4,'nextMargin',5,'previousMargin',6,'style',7],[],e,s,gg)
var aZLD=_v()
_(lYLD,aZLD)
var t1LD=function(b3LD,e2LD,o4LD,gg){
var o6LD=_n('swiper-item')
_rz(z,o6LD,'class',418,b3LD,e2LD,gg)
var f7LD=_n('view')
_rz(z,f7LD,'class',419,b3LD,e2LD,gg)
var c8LD=_mz(z,'image',['bindtap',420,'class',1,'mode',2,'src',3],[],b3LD,e2LD,gg)
var h9LD=_n('view')
_rz(z,h9LD,'class',424,b3LD,e2LD,gg)
var o0LD=_mz(z,'image',['class',425,'src',1],[],b3LD,e2LD,gg)
_(h9LD,o0LD)
_(c8LD,h9LD)
_(f7LD,c8LD)
_(o6LD,f7LD)
_(o4LD,o6LD)
return o4LD
}
aZLD.wxXCkey=2
_2z(z,416,t1LD,e,s,gg,aZLD,'item','index','index')
_(oXLD,lYLD)
_(hGLD,oXLD)
var cAMD=_n('view')
_rz(z,cAMD,'class',427,e,s,gg)
var lCMD=_n('view')
_rz(z,lCMD,'class',428,e,s,gg)
var aDMD=_n('text')
_rz(z,aDMD,'class',429,e,s,gg)
var tEMD=_oz(z,430,e,s,gg)
_(aDMD,tEMD)
_(lCMD,aDMD)
_(cAMD,lCMD)
var oBMD=_v()
_(cAMD,oBMD)
if(_oz(z,431,e,s,gg)){oBMD.wxVkey=1
var eFMD=_mz(z,'view',['bind:tap',432,'class',1],[],e,s,gg)
var bGMD=_mz(z,'image',['class',434,'src',1],[],e,s,gg)
_(eFMD,bGMD)
var oHMD=_n('text')
_rz(z,oHMD,'class',436,e,s,gg)
var xIMD=_oz(z,437,e,s,gg)
_(oHMD,xIMD)
_(eFMD,oHMD)
_(oBMD,eFMD)
}
oBMD.wxXCkey=1
_(hGLD,cAMD)
var oJMD=_mz(z,'view',['class',438,'style',1],[],e,s,gg)
var fKMD=_mz(z,'image',['bindtap',440,'class',1,'src',2],[],e,s,gg)
_(oJMD,fKMD)
var cLMD=_mz(z,'image',['bindtap',443,'class',1,'src',2],[],e,s,gg)
_(oJMD,cLMD)
var hMMD=_mz(z,'image',['bind:tap',446,'class',1,'src',2],[],e,s,gg)
_(oJMD,hMMD)
var oNMD=_mz(z,'image',['bindtap',449,'class',1,'src',2],[],e,s,gg)
_(oJMD,oNMD)
_(hGLD,oJMD)
}
hGLD.wxXCkey=1
}
var l1CD=_v()
_(r,l1CD)
if(_oz(z,452,e,s,gg)){l1CD.wxVkey=1
var oPMD=_n('view')
_rz(z,oPMD,'class',453,e,s,gg)
var lQMD=_n('view')
_rz(z,lQMD,'class',454,e,s,gg)
var aRMD=_mz(z,'tui-charts-column',['tooltip',-1,'bindclick',455,'clickEffect',1,'columnBarWidth',2,'columnCap',3,'dataset',4,'id',5,'max',6,'splitNumber',7,'xAxis',8,'xAxisVal',9],[],e,s,gg)
_(lQMD,aRMD)
_(oPMD,lQMD)
_(l1CD,oPMD)
var cOMD=_v()
_(l1CD,cOMD)
if(_oz(z,465,e,s,gg)){cOMD.wxVkey=1
var tSMD=_n('view')
_rz(z,tSMD,'class',466,e,s,gg)
var eTMD=_n('view')
_rz(z,eTMD,'class',467,e,s,gg)
var bUMD=_mz(z,'tui-charts-pie',['id',468,'type',1],[],e,s,gg)
_(eTMD,bUMD)
_(tSMD,eTMD)
_(cOMD,tSMD)
}
var oVMD=_n('view')
_rz(z,oVMD,'class',470,e,s,gg)
var xWMD=_n('view')
_rz(z,xWMD,'class',471,e,s,gg)
var oXMD=_oz(z,472,e,s,gg)
_(xWMD,oXMD)
_(oVMD,xWMD)
var fYMD=_n('view')
_rz(z,fYMD,'class',473,e,s,gg)
var cZMD=_oz(z,474,e,s,gg)
_(fYMD,cZMD)
_(oVMD,fYMD)
var h1MD=_n('view')
_rz(z,h1MD,'class',475,e,s,gg)
var o2MD=_oz(z,476,e,s,gg)
_(h1MD,o2MD)
_(oVMD,h1MD)
var c3MD=_n('view')
_rz(z,c3MD,'class',477,e,s,gg)
var o4MD=_oz(z,478,e,s,gg)
_(c3MD,o4MD)
_(oVMD,c3MD)
var l5MD=_n('view')
_rz(z,l5MD,'class',479,e,s,gg)
var a6MD=_oz(z,480,e,s,gg)
_(l5MD,a6MD)
_(oVMD,l5MD)
var t7MD=_n('view')
_rz(z,t7MD,'class',481,e,s,gg)
var e8MD=_oz(z,482,e,s,gg)
_(t7MD,e8MD)
_(oVMD,t7MD)
_(l1CD,oVMD)
cOMD.wxXCkey=1
cOMD.wxXCkey=3
}
var b9MD=_mz(z,'tui-bottom-popup',['bindclose',483,'maskZIndex',1,'show',2,'zIndex',3],[],e,s,gg)
var o0MD=_n('view')
_rz(z,o0MD,'class',487,e,s,gg)
var xAND=_mz(z,'view',['bindtap',488,'class',1],[],e,s,gg)
var oBND=_n('view')
_rz(z,oBND,'class',490,e,s,gg)
var cDND=_n('text')
_rz(z,cDND,'class',491,e,s,gg)
var hEND=_oz(z,492,e,s,gg)
_(cDND,hEND)
_(oBND,cDND)
var fCND=_v()
_(oBND,fCND)
if(_oz(z,493,e,s,gg)){fCND.wxVkey=1
var oFND=_n('text')
_rz(z,oFND,'class',494,e,s,gg)
var cGND=_oz(z,495,e,s,gg)
_(oFND,cGND)
_(fCND,oFND)
}
var oHND=_n('text')
_rz(z,oHND,'class',496,e,s,gg)
var lIND=_oz(z,497,e,s,gg)
_(oHND,lIND)
_(oBND,oHND)
fCND.wxXCkey=1
_(xAND,oBND)
_(o0MD,xAND)
var aJND=_mz(z,'swiper',['bindchange',498,'circular',1,'current',2,'duration',3,'indicatorDots',4,'nextMargin',5,'previousMargin',6,'style',7],[],e,s,gg)
var tKND=_v()
_(aJND,tKND)
var eLND=function(oNND,bMND,xOND,gg){
var fQND=_n('swiper-item')
_rz(z,fQND,'class',508,oNND,bMND,gg)
var cRND=_mz(z,'image',['bindtap',509,'class',1,'mode',2,'src',3],[],oNND,bMND,gg)
_(fQND,cRND)
_(xOND,fQND)
return xOND
}
tKND.wxXCkey=2
_2z(z,506,eLND,e,s,gg,tKND,'item','index','index')
_(o0MD,aJND)
_(b9MD,o0MD)
var hSND=_n('view')
_rz(z,hSND,'class',513,e,s,gg)
var oTND=_mz(z,'image',['bindtap',514,'class',1,'src',2],[],e,s,gg)
_(hSND,oTND)
var cUND=_mz(z,'image',['bindtap',517,'class',1,'src',2],[],e,s,gg)
_(hSND,cUND)
var oVND=_mz(z,'image',['bindtap',520,'class',1,'src',2],[],e,s,gg)
_(hSND,oVND)
_(b9MD,hSND)
_(r,b9MD)
var lWND=_mz(z,'tui-popup',['duration',523,'modeClass',1,'show',2,'styles',3],[],e,s,gg)
var aXND=_mz(z,'view',['catch:tap',527,'class',1],[],e,s,gg)
var tYND=_mz(z,'image',['class',529,'src',1],[],e,s,gg)
_(aXND,tYND)
_(lWND,aXND)
_(r,lWND)
var eZND=_mz(z,'tui-popup',['bindclick',531,'duration',1,'modeClass',2,'show',3,'styles',4],[],e,s,gg)
var b1ND=_n('view')
_rz(z,b1ND,'class',536,e,s,gg)
var o2ND=_n('view')
_rz(z,o2ND,'class',537,e,s,gg)
var x3ND=_n('text')
_rz(z,x3ND,'class',538,e,s,gg)
var o4ND=_oz(z,539,e,s,gg)
_(x3ND,o4ND)
_(o2ND,x3ND)
_(b1ND,o2ND)
var f5ND=_n('view')
_rz(z,f5ND,'class',540,e,s,gg)
var c6ND=_n('text')
_rz(z,c6ND,'class',541,e,s,gg)
var h7ND=_oz(z,542,e,s,gg)
_(c6ND,h7ND)
_(f5ND,c6ND)
_(b1ND,f5ND)
_(eZND,b1ND)
_(r,eZND)
var a2CD=_v()
_(r,a2CD)
if(_oz(z,543,e,s,gg)){a2CD.wxVkey=1
var o8ND=_n('view')
_rz(z,o8ND,'class',544,e,s,gg)
var c9ND=_mz(z,'view',['bindtap',545,'class',1],[],e,s,gg)
var o0ND=_oz(z,547,e,s,gg)
_(c9ND,o0ND)
_(o8ND,c9ND)
var lAOD=_mz(z,'image',['class',548,'mode',1,'src',2],[],e,s,gg)
_(o8ND,lAOD)
var aBOD=_mz(z,'button',['bindtap',551,'class',1],[],e,s,gg)
var tCOD=_oz(z,553,e,s,gg)
_(aBOD,tCOD)
_(o8ND,aBOD)
_(a2CD,o8ND)
}
var eDOD=_mz(z,'canvas',['class',554,'id',1,'type',2],[],e,s,gg)
_(r,eDOD)
cVCD.wxXCkey=1
cVCD.wxXCkey=3
hWCD.wxXCkey=1
oXCD.wxXCkey=1
oXCD.wxXCkey=3
cYCD.wxXCkey=1
cYCD.wxXCkey=3
oZCD.wxXCkey=1
l1CD.wxXCkey=1
l1CD.wxXCkey=3
a2CD.wxXCkey=1
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx_XC_42";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx_XC_42();	if (__vd_version_info__.delayedGwx) __wxAppCode__['pages/word/word.wxml'] = [$gwx_XC_42, './pages/word/word.wxml'];else __wxAppCode__['pages/word/word.wxml'] = $gwx_XC_42( './pages/word/word.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['pages/word/word.wxss']=setCssToHead([[2,"./static/animation.wxss"],".",[1],"container{padding-bottom:",[0,110],"}\n.",[1],"quiz-volume{height:",[0,120],";padding-bottom:",[0,20],"}\n.",[1],"quiz-speak,.",[1],"quiz-volume{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;width:100%;z-index:1}\n.",[1],"quiz-speak{height:",[0,168],";margin-top:",[0,10],"}\n.",[1],"volume-bg{-webkit-align-items:center;align-items:center;background:#5677fc;border-radius:50%;display:-webkit-flex;display:flex;height:",[0,108],";-webkit-justify-content:center;justify-content:center;opacity:.7;width:",[0,108],"}\n.",[1],"audio_icon{height:",[0,64],";margin-left:",[0,20],";width:",[0,64],";z-index:999}\n.",[1],"volume-icon{height:",[0,108],";width:",[0,108],"}\n.",[1],"volume-icon,.",[1],"volume-icon1{margin-left:",[0,40],";margin-right:",[0,40],";z-index:999}\n.",[1],"volume-icon1{height:",[0,120],";width:",[0,120],"}\n.",[1],"quiz-bottom-icon{height:",[0,100],";width:",[0,100],";z-index:99}\n.",[1],"bottom-icon{height:",[0,168],";margin:",[0,12],";width:",[0,168],";z-index:999}\n.",[1],"bottom-icon-shanka{height:",[0,138],";margin:",[0,12],";width:",[0,138],";z-index:999}\n.",[1],"bottom-icon-listen{height:",[0,126],";margin:",[0,12],";width:",[0,126],";z-index:999}\n.",[1],"navi-card{-webkit-align-items:center;align-items:center;background:#fff;border-radius:",[0,8],";box-shadow:0 ",[0,8]," ",[0,20]," 0 rgba(9,36,66,.04);color:#596c8e;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;font-size:",[0,28],";font-weight:400;height:",[0,200],";-webkit-justify-content:center;justify-content:center;line-height:",[0,40],";margin-top:",[0,30],";width:100%}\n.",[1],"navi-icon{height:",[0,88],";margin-bottom:",[0,34],";width:",[0,88],"}\n.",[1],"tui-header-icon{height:32px}\n.",[1],"tui-searchbox{background:#f7f7f7;border-radius:15px;color:#999;font-size:12px;height:30px;margin-left:",[0,20],";margin-right:",[0,30],";overflow:hidden;padding:3px 10px;width:100%}\n.",[1],"tui-icon-box{height:20px!important;width:20px!important}\n.",[1],"tui-banner-swiper{position:relative}\n.",[1],"banner-item{-webkit-flex-direction:column;flex-direction:column}\n.",[1],"banner-item,.",[1],"tui-video__box wx-view{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-video__box wx-view{box-sizing:border-box;font-size:",[0,24],";height:100%;left:0;padding-left:",[0,66],";position:absolute;top:0;width:100%}\n.",[1],"tui-banner-tag{color:#fff;position:fixed;right:0;top:",[0,180],"}\n.",[1],"tui-padding{box-sizing:border-box;padding:0 ",[0,30],"}\n.",[1],"tui-ml-auto{margin-left:auto}\n.",[1],"tui-size{line-height:",[0,28],"}\n.",[1],"tui-gray{color:#999}\nwx-tui-macaron{color:#ff9b6a}\n.",[1],"bg-macaron{background-color:#ff9b6a;color:var(--black)}\n.",[1],"lines-macaron{color:#ff9b6a}\n.",[1],"tui-icon-red{color:#ff201f}\n.",[1],"tui-border-radius{border-bottom-left-radius:",[0,24],";border-bottom-right-radius:",[0,24],";overflow:hidden}\n.",[1],"tui-radius-all{border-radius:",[0,24],";overflow:hidden}\n.",[1],"tui-mtop{margin-top:",[0,26],"}\n.",[1],"tui-pro-detail{box-sizing:border-box;color:#333}\n.",[1],"operation{background:#fff;padding:",[0,20]," 0;top:",[0,20],";width:42%}\n.",[1],"tui-study-title{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;height:",[0,120],";-webkit-justify-content:center;justify-content:center;width:100%}\n.",[1],"tui-new-label-voice{border-radius:12%;right:",[0,2],";top:",[0,2],"}\n.",[1],"tui-new-label-like,.",[1],"tui-new-label-voice{height:",[0,88],";width:",[0,88],"}\n.",[1],"tui-new-label-like,.",[1],"tui-new-label-share,.",[1],"tui-new-label-voice{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;position:absolute}\n.",[1],"tui-new-label-share{bottom:",[0,2],";height:",[0,128],";right:",[0,2],";width:",[0,128],"}\n.",[1],"voice-icon{height:",[0,72],";width:",[0,72],"}\n.",[1],"voice-icon-sm{height:",[0,56],";width:",[0,56],"}\n.",[1],"share-icon{height:",[0,120],";width:",[0,120],"}\n.",[1],"tui-word-title{min-height:",[0,140],"}\n.",[1],"tui-pindu-title,.",[1],"tui-word-title{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;-webkit-justify-content:center;justify-content:center;width:100%}\n.",[1],"tui-pindu-title{margin-top:",[0,20],";min-height:",[0,120],"}\n.",[1],"tui-pro-pricebox{color:#ff201f;display:-webkit-flex;display:flex;font-size:",[0,36],";font-weight:700;-webkit-justify-content:space-between;justify-content:space-between;line-height:",[0,44],"}\n.",[1],"tui-pro-price,.",[1],"tui-pro-pricebox{-webkit-align-items:center;align-items:center}\n.",[1],"tui-price{font-size:",[0,58],"}\n.",[1],"tui-original-price{box-sizing:border-box;font-size:",[0,26],";line-height:",[0,26],";padding:",[0,10]," ",[0,30],"}\n.",[1],"tui-line-through{text-decoration:line-through}\n.",[1],"tui-scale-collection{font-weight:400;line-height:",[0,24],";margin-top:",[0,4],";-webkit-transform:scale(.7);transform:scale(.7);-webkit-transform-origin:center 90%;transform-origin:center 90%}\n.",[1],"tui-word-bottom{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;height:",[0,120],";-webkit-justify-content:center;justify-content:center;width:100%}\n.",[1],"tui-button-bottom{bottom:",[0,0],"}\n.",[1],"tui-button-bottom,.",[1],"tui-button-bottom-shanka,.",[1],"tui-study-bottom{height:",[0,240],"}\n.",[1],"tui-button-bottom,.",[1],"tui-button-bottom-shanka,.",[1],"tui-star-top,.",[1],"tui-study-bottom{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;width:100%;z-index:99}\n.",[1],"tui-star-top{height:",[0,200],"}\n.",[1],"tui-pro-title{padding-top:",[0,20],"}\n.",[1],"tui-share-btn{background:transparent;border:0;border-radius:0;display:block;margin:0;padding:0}\n.",[1],"tui-share-btn::after{border:0}\n.",[1],"tui-share-box{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-share-position{position:absolute;right:0;top:",[0,30],"}\n.",[1],"tui-share-text{padding-left:",[0,8],"}\n.",[1],"tui-sub-title{font-size:",[0,26],";line-height:",[0,36],";padding:",[0,20]," 0}\n.",[1],"tui-sale-info{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between;padding-top:",[0,20],"}\n.",[1],"tui-discount-box{background:#fff}\n.",[1],"tui-list-cell{font-size:",[0,26],";line-height:",[0,26],";padding:",[0,30],"}\n.",[1],"tui-top40{top:",[0,40],"!important}\n.",[1],"tui-bold{font-weight:700}\n.",[1],"tui-last::after{border-bottom:0!important}\n.",[1],"tui-flex-center{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-cell-title{-webkit-flex-shrink:0;flex-shrink:0;padding-right:",[0,30],";width:",[0,66],"}\n.",[1],"tui-promotion-box{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;padding:",[0,10]," 0;width:80%}\n.",[1],"tui-promotion-box wx-text{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;width:70%}\n.",[1],"tui-basic-info{background:#fff}\n.",[1],"tui-addr-box{width:76%}\n.",[1],"tui-addr-item{line-height:",[0,34],";padding:",[0,10],"}\n.",[1],"tui-guarantee{font-size:",[0,24],";margin-bottom:",[0,20],";margin-top:",[0,20],";padding:",[0,20]," ",[0,30]," ",[0,30],"}\n.",[1],"tui-guarantee-item{color:#999;padding-right:",[0,30],";padding-top:",[0,10],"}\n.",[1],"tui-pl{padding-left:",[0,4],"}\n.",[1],"tui-cmt-box{background:#fff}\n.",[1],"tui-between{-webkit-justify-content:space-between!important;justify-content:space-between!important}\n.",[1],"tui-cmt-all{color:#ff201f;padding-right:",[0,8],"}\n.",[1],"tui-cmt-content{font-size:",[0,26],"}\n.",[1],"tui-cmt-user{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-acatar{border-radius:",[0,30],";display:block;height:",[0,60],";margin-right:",[0,16],";width:",[0,60],"}\n.",[1],"tui-cmt{padding:",[0,20]," 0}\n.",[1],"tui-attr{color:#999;font-size:",[0,24],";padding:",[0,6]," 0}\n.",[1],"tui-cmt-btn{-webkit-align-items:center;align-items:center;box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;padding:",[0,50]," 0 ",[0,30],"}\n.",[1],"tui-nomore-box{padding-top:",[0,10],"}\n.",[1],"tui-product-img{display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;-webkit-transform:translateZ(0);transform:translateZ(0)}\n.",[1],"tui-product-img wx-image{display:block;width:100%}\n.",[1],"tui-col-7{width:58.33333333%}\n.",[1],"tui-col-5{width:41.66666667%}\n.",[1],"tui-operation::before{border-top:",[0,1]," solid #eaeef1;content:\x22\x22;left:0;position:absolute;right:0;top:0;-webkit-transform:scaleY(.5);transform:scaleY(.5)}\n.",[1],"tui-operation-item,.",[1],"tui-operation-left{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-operation-item{-webkit-flex:1;flex:1;-webkit-flex-direction:column;flex-direction:column;-webkit-justify-content:center;justify-content:center;position:relative}\n.",[1],"tui-operation-text{color:#333;font-size:",[0,22],"}\n.",[1],"tui-opacity{opacity:.5}\n.",[1],"tui-scale-small{-webkit-transform:scale(.9);transform:scale(.9);-webkit-transform-origin:center center;transform-origin:center center}\n.",[1],"tui-flex{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between}\n.",[1],"tui-level-title{word-wrap:break-word;font-size:",[0,32],";font-weight:500;padding:0 ",[0,10],";word-break:break-all}\n.",[1],"tui-volume{top:",[0,280],"}\n.",[1],"tui-ask,.",[1],"tui-volume{position:fixed;right:",[0,10],"}\n.",[1],"tui-ask{top:",[0,400],"}\n.",[1],"operation{border-radius:",[0,40],";height:",[0,60],";-webkit-justify-content:center;justify-content:center;opacity:.7;position:fixed;top:",[0,30],"}\n.",[1],"operation,.",[1],"tui-operation-titbox{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-operation-titbox{box-sizing:border-box;font-size:",[0,32],";padding:",[0,10]," ",[0,30],";position:relative}\n.",[1],"tui-product-box{-webkit-align-items:flex-end;align-items:flex-end;font-size:",[0,24],";padding-bottom:",[0,30],"}\n.",[1],"tui-item-box,.",[1],"tui-product-box{display:-webkit-flex;display:flex}\n.",[1],"tui-item-box{-webkit-align-items:center;align-items:center;width:100%}\n.",[1],"tui-msg-pic{border-radius:10%;display:block;-webkit-flex-shrink:0;flex-shrink:0;height:",[0,100],";margin-right:",[0,24],";width:",[0,100],"}\n.",[1],"tui-list-cell_name{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;padding-left:",[0,20],"}\n.",[1],"tui-attr-box{padding:",[0,20]," 0}\n.",[1],"tui-attr-item{background:#f7f7f7;margin-bottom:",[0,20],";margin-right:",[0,20],";min-width:",[0,200],";padding:0 ",[0,26],"}\n.",[1],"tui-attr-active1{color:#e41f19}\n.",[1],"tui-attr-active1,.",[1],"tui-attr-active2{background:#fcedea!important;font-weight:700;position:relative}\n.",[1],"tui-attr-active2{color:#191ce4}\n.",[1],"tui-attr-active3{background:#fcedea!important;color:#19e456;font-weight:700;position:relative}\n.",[1],"tui-content{background-color:#fff;color:#555;font-size:",[0,32],";padding:",[0,20]," ",[0,30]," ",[0,20]," ",[0,70],"}\n.",[1],"tui-tabbar{background-color:#fff;height:",[0,150],";z-index:9999}\n.",[1],"tui-tabbar::before{border-top:",[0,1]," solid #d2d2d2;content:\x22\x22;left:0;position:absolute;top:0;-webkit-transform:scaleY(.5);transform:scaleY(.5);width:100%}\n.",[1],"tui-tabbar-item{-webkit-align-items:center;align-items:center;color:#aaa;display:-webkit-flex;display:flex;-webkit-flex:1;flex:1;-webkit-flex-direction:column;flex-direction:column;font-size:",[0,28],";height:",[0,90],";-webkit-justify-content:space-between;justify-content:space-between;width:25%}\n.",[1],"tui-ptop-4{padding-top:",[0,4],"}\n.",[1],"tui-scale{font-weight:700;line-height:",[0,30],";-webkit-transform:scale(.8);transform:scale(.8);-webkit-transform-origin:center 100%;transform-origin:center 100%}\n.",[1],"tui-item-active{color:#00c0fb!important}\n.",[1],"tui-default{padding:",[0,20]," ",[0,30],"}\n.",[1],"describe{color:#666;font-size:",[0,24],"}\n.",[1],"tui-tips-img{height:300px;width:260px}\n.",[1],"tui-modal-custom-text{padding:",[0,30]," 0 ",[0,20],"}\n.",[1],"tui-flex-box{-webkit-align-items:flex-start;align-items:flex-start;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;-webkit-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:flex-start;justify-content:flex-start;margin-bottom:",[0,26],";margin-left:",[0,30],";width:100%}\n.",[1],"tui-grid-label{color:#333;display:block;font-size:",[0,28],";font-weight:400;margin-top:",[0,10],";overflow:hidden;text-align:center;text-overflow:ellipsis;white-space:nowrap}\n.",[1],"tui-grid-img{text-align:center;vertical-align:middle}\n.",[1],"collect_tips{-webkit-align-items:center;align-items:center;color:#3f3f3f;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;font-size:",[0,26],";-webkit-justify-content:center;justify-content:center;padding-top:",[0,30],";width:100%}\n.",[1],"quiz_img{height:",[0,333],";width:",[0,227],"}\n.",[1],"icon-switch{height:",[0,120],";width:",[0,120],"}\n.",[1],"tui-goods-center{margin-left:",[0,20],";padding:",[0,10],"}\n.",[1],"tui-goods__list{padding-left:",[0,30],"}\n.",[1],"tui-goods__item{border-radius:",[0,10],";height:",[0,260],";margin-right:",[0,30],";width:",[0,210],"}\n.",[1],"tui-goods__imgbox{height:",[0,190],";width:",[0,190],"}\n.",[1],"tui-goods__img{max-height:",[0,190],";max-width:",[0,190],"}\n.",[1],"tui-pri__box{-webkit-align-items:center;align-items:center;-webkit-justify-content:center;justify-content:center;max-width:",[0,180],"}\n.",[1],"tui-pri__box,.",[1],"tui-sale-pri{display:-webkit-flex;display:flex}\n.",[1],"tui-sale-pri{-webkit-align-items:flex-end;align-items:flex-end;box-sizing:border-box;color:#999;overflow:hidden;padding:",[0,10]," 0;text-overflow:ellipsis;white-space:nowrap}\n.",[1],"tui-sale-pri,.",[1],"tui-size-sm{font-size:",[0,30],";line-height:",[0,30],"}\n.",[1],"tui-size-sm{-webkit-transform:scale(.8);transform:scale(.8);-webkit-transform-origin:0 50%;transform-origin:0 50%}\n.",[1],"tui-original__pri{-webkit-align-items:center;align-items:center;color:#999;display:-webkit-flex;display:flex;font-size:",[0,24],";-webkit-justify-content:center;justify-content:center;line-height:",[0,24],";text-decoration:line-through;-webkit-transform:scale(.8);transform:scale(.8);-webkit-transform-origin:center 10%;transform-origin:center 10%}\n.",[1],"tui-page__hd{box-sizing:border-box;padding:",[0,20],";width:100%}\n.",[1],"tui-page__bd{margin-top:20px;padding-bottom:40px}\n.",[1],"tui-page__title{font-size:20px;font-weight:400;text-align:left}\n.",[1],"tui-page__desc{color:#888;font-size:14px;margin-top:16px;text-align:left}\n.",[1],"tui-section__title{padding:",[0,20]," 15px}\n.",[1],"tui-page__spacing .",[1],"thorui-radio{margin-right:",[0,30],"}\n.",[1],"tui-list-view{margin-top:",[0,30],"}\n.",[1],"tui-list-view .",[1],"thorui-radio{height:100%;width:100%}\n.",[1],"tui-tabs{-webkit-align-items:center;align-items:center;background-color:#fafafa;-webkit-flex:1;flex:1;-webkit-justify-content:center;justify-content:center;overflow:hidden}\n.",[1],"tui-scroll-h,.",[1],"tui-tabs{display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row}\n.",[1],"tui-scroll-h{background-color:#fff;height:",[0,80],";white-space:nowrap;width:100%}\n.",[1],"tui-line-h{position:relative}\n.",[1],"tui-line-h::after{border-bottom:",[0,1]," solid #eaeef1;bottom:0;content:\x22\x22;left:0;position:absolute;right:0;-webkit-transform:scaleY(.5);transform:scaleY(.5);-webkit-transform-origin:0 100%;transform-origin:0 100%}\n.",[1],"tui-tab-item{display:inline-block;padding:0 ",[0,20],"}\n.",[1],"tui-tab-item,.",[1],"tui-tab-item-title{-webkit-flex-wrap:nowrap;flex-wrap:nowrap}\n.",[1],"tui-tab-item-title{color:#555;font-size:",[0,28],";height:",[0,80],";line-height:",[0,80],";white-space:nowrap}\n.",[1],"tui-tab-item-title-active{border-bottom:",[0,6]," solid #5677fc;color:#5677fc;font-size:",[0,30],";font-weight:700}\n.",[1],"tui-tab-item-title-active,.",[1],"tui-title{box-sizing:border-box;text-align:center}\n.",[1],"tui-title{color:#888;font-size:",[0,28],";padding:",[0,10]," 0;width:100%}\n.",[1],"tui-charts-box{padding:0 ",[0,30]," 0 ",[0,50],"}\n.",[1],"tui-charts-box,.",[1],"tui-charts-pie{box-sizing:border-box;width:100%}\n.",[1],"tui-charts-pie{display:-webkit-flex;display:flex;-webkit-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;padding:0 ",[0,30],"}\n.",[1],"tui-mtop{margin-top:",[0,120],"}\n.",[1],"tui-legend__box{display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;-webkit-flex-wrap:wrap;flex-wrap:wrap}\n.",[1],"tui-legend__item{-webkit-align-items:center;align-items:center;box-sizing:border-box;display:-webkit-flex;display:flex;font-size:",[0,28],";margin-bottom:",[0,20],";margin-left:",[0,24],";padding-left:",[0,30],"}\n.",[1],"tui-legend__circle{border-radius:50%;-webkit-flex-shrink:0;flex-shrink:0;height:",[0,20],";margin-right:",[0,8],";width:",[0,20],"}\n.",[1],"content{-webkit-box-orient:vertical;-webkit-line-clamp:5;background-color:#fff;display:-webkit-flex;display:flex;display:-webkit-box;font-size:",[0,26],";margin-top:",[0,18],";overflow:hidden;text-overflow:ellipsis}\n.",[1],"tab-content{-webkit-align-items:center;align-items:center;color:#8c98ae;display:-webkit-flex;display:flex;font-size:",[0,28],";height:100%;-webkit-justify-content:center;justify-content:center;min-height:",[0,140],"}\n.",[1],"tui-history-content{margin-top:",[0,110],"}\n.",[1],"lin-card{margin-top:",[0,20],"}\n.",[1],"tui-container{box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;padding-bottom:env(safe-area-inset-bottom)}\n.",[1],"tui-header-screen{background:#fff;box-sizing:border-box;width:100%;z-index:1000}\n.",[1],"tui-history-content{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-wrap:wrap;flex-wrap:wrap;margin-left:",[0,28],"}\n.",[1],"tui-classify-box{top:",[0,100],"}\n.",[1],"tui-classify-item{width:25%}\n.",[1],"tui-classify-img{height:",[0,128],";width:",[0,128],"}\n.",[1],"tui-news-flex{display:-webkit-flex;display:flex;width:100%}\n.",[1],"tui-flex-column{-webkit-flex-direction:column!important;flex-direction:column!important}\n.",[1],"tui-flex-between{-webkit-justify-content:space-between!important;justify-content:space-between!important}\n.",[1],"tui-news-cell{padding:",[0,20]," ",[0,30],"}\n.",[1],"tui-news-cell,.",[1],"tui-news-tbox{display:-webkit-flex;display:flex}\n.",[1],"tui-news-tbox{box-sizing:border-box;-webkit-flex:1;flex:1;width:100%}\n.",[1],"tui-news-picbox{display:-webkit-flex;display:flex;position:relative}\n.",[1],"tui-w220{width:",[0,220],"}\n.",[1],"tui-h165{height:",[0,165],"}\n.",[1],"tui-block{display:block}\n.",[1],"tui-w-full{width:100%}\n.",[1],"tui-one-third{width:33%}\n.",[1],"tui-news-title{word-wrap:break-word;-webkit-box-orient:vertical;-webkit-line-clamp:2;box-sizing:border-box;display:-webkit-box;font-size:",[0,34],";overflow:hidden;text-overflow:ellipsis;width:100%;word-break:break-all}\n.",[1],"tui-pl-20{padding-left:",[0,20],"}\n.",[1],"tui-pt20{padding-top:",[0,20],"}\n.",[1],"tui-sub-box{-webkit-align-items:center;align-items:center;box-sizing:border-box;color:#999;display:-webkit-flex;display:flex;line-height:",[0,24],"}\n.",[1],"tui-sub-source{font-size:",[0,26],"}\n.",[1],"tui-sub-cmt{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;font-size:",[0,24],";line-height:",[0,24],"}\n.",[1],"tui-scale{-webkit-transform:scale(.6);transform:scale(.6);-webkit-transform-origin:center center;transform-origin:center center}\n.",[1],"tui-btm-badge{background:rgba(0,0,0,.6);bottom:0;color:#fff;font-size:",[0,24],";padding:",[0,2]," ",[0,12],";position:absolute;right:0;-webkit-transform:scale(.8);transform:scale(.8);-webkit-transform-origin:100% 100%;transform-origin:100% 100%;z-index:20}\n.",[1],"tui-video{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;left:50%;position:absolute;top:50%;-webkit-transform:translate(-50%,-50%);transform:translate(-50%,-50%);-webkit-transform-origin:0 0;transform-origin:0 0;z-index:10}\n.",[1],"tui-icon{background:rgba(0,0,0,.5);border-radius:50%;padding:",[0,26],"}\n.",[1],"tui-searchbox{padding:",[0,30]," 0}\n.",[1],"tui-search-input,.",[1],"tui-searchbox{-webkit-align-items:center;align-items:center;box-sizing:border-box;display:-webkit-flex;display:flex}\n.",[1],"tui-search-input{background:#f2f2f2;border-radius:",[0,35],";-webkit-flex-wrap:nowrap;flex-wrap:nowrap;height:",[0,66],";padding:",[0,30],";position:fixed;width:100%}\n.",[1],"tui-input{color:#333;-webkit-flex:1;flex:1;font-size:",[0,28],";padding:0 ",[0,16],"}\n.",[1],"tui-input-plholder{color:#b2b2b2;font-size:",[0,28],"}\n.",[1],"tui-product-box{box-sizing:border-box;margin-top:",[0,20],";padding:0 ",[0,25],";position:fixed}\n.",[1],"tui-product-container{margin-right:2%}\n.",[1],"tui-product-container:last-child{margin-right:0}\n.",[1],"tui-pro-item{margin-bottom:5%}\n.",[1],"tui-pro-img{width:100%}\n.",[1],"tui-flex-2{background:#fdfdfd;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;-webkit-flex-wrap:wrap;flex-wrap:wrap;font-size:",[0,22],"}\n.",[1],"tui-flex-item{color:#999;padding-right:",[0,10],";padding-top:",[0,10],"}\n.",[1],"tui-factory-price{font-size:",[0,22],"}\n.",[1],"tui-pro-price{-webkit-align-items:flex-end;align-items:flex-end;display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between;padding-bottom:",[0,10],";padding-left:",[0,10],"}\n.",[1],"tui-pro-pay{padding-right:",[0,10],"}\n.",[1],"tui-menu-box{box-sizing:border-box}\n.",[1],"tui-menu-header{-webkit-align-items:center;align-items:center;font-size:",[0,34],";height:32px}\n.",[1],"tui-menu-header,.",[1],"tui-menu-itembox{color:#fff;display:-webkit-flex;display:flex}\n.",[1],"tui-menu-itembox{box-sizing:border-box;-webkit-flex-wrap:wrap;flex-wrap:wrap;font-size:",[0,26],";padding:",[0,40]," ",[0,10]," 0}\n.",[1],"tui-menu-item{-webkit-align-items:center;align-items:center;background:rgba(0,0,0,.4);border-radius:",[0,24],";display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;height:",[0,160],";-webkit-justify-content:center;justify-content:center;margin-bottom:4%;margin-right:4%;width:22%}\n.",[1],"tui-menu-item:nth-of-type(4n){margin-right:0}\n.",[1],"tui-badge-box{position:relative}\n.",[1],"tui-badge-box .",[1],"tui-badge-class{position:absolute;right:-8px;top:-8px}\n.",[1],"tui-msg-badge{top:-10px}\n.",[1],"tui-icon-up_box{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;width:100%}\n.",[1],"tui-menu-text{padding-top:",[0,12],"}\n.",[1],"tui-opcity .",[1],"tui-badge-box,.",[1],"tui-opcity .",[1],"tui-menu-text{opacity:.5;transition:opacity .2s ease-in-out}\nbody{background-color:#f7f7f7}\n.",[1],"container{padding-bottom:env(safe-area-inset-bottom)}\n.",[1],"tui-header-box{left:0;position:fixed;top:0;width:100%;z-index:995}\n.",[1],"tui-header{font-size:18px;font-weight:500;height:32px;line-height:18px}\n.",[1],"tui-header-icon{-webkit-align-items:flex-start;align-items:flex-start;display:-webkit-flex;display:flex;height:50px;-webkit-justify-content:space-between;justify-content:space-between;left:10px;position:fixed;top:0;-webkit-transform:translateZ(0);transform:translateZ(0);width:",[0,160],";z-index:9999}\n.",[1],"tui-header-icon .",[1],"tui-badge{background:#e41f19!important;position:absolute;right:-4px}\n.",[1],"tui-icon-ml{margin-left:",[0,20],"}\n.",[1],"tui-icon-box{border-radius:50%;height:36px!important;-webkit-justify-content:center;justify-content:center;padding:6px!important;position:relative;width:36px!important}\n.",[1],"tui-content-box,.",[1],"tui-icon-box{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-content-box{box-sizing:border-box;height:44px;padding:0 ",[0,30],";width:100%}\n.",[1],"tui-avatar-box{-webkit-align-items:center;align-items:center;border:1px solid #eaeef1;border-radius:50%;display:-webkit-flex;display:flex;-webkit-flex-shrink:0;flex-shrink:0;height:30px;-webkit-justify-content:center;justify-content:center;width:30px}\n.",[1],"tui-avatar{border-radius:50%;height:28px;width:28px}\n.",[1],"tui-search-box{-webkit-align-items:center;align-items:center;background-color:#f1f1f1;border-radius:18px;box-sizing:border-box;color:#bfbfbf;display:-webkit-flex;display:flex;font-size:14px;height:32px;margin:0 ",[0,28],";padding:0 12px;width:100%}\n.",[1],"tui-word-box{height:90%}\n.",[1],"tui-banner-box,.",[1],"tui-word-box{box-sizing:border-box;width:100%;z-index:99}\n.",[1],"tui-banner-box{height:60vh}\n.",[1],"tui-banner-box-fuxi,.",[1],"word_list_area{box-sizing:border-box;height:70vh;width:100%;z-index:99}\n.",[1],"tui-card,.",[1],"tui-card-word{position:relative}\n.",[1],"tui-card-title{bottom:",[0,20],";box-sizing:border-box;color:#fff;font-size:",[0,48],";font-weight:500;padding:",[0,20]," ",[0,30],";position:absolute}\n.",[1],"tui-pro-titbox{-webkit-flex-direction:row;flex-direction:row;-webkit-flex-wrap:wrap;flex-wrap:wrap;font-size:",[0,50],";font-weight:500;padding:",[0,10]," ",[0,14],"}\n.",[1],"tui-pro-titbox,.",[1],"tui-pro-titbox-study-name{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-pro-titbox-study-name{font-size:",[0,88],"}\n.",[1],"tui-pro-titbox-study-name.",[1],"completed{-webkit-animation:celebrate 1s ease-in-out;animation:celebrate 1s ease-in-out}\n.",[1],"tui-pro-titbox-study-prompt{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;font-size:",[0,36],"}\n.",[1],"tui-logo-small{height:",[0,60],";width:",[0,60],"}\n.",[1],"word-titbox-name{font-size:",[0,100],"}\n.",[1],"word-titbox-name,.",[1],"word-titbox-yinbiao{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;font-weight:500;-webkit-justify-content:center;justify-content:center}\n.",[1],"word-titbox-yinbiao{-webkit-flex-direction:row;flex-direction:row;font-size:",[0,50],"}\n.",[1],"tui-banner-item{box-sizing:border-box;-webkit-flex-direction:column;flex-direction:column}\n.",[1],"tui-banner-item,.",[1],"tui-word-image{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center}\n.",[1],"tui-word-image{border-radius:",[0,12],";height:",[0,580],";top:0;width:100%}\n.",[1],"tui-slide-image-word{height:90%}\n.",[1],"tui-slide-image,.",[1],"tui-slide-image-word{border-radius:",[0,18],";display:block;transition:all .05s linear;width:100%}\n.",[1],"tui-slide-image{height:60vh}\n.",[1],"prompt-text,.",[1],"tui-card-img{-webkit-align-items:center;align-items:center}\n.",[1],"tui-card-img{display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;position:relative}\n.",[1],"tui-pindu-image{border-radius:",[0,12],";display:block;height:40vh;transition:all .05s linear}\n.",[1],"tui-banner-scale{-webkit-transform:scaleY(.9);transform:scaleY(.9);-webkit-transform-origin:center center;transform-origin:center center}\n.",[1],"img_title{bottom:0;position:relative}\n.",[1],"tui-goods__list{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-goods__item{background-color:#fff;border-radius:",[0,6],";-webkit-flex-direction:column;flex-direction:column;-webkit-flex-shrink:0;flex-shrink:0;height:",[0,330],";margin-right:",[0,18],";width:",[0,330],"}\n.",[1],"tui-goods__imgbox,.",[1],"tui-goods__item{-webkit-align-items:center;align-items:center;box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center}\n.",[1],"tui-goods__imgbox{height:",[0,300],";width:",[0,300],"}\n.",[1],"tui-goods__img{display:block;max-height:",[0,300],";max-width:",[0,300],"}\n.",[1],"tui-rolling-news{-webkit-align-items:center;align-items:center;background:#fff;box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-flex-wrap:nowrap;flex-wrap:nowrap;-webkit-justify-content:center;justify-content:center;padding:0 ",[0,30],";width:100%}\n.",[1],"tui-rolling-news::after{left:0}\n.",[1],"tui-swiper{-webkit-flex:1;flex:1;font-size:",[0,28],";height:",[0,80],";margin-left:",[0,8],"}\n.",[1],"tui-swiper-item{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-news-item{color:#555;line-height:",[0,28],";overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n.",[1],"tui-classify-box{-webkit-align-items:center;align-items:center;background-color:#fff;display:-webkit-flex;display:flex;-webkit-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:space-between;justify-content:space-between;padding:",[0,28]," 0;width:100%}\n.",[1],"tui-classify-item{text-align:center;width:20%}\n.",[1],"tui-classify-img{height:",[0,88],";width:",[0,88],"}\n.",[1],"tui-classify-name{color:#555;font-size:",[0,26],";line-height:",[0,26],";padding-top:",[0,8],";white-space:nowrap}\n.",[1],"tui-spike-box{background:#fff;bottom:",[0,60],";margin-top:",[0,20],"}\n.",[1],"tui-msg-item{display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;-webkit-justify-content:space-between;justify-content:space-between;max-width:",[0,500],";min-height:",[0,80],";overflow:hidden}\n.",[1],"tui-msg-name{color:#262b3a;font-size:",[0,34],"}\n.",[1],"tui-msg-content,.",[1],"tui-msg-name{line-height:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n.",[1],"tui-msg-content{color:#9397a4;font-size:",[0,26],"}\n.",[1],"tui-msg-right{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;height:",[0,100],";-webkit-justify-content:center;justify-content:center;margin-left:auto;text-align:right;width:20%}\n.",[1],"tui-msg-time{color:#9397a4;font-size:",[0,24],";line-height:",[0,24],";width:100%}\n.",[1],"tui-chat-item,.",[1],"tui-msg-box{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-chat-item{-webkit-justify-content:space-between;justify-content:space-between;width:100%}\n.",[1],"tui-spike-title{box-sizing:border-box;color:#333;font-size:",[0,30],";font-weight:700;padding:",[0,20]," ",[0,30],"}\n.",[1],"tui-spike-title::after{left:0}\n.",[1],"tui-spike-swiper{min-height:",[0,880],"}\n.",[1],"tui-pro-title{padding:0 ",[0,150]," 0 ",[0,10],"}\n.",[1],"tui-curtask-title,.",[1],"tui-pro-title{font-size:",[0,36],";font-weight:500;position:relative}\n.",[1],"tui-curtask-title{padding:0 ",[0,30],"}\n.",[1],"tui-pro-btmbox{-webkit-justify-content:space-between;justify-content:space-between;width:100%}\n.",[1],"tui-countdown,.",[1],"tui-pro-btmbox{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"tui-countdown-text{color:#555;font-size:",[0,24],";line-height:",[0,24],";padding:0 ",[0,8],"}\n.",[1],"tui-collection{-webkit-align-items:center;align-items:center;color:#333;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;height:",[0,44],";-webkit-justify-content:center;justify-content:center}\n.",[1],"tui-size{font-size:",[0,24],";line-height:",[0,24],"}\n.",[1],"tui-ml-auto{position:absolute;right:",[0,50],"}\n.",[1],"list-icon{bottom:",[0,180],";height:",[0,120],";left:",[0,80],";position:fixed;width:",[0,120],"}\n.",[1],"tui-popup-class{border-top-left-radius:",[0,24],";border-top-right-radius:",[0,24],";padding-bottom:env(safe-area-inset-bottom)}\n.",[1],"tui-popup-box{padding:",[0,30]," 0;position:relative}\n.",[1],"tui-popup-btn{bottom:0;left:0;position:absolute;width:100%}\n.",[1],"tui-popup-img{border-radius:",[0,24],";display:block;height:",[0,200],";width:",[0,200],"}\n.",[1],"tui-popup-price{padding-bottom:",[0,8],";padding-left:",[0,20],"}\n.",[1],"tui-amount{color:#ff201f;font-size:",[0,36],"}\n.",[1],"tui-number{color:#999;font-size:",[0,24],";line-height:",[0,24],";padding-top:",[0,12],"}\n.",[1],"tui-popup-scroll{font-size:",[0,26],";height:",[0,780],"}\n.",[1],"tui-tips-scroll{font-size:",[0,26],";height:",[0,620],"}\n.",[1],"tui-scrollview-box{box-sizing:border-box;padding:0 ",[0,30]," ",[0,60],"}\n.",[1],"tui-attr-title{color:#333;padding:",[0,10]," 0}\n.",[1],"tui-product-list{box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;-webkit-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:space-between;justify-content:space-between}\n.",[1],"tui-pro-item{margin-bottom:4%}\n.",[1],"tui-attr-active{background:#fcedea!important;color:#e41f19;font-weight:700;position:relative}\n.",[1],"tui-attr-active::after{border:",[0,1]," solid #e41f19;border-radius:",[0,40],";content:\x22\x22;height:100%;left:0;position:absolute;top:0;width:100%}\n.",[1],"tui-number-box{-webkit-justify-content:space-between;justify-content:space-between;padding:",[0,20]," 0 ",[0,30],"}\n.",[1],"tui-list-cell,.",[1],"tui-number-box{-webkit-align-items:center;align-items:center;box-sizing:border-box;display:-webkit-flex;display:flex}\n.",[1],"tui-list-cell{font-size:",[0,32],";line-height:",[0,64],";padding:",[0,36]," ",[0,30],";position:relative;width:100%}\n.",[1],"tui-product-container{-webkit-flex:1;flex:1;margin-right:",[0,10],"}\n.",[1],"tui-product-container:last-child{margin-bottom:",[0,100],"}\n.",[1],"tui-pro-item{background:#fff;border-radius:",[0,12],";box-sizing:border-box;margin-bottom:",[0,10],";overflow:hidden;transition:all .15s ease-in-out;width:100%}\n.",[1],"tui-flex-list{display:-webkit-flex;display:flex;margin-bottom:",[0,1],"!important}\n.",[1],"tui-pro-img{border-radius:",[0,10],";display:block;width:92%}\n.",[1],"tui-proimg-list{border-radius:",[0,12],";-webkit-flex-shrink:0;flex-shrink:0;height:",[0,220],"!important;width:",[0,220],"}\n.",[1],"tui-pro-content{box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;-webkit-justify-content:space-between;justify-content:space-between;padding:",[0,20],"}\n.",[1],"tui-pro-tit{-webkit-box-orient:vertical;-webkit-line-clamp:2;color:#2e2e2e;display:-webkit-box;font-size:",[0,26],";overflow:hidden;text-overflow:ellipsis;word-break:break-all}\n.",[1],"tui-pro-price{padding-top:",[0,18],"}\n.",[1],"tui-sale-price{color:#e41f19;font-size:",[0,34],";font-weight:500}\n.",[1],"tui-factory-price{color:#a0a0a0;font-size:",[0,24],";padding-left:",[0,12],";text-decoration:line-through}\n.",[1],"tui-pro-pay{color:#656565;font-size:",[0,24],";padding-top:",[0,10],"}\n.",[1],"tui-tabbar{-webkit-align-items:center;align-items:center;background:#fff;bottom:0;box-sizing:border-box;display:-webkit-flex;display:flex;height:",[0,160],";-webkit-justify-content:space-between;justify-content:space-between;left:0;padding:0 ",[0,30],";position:fixed;width:100%;z-index:99999}\n.",[1],"png{height:",[0,48],";width:",[0,48],"}\n.",[1],"tui-right{position:absolute;right:",[0,30],";top:",[0,30],"}\n.",[1],"tui-operation{-webkit-align-items:center;align-items:center;background:hsla(0,0%,100%,.98);bottom:0;display:-webkit-flex;display:flex;height:",[0,100],";-webkit-justify-content:space-between;justify-content:space-between;left:0;padding-bottom:env(safe-area-inset-bottom);position:fixed;width:100%;z-index:10}\n.",[1],"tui-operation-right{height:",[0,100],";padding-top:0}\n.",[1],"tui-right-flex{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center}\n.",[1],"tui-flex-1{-webkit-flex:1;flex:1;padding:",[0,16],"}\n.",[1],"tui-safearea-bottom{height:env(safe-area-inset-bottom);width:100%}\n.",[1],"tui-order-list{box-sizing:border-box;padding:0 ",[0,25],";width:100%}\n.",[1],"tui-order-item{border-radius:",[0,12],";box-shadow:0 ",[0,5]," ",[0,10]," 0 rgba(0,0,0,.06);margin-top:",[0,30],";overflow:hidden}\n.",[1],"tui-goods-item{box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between;padding:",[0,20],";width:100%}\n.",[1],"tui-goods-img{display:block;-webkit-flex-shrink:0;flex-shrink:0;height:",[0,180],";width:",[0,180],"}\n.",[1],"tui-goods-center{box-sizing:border-box;-webkit-flex:1;flex:1;padding:",[0,30]," ",[0,10],"}\n.",[1],"tui-goods-name{-webkit-box-orient:vertical;-webkit-line-clamp:2;display:-webkit-box;font-size:",[0,32],";line-height:",[0,42],";overflow:hidden;text-overflow:ellipsis;word-break:break-all}\n.",[1],"tui-header{-webkit-align-items:center;align-items:center;background-color:#fff;border-top-left-radius:",[0,20],";border-top-right-radius:",[0,20],";box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;overflow:hidden;padding:",[0,20],";position:relative;width:100%}\n.",[1],"tui-icon-close{position:absolute;right:",[0,30],";top:50%;-webkit-transform:translateY(-50%);transform:translateY(-50%)}\n.",[1],"tui-scroll-box{box-sizing:border-box;color:#fff;font-size:",[0,30],";height:100%;position:relative;width:100%;word-break:break-all;z-index:99}\n.",[1],"tui-drop-item{box-sizing:border-box;color:#333;display:inline-block;font-size:",[0,28],";height:",[0,80],";padding:",[0,20]," ",[0,40],";width:50%}\n.",[1],"tui-drop-btnbox{bottom:0;box-sizing:border-box;display:-webkit-flex;display:flex;height:",[0,100],";left:0;position:absolute;width:100%}\n.",[1],"tui-drop-btn{border:0;border-radius:0!important;font-size:",[0,32],"!important;height:",[0,100],";line-height:",[0,100],";text-align:center;width:50%!important}\n.",[1],"tips{background:#fff;color:#555;font-size:",[0,24],";line-height:",[0,42],";padding:",[0,50]," ",[0,34],";position:relative}\n.",[1],"tips::before{border-top:",[0,1]," solid #eaeef1;content:\x22\x22;left:0;position:absolute;right:0;top:0;-webkit-transform:scaleY(.5);transform:scaleY(.5)}\n.",[1],"sticky-item{background-color:#fafafa;box-sizing:border-box;height:",[0,104],";-webkit-justify-content:space-between;justify-content:space-between;padding:",[0,20]," ",[0,30],";width:100%}\n.",[1],"date,.",[1],"sticky-item{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"date{background-color:#ff9b6a;border-radius:",[0,25],";font-size:",[0,28],";height:",[0,54],";-webkit-justify-content:center;justify-content:center;padding:0 ",[0,28],";position:relative}\n.",[1],"date::after{border:",[0,1]," solid #eaeef1;border-radius:",[0,60],";content:\x22\x22;height:200%;left:0;position:absolute;top:0;-webkit-transform:scale(.5);transform:scale(.5);-webkit-transform-origin:0 0;transform-origin:0 0;width:200%}\n.",[1],"amount{color:#7a7a7a;font-size:",[0,24],";text-align:right}\n.",[1],"list-view{overflow:hidden;position:relative;width:100%}\n.",[1],"list-view::after{border-top:",[0,1]," solid #eaeef1;content:\x22\x22;left:0;position:absolute;right:0;top:0;-webkit-transform:scaleY(.5);transform:scaleY(.5)}\n.",[1],"tui-list-item{-webkit-align-items:flex-start;align-items:flex-start;background-color:#fff;box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between;padding:",[0,30]," ",[0,28],";width:100%}\n.",[1],"tui-list-item::after{left:",[0,120],"}\n.",[1],"item-last::after{left:0!important}\n.",[1],"content-box{-webkit-align-items:flex-start;align-items:flex-start;display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between}\n.",[1],"logo{-webkit-flex-grow:1;flex-grow:1;height:",[0,60],";width:",[0,60],"}\n.",[1],"des-box{box-sizing:border-box;color:#333;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;font-size:",[0,24],";-webkit-justify-content:space-between;justify-content:space-between;min-height:",[0,130],";padding-left:",[0,28],";vertical-align:top}\n.",[1],"tit{font-size:",[0,32],";max-width:",[0,420],";overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n.",[1],"time{color:#888}\n.",[1],"money{color:#000;font-size:",[0,38],";font-weight:500;overflow:hidden;padding-left:",[0,20],";text-overflow:ellipsis;white-space:nowrap}\n.",[1],"add{color:#5677fc!important}\n.",[1],"tui-color-primary{color:#5677fc}\n.",[1],"tui-page__spacing{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;padding:",[0,40],"}\n.",[1],"thorui-loading__2 wx-view{-webkit-animation:tui_ani 1.4s ease-in-out infinite;animation:tui_ani 1.4s ease-in-out infinite;-webkit-animation-fill-mode:both;animation-fill-mode:both;background-color:var(--thorui-color-success);border-radius:",[0,36],";display:inline-block;height:",[0,36],";width:",[0,36],"}\n.",[1],"thorui-loading__2 .",[1],"thorui-ani__1{-webkit-animation-delay:-.3s;animation-delay:-.3s}\n.",[1],"thorui-loading__2 .",[1],"thorui-ani__2{-webkit-animation-delay:-.15s;animation-delay:-.15s}\n.",[1],"tui-title_demo{box-sizing:border-box;color:#e03232;font-size:",[0,32],";text-align:center;width:100%}\n.",[1],"tui-page__bd{padding-bottom:20px}\n.",[1],"tui-chart-title{box-sizing:border-box;color:#888;font-size:",[0,28],";padding:",[0,30]," 0;text-align:center;width:100%}\n.",[1],"tui-content-word{background-color:#fff;color:#555;font-size:",[0,42],";padding:",[0,20]," ",[0,30],"}\n.",[1],"tui-attr-box{background-color:#fff;border-radius:",[0,20],";box-sizing:border-box;font-size:0;width:100%}\n.",[1],"tui-attr-item{-webkit-align-items:center;align-items:center;background:#fcedea;border:",[0,1]," solid #fcedea;border-radius:",[0,32],";box-sizing:border-box;display:-webkit-inline-flex;display:inline-flex;font-size:",[0,26],";height:",[0,64],";-webkit-justify-content:center;justify-content:center;margin:",[0,10],";max-width:100%;min-width:",[0,110],";padding:0 ",[0,20],"}\n.",[1],"tui-attr-item wx-text{font-weight:700;padding-left:",[0,12],"}\n.",[1],"tui-bottom-title{box-sizing:border-box;color:#5677fc;font-size:",[0,32],";padding:",[0,40]," 0;text-align:center;width:100%}\n.",[1],"tui-new-label{border-top-left-radius:",[0,12],";height:",[0,80],";position:absolute;right:0;top:0;width:",[0,60],"}\n.",[1],"icon-ask{height:",[0,100],";opacity:.8;width:",[0,100],"}\n.",[1],"icon-recorder{height:",[0,140],";opacity:.8;width:",[0,140],";z-index:999}\n.",[1],"icon-voice{height:",[0,100],";opacity:.8;width:",[0,100],"}\n.",[1],"icon-recording{height:",[0,240],";width:",[0,240],"}\n.",[1],"icon-star{height:",[0,120],";width:",[0,120],"}\n.",[1],"icon-add{height:",[0,100],";opacity:.8;width:",[0,100],"}\n.",[1],"tui-modal-custom{text-align:center}\n.",[1],"tui-tips-img{height:",[0,80],";margin-top:",[0,20],";width:",[0,80],"}\n.",[1],"tui-modal-custom-text{color:#333;font-size:",[0,30],";padding:",[0,30]," 0}\n.",[1],"tui-prompt-title{font-size:",[0,34],";padding-bottom:",[0,20],"}\n.",[1],"tui-modal-input{border-bottom:",[0,1]," solid #e6e6e6;font-size:",[0,32],";margin:",[0,30]," auto ",[0,50],";width:80%}\n.",[1],"tui-hidden-input{width:0}\n.",[1],"tui-text{font-size:",[0,30],";padding-left:",[0,12],"}\n.",[1],"popup-text{height:120px;width:300px}\n.",[1],"tui-new-label-progress{-webkit-align-items:center;align-items:center;background:#f1f1f1;height:",[0,60],";-webkit-justify-content:center;justify-content:center;opacity:.6}\n.",[1],"word-text{font-family:Arial,Microsoft YaHei,黑体,宋体,sans-serif;font-size:",[0,48],"}\n.",[1],"tui-rate-container{-webkit-align-items:center;align-items:center;background:#fff;box-sizing:border-box;display:-webkit-flex;display:flex;font-size:",[0,30],";-webkit-justify-content:space-between;justify-content:space-between;margin-left:",[0,30],";margin-right:",[0,30],";margin-top:",[0,30],";padding:",[0,40],"}\n.",[1],"tui-title{font-size:",[0,48],";margin-left:",[0,180],"}\n.",[1],"icon-yanhua{height:",[0,100],";width:",[0,100],"}\n.",[1],"title-display{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;-webkit-justify-content:center;justify-content:center}\n.",[1],"chart-title{font-size:large;font-weight:700;padding:",[0,40]," ",[0,30]," ",[0,30],"}\n.",[1],"chart-progress-box,.",[1],"chart-title{-webkit-align-items:center;align-items:center;box-sizing:border-box;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;width:100%}\n.",[1],"chart-progress-box{padding:0 ",[0,30],"}\n.",[1],"chart-progress-text{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;height:130px;-webkit-justify-content:center;justify-content:center;left:0;padding-top:",[0,40],";position:absolute;top:0;width:100%}\n.",[1],"chart-progress-num{font-size:",[0,60],";padding-top:",[0,20],"}\n.",[1],"header{box-sizing:border-box;padding:",[0,60],"}\n.",[1],"title{color:#333;font-size:",[0,34],";font-weight:500}\n.",[1],"sub-title{color:#7a7a7a;font-size:",[0,24],";padding-top:",[0,18],"}\n.",[1],"tui-btn__box{display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;width:100%}\n.",[1],"tui-product-title{-webkit-flex-direction:row;flex-direction:row}\n.",[1],"tui-product-title,.",[1],"tui-product-title1{-webkit-align-items:center;align-items:center;background:#6f8af7;border-radius:",[0,50],";display:-webkit-flex;display:flex;font-size:",[0,60],";font-weight:500;height:",[0,108],";-webkit-justify-content:center;justify-content:center;opacity:.7;width:66%;z-index:99}\n.",[1],"tui-product-title1{-webkit-flex-direction:column;flex-direction:column}\n.",[1],"title1-text{font-family:Arial,Microsoft YaHei,黑体,宋体,sans-serif;font-size:",[0,64],"}\n.",[1],"popup-recording{-webkit-align-items:center;align-items:center;border-radius:6%;color:#fff;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;height:100%;-webkit-justify-content:center;justify-content:center;width:100%;z-index:9999}\n.",[1],"icon-recording{height:",[0,360],";width:",[0,360],"}\n.",[1],"pop-view{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;-webkit-justify-content:center;justify-content:center}\n.",[1],"popup-text{color:#fff;-webkit-flex-direction:row;flex-direction:row;height:",[0,240],"}\n.",[1],"popup-text,.",[1],"result-text{-webkit-align-items:center;align-items:center;border-radius:6%;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;width:",[0,600],"}\n.",[1],"result-text{height:",[0,200],"}\n.",[1],"value-text{font-family:Times New Roman,Times,serif;font-size:",[0,300],";font-style:italic;font-weight:700}\n.",[1],"thorui-flex__center,.",[1],"tui-item__row{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center}\n.",[1],"tui-item__row{color:#fff;font-size:",[0,26],";width:45%}\n.",[1],"tui-color__white{background-color:#fff;color:#000}\n.",[1],"tui-new-label-progress{bottom:",[0,0],";display:-webkit-inline-flex;display:inline-flex;height:",[0,16],";left:",[0,0],";opacity:.8;position:absolute;width:100%}\n.",[1],"tui-new-label-text{-webkit-align-items:center;align-items:center;border-radius:12%;display:-webkit-flex;display:flex;height:",[0,40],";-webkit-justify-content:center;justify-content:center;position:absolute;right:",[0,0],";top:",[0,0],";width:",[0,60],"}\n.",[1],"tui-container-study{box-sizing:border-box;padding:",[0,10],";width:100%}\n.",[1],"tui-extend-item{word-wrap:break-word;background:#dfeaf3;border-radius:",[0,20],";box-sizing:border-box;color:#fff;font-family:Microsoft YaHei;margin-bottom:",[0,30],";margin-left:",[0,24],";text-align:justify;word-break:break-all}\n.",[1],"tui-title-study{box-sizing:border-box;color:#fff;font-size:",[0,48],";font-weight:500;padding:",[0,30]," 0;text-align:center;width:100%}\n.",[1],"flex__between{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;-webkit-justify-content:space-between;justify-content:space-between;width:95%}\n.",[1],"word-mode-title{box-sizing:border-box;color:#888;font-size:",[0,30],";font-weight:500;padding:",[0,20],";width:100%}\n.",[1],"safearea-bottom{height:",[0,120],"}\n.",[1],"tui-logo{height:",[0,72],";width:",[0,72],"}\n.",[1],"tui-logo,.",[1],"tui-logo1{-webkit-flex-shrink:0;flex-shrink:0}\n.",[1],"tui-logo1{height:",[0,120],";width:",[0,120],"}\n.",[1],"pindu_container{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;padding:",[0,20],"}\n.",[1],"message{color:red;font-size:",[0,32],";margin-bottom:",[0,20],";opacity:0;transition:opacity .3s}\n.",[1],"message.",[1],"show{opacity:1}\n.",[1],"input-area{display:-webkit-flex;display:flex;-webkit-flex-wrap:wrap;flex-wrap:wrap;gap:",[0,10],";-webkit-justify-content:center;justify-content:center;margin-bottom:",[0,40],";margin-top:",[0,20],"}\n.",[1],"input-area.",[1],"completed{-webkit-animation:celebrate .5s ease-in-out;animation:celebrate .5s ease-in-out}\n@-webkit-keyframes celebrate{0%{opacity:1;-webkit-transform:scale(1);transform:scale(1)}\n50%{opacity:.7;-webkit-transform:scale(1.2);transform:scale(1.2)}\n100%{opacity:1;-webkit-transform:scale(1);transform:scale(1)}\n}@keyframes celebrate{0%{opacity:1;-webkit-transform:scale(1);transform:scale(1)}\n50%{opacity:.7;-webkit-transform:scale(1.2);transform:scale(1.2)}\n100%{opacity:1;-webkit-transform:scale(1);transform:scale(1)}\n}.",[1],"letter-box{-webkit-align-items:center;align-items:center;border:",[0,2]," solid #333;box-sizing:border-box;color:#333;display:-webkit-flex;display:flex;font-size:",[0,64],";-webkit-justify-content:center;justify-content:center;margin-top:",[0,20],";text-align:center}\n.",[1],"letter-box.",[1],"empty{color:#ccc}\n.",[1],"letter-box.",[1],"highlight{background-color:#ffeb3b;border-color:#f44336;transition:background-color .3s,border-color .3s}\n.",[1],"letters-area{-webkit-flex-wrap:wrap;flex-wrap:wrap;gap:",[0,15],";margin-bottom:",[0,40],"}\n.",[1],"letter-btn,.",[1],"letters-area{display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center}\n.",[1],"letter-btn{-webkit-align-items:center;align-items:center;background-color:#f0f0f0;border:",[0,2]," solid #333;border-radius:",[0,10],";box-sizing:border-box;font-size:",[0,64],";height:",[0,120],"}\n.",[1],"letter-btn[disabled]{background-color:#ccc;opacity:.5}\n.",[1],"confetti-gif{height:",[0,240],";pointer-events:none;position:absolute;width:",[0,240],";z-index:5}\n.",[1],"tui-word-container{-webkit-flex-direction:row;flex-direction:row;-webkit-justify-content:space-between;justify-content:space-between;width:100%}\n.",[1],"tui-word-button,.",[1],"tui-word-container{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;min-height:",[0,120],"}\n.",[1],"tui-word-button{background-color:#fff;border-radius:",[0,20],";box-shadow:0 ",[0,8]," ",[0,20]," rgba(0,0,0,.08);font-size:",[0,56],";-webkit-justify-content:center;justify-content:center;margin:",[0,8],";transition:-webkit-transform .1s ease;transition:transform .1s ease;transition:transform .1s ease,-webkit-transform .1s ease;width:50%}\n.",[1],"tui-word-button:active{background-color:#fafafa;box-shadow:0 ",[0,4]," ",[0,10]," rgba(0,0,0,.05);-webkit-transform:scale(.96);transform:scale(.96)}\n.",[1],"gif-icon{height:",[0,62],";width:",[0,74],"}\n.",[1],"tui-new-label-gif{border-radius:12%;height:",[0,64],";left:",[0,10],";position:absolute;top:",[0,10],";width:",[0,76],"}\n.",[1],"poster-container,.",[1],"tui-new-label-gif{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center}\n.",[1],"poster-container{background-color:rgba(0,0,0,.7);-webkit-flex-direction:column;flex-direction:column;height:100vh;left:0;position:fixed;top:0;width:100vw;z-index:9999}\n.",[1],"poster-img{border-radius:",[0,16],";box-shadow:0 ",[0,12]," ",[0,32]," rgba(0,0,0,.3);height:",[0,1080],";width:",[0,600],"}\n.",[1],"save-btn{background-color:#ff9800;border-radius:",[0,40],";color:#fff;font-size:",[0,30],";margin-top:",[0,40],";width:",[0,400],";z-index:10000}\n.",[1],"hidden-canvas{height:540px;left:-9999px;position:absolute;top:-9999px;width:300px;z-index:-1}\n.",[1],"close-btn{-webkit-align-items:center;align-items:center;background-color:hsla(0,0%,100%,.25);border-radius:50%;color:#fff;display:-webkit-flex;display:flex;font-size:",[0,44],";font-weight:300;height:",[0,60],";-webkit-justify-content:center;justify-content:center;line-height:1;position:absolute;right:",[0,52],";top:",[0,50],";width:",[0,60],";z-index:10001}\n.",[1],"close-btn:active{background-color:hsla(0,0%,100%,.4)}\n.",[1],"download-icon{height:",[0,78],";width:",[0,78],"}\n.",[1],"tui-new-label-download{-webkit-align-items:center;align-items:center;border-radius:12%;display:-webkit-flex;display:flex;height:",[0,90],";-webkit-justify-content:center;justify-content:center;left:",[0,6],";position:absolute;top:",[0,6],";width:",[0,90],"}\n",],"Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./pages/word/word.wxss:1:69)",{path:"./pages/word/word.wxss"});
}