$gwx_XC_32=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx_XC_32 || [];
function gz$gwx_XC_32_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx_XC_32_1)return __WXML_GLOBAL__.ops_cached.$gwx_XC_32_1
__WXML_GLOBAL__.ops_cached.$gwx_XC_32_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'honor-page'])
Z([3,'header'])
Z([a,[[7],[3,'year']],[3,' 年 '],[[7],[3,'month']],[3,' 月']])
Z([[7],[3,'empty_report']])
Z(z[1])
Z([3,'本月暂无任何学习记录'])
Z([3,'honor-wall'])
Z([3,'honor-card'])
Z([a,[3,'background:'],[[6],[[7],[3,'bgColors']],[1,0]]])
Z([3,'card-header'])
Z([3,'card-left'])
Z([3,'icon'])
Z([3,'https://qianyufang.top/public/yingyu/images/honor/mic.png'])
Z([3,'title'])
Z([3,'Keep Going!'])
Z([3,'top3'])
Z([3,'subtitle'])
Z([a,[3,'本月平均每天学习'],[[7],[3,'month_avarge']],[3,'课，学完'],[[7],[3,'level_cur']],[3,'级还需'],[[7],[3,'level_days']],[3,'天']])
Z([3,'#ff9b6a'])
Z([3,'#f3f3f3'])
Z([3,'#ff7900'])
Z([[7],[3,'level_progress']])
Z([3,'10'])
Z(z[7])
Z([a,z[8][1],[[6],[[7],[3,'bgColors']],[1,1]]])
Z(z[9])
Z(z[10])
Z(z[11])
Z([3,'https://qianyufang.top/public/yingyu/images/honor/calendar.png'])
Z(z[13])
Z([3,'执行力'])
Z(z[15])
Z(z[16])
Z([a,[3,'本月学习天数：'],[[7],[3,'month_days']],[3,'/'],[[7],[3,'cur_days']],[3,' 天，本月打卡率：'],[[7],[3,'month_daka_rate']]])
Z(z[18])
Z([[7],[3,'month_daka_star']])
Z([3,'true'])
Z(z[22])
Z([[7],[3,'star_size']])
Z([[2,'!='],[[7],[3,'plan_id']],[1,'']])
Z([3,'goPlan'])
Z(z[16])
Z([a,[3,'['],[[7],[3,'plan_title']],[3,']']])
Z(z[16])
Z([a,[3,'总计打卡：'],[[7],[3,'plan_days_normal']],z[33][3],[[7],[3,'plan_days_cur']],[3,' 天，整体完成率：'],[[7],[3,'plan_finish_rate']]])
Z(z[18])
Z([[7],[3,'month_plan_star']])
Z(z[36])
Z(z[22])
Z(z[38])
Z(z[7])
Z([a,z[8][1],[[6],[[7],[3,'bgColors']],[1,2]]])
Z(z[9])
Z(z[10])
Z(z[11])
Z([3,'https://qianyufang.top/public/yingyu/images/honor/book.png'])
Z(z[13])
Z([3,'学习内容'])
Z(z[15])
Z(z[16])
Z([a,[3,'本月完成学习'],[[7],[3,'month_cards']],[3,'课，共'],[[7],[3,'month_cards_times']],[3,'次']])
Z(z[16])
Z([a,[3,'其中'],z[17][4],[3,'级占比'],[[7],[3,'level_cur_ratio']]])
Z([[7],[3,'level_second']])
Z([a,[3,'，'],[[7],[3,'level_second']],z[62][3],[[7],[3,'level_second_ratio']]])
Z([3,'cu-list grid col-3'])
Z([[7],[3,'cardList']])
Z([3,'index'])
Z([3,'goCardStudy'])
Z([3,'cu-card'])
Z([[6],[[7],[3,'item']],[3,'_id']])
Z([3,'cu-item'])
Z([[6],[[7],[3,'item']],[3,'cover']])
Z([3,'width:100%;height:300rpx;'])
Z([3,'bg-macron tui-new-label-text text-center text-white text-sm'])
Z([a,[[6],[[7],[3,'item']],[3,'num']],z[60][5]])
Z([3,'text-cut text-sm'])
Z([a,[[6],[[7],[3,'item']],[3,'level']],[3,': '],[[6],[[7],[3,'item']],[3,'title']]])
Z(z[7])
Z([a,z[8][1],[[6],[[7],[3,'bgColors']],[1,3]]])
Z(z[9])
Z(z[10])
Z(z[11])
Z([3,'https://qianyufang.top/public/yingyu/images/honor/test.png'])
Z(z[13])
Z([3,'开口能力'])
Z(z[15])
Z(z[16])
Z([a,[3,'开口次数'],[[7],[3,'month_speak_num']],[3,'次，说出单词'],[[7],[3,'month_speak_words']],[3,'个']])
Z([[7],[3,'speakList']])
Z(z[67])
Z([3,'goCardShare'])
Z([3,'flex align-center'])
Z([[7],[3,'index']])
Z([3,'text-cut'])
Z([3,'width:33%;'])
Z([3,'text-gray'])
Z([a,z[77][1],[3,':'],z[77][3]])
Z([3,'star-speak'])
Z([3,'citem'])
Z([[6],[[7],[3,'item']],[3,'stars']])
Z(z[67])
Z([3,'icon-star-speak'])
Z([[2,'?:'],[[2,'>'],[[7],[3,'citem']],[1,3]],[1,'https://qianyufang.top/public/yingyu/images/icon/star_icon.png'],[1,'https://qianyufang.top/public/yingyu/images/icon/star_gray.png']])
Z([3,'record-play'])
Z([3,'record-play-icon'])
Z([3,'https://qianyufang.top/public/yingyu/images/icon/voice.png'])
Z([3,'subtitle margin-top-sm'])
Z([a,[3,'熟练通过'],[[7],[3,'words_right']],[3,'个，仍需练习'],[[7],[3,'words_wrong']],z[88][5]])
Z([3,'padding'])
Z([3,'onClick'])
Z([3,'300'])
Z([3,'tui_pie_1'])
Z([[7],[3,'legend']])
Z([3,'掌握程度'])
Z([[2,'>'],[[6],[[7],[3,'speak_words_wrong_list']],[3,'length']],[1,0]])
Z([3,'wrong-words-list'])
Z([[7],[3,'speak_words_wrong_list']])
Z([3,'clickWordExtend'])
Z(z[93])
Z([3,'12rpx'])
Z(z[120])
Z([3,'1.1'])
Z([3,'circle'])
Z([3,'32rpx'])
Z([3,'light-orange'])
Z([a,[[6],[[7],[3,'item']],[3,'_id']]])
Z([3,'#f7f7f7'])
Z([3,'已经到底部了'])
Z([3,'tui-safearea-bottom'])
})(__WXML_GLOBAL__.ops_cached.$gwx_XC_32_1);return __WXML_GLOBAL__.ops_cached.$gwx_XC_32_1
}
__WXML_GLOBAL__.ops_set.$gwx_XC_32=z;
__WXML_GLOBAL__.ops_init.$gwx_XC_32=true;
var x=['./pages/report/report.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx_XC_32_1()
var aDNC=_n('view')
_rz(z,aDNC,'class',0,e,s,gg)
var eFNC=_n('view')
_rz(z,eFNC,'class',1,e,s,gg)
var bGNC=_oz(z,2,e,s,gg)
_(eFNC,bGNC)
_(aDNC,eFNC)
var tENC=_v()
_(aDNC,tENC)
if(_oz(z,3,e,s,gg)){tENC.wxVkey=1
var oHNC=_n('view')
_rz(z,oHNC,'class',4,e,s,gg)
var xINC=_oz(z,5,e,s,gg)
_(oHNC,xINC)
_(tENC,oHNC)
}
var oJNC=_n('view')
_rz(z,oJNC,'class',6,e,s,gg)
var fKNC=_mz(z,'view',['class',7,'style',1],[],e,s,gg)
var cLNC=_n('view')
_rz(z,cLNC,'class',9,e,s,gg)
var hMNC=_n('view')
_rz(z,hMNC,'class',10,e,s,gg)
var oNNC=_mz(z,'image',['class',11,'src',1],[],e,s,gg)
_(hMNC,oNNC)
var cONC=_n('text')
_rz(z,cONC,'class',13,e,s,gg)
var oPNC=_oz(z,14,e,s,gg)
_(cONC,oPNC)
_(hMNC,cONC)
_(cLNC,hMNC)
_(fKNC,cLNC)
var lQNC=_n('view')
_rz(z,lQNC,'class',15,e,s,gg)
var aRNC=_n('view')
_rz(z,aRNC,'class',16,e,s,gg)
var tSNC=_oz(z,17,e,s,gg)
_(aRNC,tSNC)
_(lQNC,aRNC)
var eTNC=_mz(z,'tui-progress',['showInfo',-1,'activeColor',18,'backgroundColor',1,'color',2,'percent',3,'width',4],[],e,s,gg)
_(lQNC,eTNC)
_(fKNC,lQNC)
_(oJNC,fKNC)
var bUNC=_mz(z,'view',['class',23,'style',1],[],e,s,gg)
var oVNC=_n('view')
_rz(z,oVNC,'class',25,e,s,gg)
var xWNC=_n('view')
_rz(z,xWNC,'class',26,e,s,gg)
var oXNC=_mz(z,'image',['class',27,'src',1],[],e,s,gg)
_(xWNC,oXNC)
var fYNC=_n('text')
_rz(z,fYNC,'class',29,e,s,gg)
var cZNC=_oz(z,30,e,s,gg)
_(fYNC,cZNC)
_(xWNC,fYNC)
_(oVNC,xWNC)
_(bUNC,oVNC)
var h1NC=_n('view')
_rz(z,h1NC,'class',31,e,s,gg)
var c3NC=_n('view')
_rz(z,c3NC,'class',32,e,s,gg)
var o4NC=_oz(z,33,e,s,gg)
_(c3NC,o4NC)
_(h1NC,c3NC)
var l5NC=_mz(z,'tui-rate',['active',34,'current',1,'disabled',2,'quantity',3,'size',4],[],e,s,gg)
_(h1NC,l5NC)
var o2NC=_v()
_(h1NC,o2NC)
if(_oz(z,39,e,s,gg)){o2NC.wxVkey=1
var a6NC=_n('view')
_rz(z,a6NC,'bind:tap',40,e,s,gg)
var t7NC=_n('view')
_rz(z,t7NC,'class',41,e,s,gg)
var e8NC=_oz(z,42,e,s,gg)
_(t7NC,e8NC)
_(a6NC,t7NC)
var b9NC=_n('view')
_rz(z,b9NC,'class',43,e,s,gg)
var o0NC=_oz(z,44,e,s,gg)
_(b9NC,o0NC)
_(a6NC,b9NC)
var xAOC=_mz(z,'tui-rate',['active',45,'current',1,'disabled',2,'quantity',3,'size',4],[],e,s,gg)
_(a6NC,xAOC)
_(o2NC,a6NC)
}
o2NC.wxXCkey=1
o2NC.wxXCkey=3
_(bUNC,h1NC)
_(oJNC,bUNC)
var oBOC=_mz(z,'view',['class',50,'style',1],[],e,s,gg)
var fCOC=_n('view')
_rz(z,fCOC,'class',52,e,s,gg)
var cDOC=_n('view')
_rz(z,cDOC,'class',53,e,s,gg)
var hEOC=_mz(z,'image',['class',54,'src',1],[],e,s,gg)
_(cDOC,hEOC)
var oFOC=_n('text')
_rz(z,oFOC,'class',56,e,s,gg)
var cGOC=_oz(z,57,e,s,gg)
_(oFOC,cGOC)
_(cDOC,oFOC)
_(fCOC,cDOC)
_(oBOC,fCOC)
var oHOC=_n('view')
_rz(z,oHOC,'class',58,e,s,gg)
var lIOC=_n('view')
_rz(z,lIOC,'class',59,e,s,gg)
var aJOC=_oz(z,60,e,s,gg)
_(lIOC,aJOC)
_(oHOC,lIOC)
var tKOC=_n('view')
_rz(z,tKOC,'class',61,e,s,gg)
var bMOC=_oz(z,62,e,s,gg)
_(tKOC,bMOC)
var eLOC=_v()
_(tKOC,eLOC)
if(_oz(z,63,e,s,gg)){eLOC.wxVkey=1
var oNOC=_oz(z,64,e,s,gg)
_(eLOC,oNOC)
}
eLOC.wxXCkey=1
_(oHOC,tKOC)
_(oBOC,oHOC)
var xOOC=_n('view')
_rz(z,xOOC,'class',65,e,s,gg)
var oPOC=_v()
_(xOOC,oPOC)
var fQOC=function(hSOC,cROC,oTOC,gg){
var oVOC=_mz(z,'view',['bindtap',68,'class',1,'data-id',2],[],hSOC,cROC,gg)
var lWOC=_n('view')
_rz(z,lWOC,'class',71,hSOC,cROC,gg)
var aXOC=_mz(z,'image',['src',72,'style',1],[],hSOC,cROC,gg)
var tYOC=_n('view')
_rz(z,tYOC,'class',74,hSOC,cROC,gg)
var eZOC=_oz(z,75,hSOC,cROC,gg)
_(tYOC,eZOC)
_(aXOC,tYOC)
_(lWOC,aXOC)
var b1OC=_n('view')
_rz(z,b1OC,'class',76,hSOC,cROC,gg)
var o2OC=_oz(z,77,hSOC,cROC,gg)
_(b1OC,o2OC)
_(lWOC,b1OC)
_(oVOC,lWOC)
_(oTOC,oVOC)
return oTOC
}
oPOC.wxXCkey=2
_2z(z,66,fQOC,e,s,gg,oPOC,'item','index','index')
_(oBOC,xOOC)
_(oJNC,oBOC)
var x3OC=_mz(z,'view',['class',78,'style',1],[],e,s,gg)
var o4OC=_n('view')
_rz(z,o4OC,'class',80,e,s,gg)
var f5OC=_n('view')
_rz(z,f5OC,'class',81,e,s,gg)
var c6OC=_mz(z,'image',['class',82,'src',1],[],e,s,gg)
_(f5OC,c6OC)
var h7OC=_n('text')
_rz(z,h7OC,'class',84,e,s,gg)
var o8OC=_oz(z,85,e,s,gg)
_(h7OC,o8OC)
_(f5OC,h7OC)
_(o4OC,f5OC)
_(x3OC,o4OC)
var c9OC=_n('view')
_rz(z,c9OC,'class',86,e,s,gg)
var lAPC=_n('view')
_rz(z,lAPC,'class',87,e,s,gg)
var aBPC=_oz(z,88,e,s,gg)
_(lAPC,aBPC)
_(c9OC,lAPC)
var tCPC=_v()
_(c9OC,tCPC)
var eDPC=function(oFPC,bEPC,xGPC,gg){
var fIPC=_mz(z,'view',['bindtap',91,'class',1,'data-id',2],[],oFPC,bEPC,gg)
var cJPC=_mz(z,'view',['class',94,'style',1],[],oFPC,bEPC,gg)
var hKPC=_n('text')
_rz(z,hKPC,'class',96,oFPC,bEPC,gg)
var oLPC=_oz(z,97,oFPC,bEPC,gg)
_(hKPC,oLPC)
_(cJPC,hKPC)
_(fIPC,cJPC)
var cMPC=_n('view')
_rz(z,cMPC,'class',98,oFPC,bEPC,gg)
var oNPC=_v()
_(cMPC,oNPC)
var lOPC=function(tQPC,aPPC,eRPC,gg){
var oTPC=_mz(z,'image',['class',102,'src',1],[],tQPC,aPPC,gg)
_(eRPC,oTPC)
return eRPC
}
oNPC.wxXCkey=2
_2z(z,100,lOPC,oFPC,bEPC,gg,oNPC,'citem','index','index')
_(fIPC,cMPC)
var xUPC=_n('view')
_rz(z,xUPC,'class',104,oFPC,bEPC,gg)
var oVPC=_mz(z,'image',['class',105,'src',1],[],oFPC,bEPC,gg)
_(xUPC,oVPC)
_(fIPC,xUPC)
_(xGPC,fIPC)
return xGPC
}
tCPC.wxXCkey=2
_2z(z,89,eDPC,e,s,gg,tCPC,'item','index','index')
var fWPC=_n('view')
_rz(z,fWPC,'class',107,e,s,gg)
var cXPC=_oz(z,108,e,s,gg)
_(fWPC,cXPC)
_(c9OC,fWPC)
var hYPC=_n('view')
_rz(z,hYPC,'class',109,e,s,gg)
var oZPC=_mz(z,'tui-charts-pie',['bindclick',110,'diam',1,'id',2,'legend',3,'title',4],[],e,s,gg)
_(hYPC,oZPC)
_(c9OC,hYPC)
var o0OC=_v()
_(c9OC,o0OC)
if(_oz(z,115,e,s,gg)){o0OC.wxVkey=1
var c1PC=_n('view')
_rz(z,c1PC,'class',116,e,s,gg)
var o2PC=_v()
_(c1PC,o2PC)
var l3PC=function(t5PC,a4PC,e6PC,gg){
var o8PC=_mz(z,'tui-tag',['bindclick',118,'data-id',1,'margin',2,'padding',3,'scaleMultiple',4,'shape',5,'size',6,'type',7],[],t5PC,a4PC,gg)
var x9PC=_oz(z,126,t5PC,a4PC,gg)
_(o8PC,x9PC)
_(e6PC,o8PC)
return e6PC
}
o2PC.wxXCkey=4
_2z(z,117,l3PC,e,s,gg,o2PC,'item','index','')
_(o0OC,c1PC)
}
o0OC.wxXCkey=1
o0OC.wxXCkey=3
_(x3OC,c9OC)
_(oJNC,x3OC)
_(aDNC,oJNC)
tENC.wxXCkey=1
_(r,aDNC)
var o0PC=_mz(z,'tui-nomore',['backgroundColor',127,'text',1],[],e,s,gg)
_(r,o0PC)
var fAQC=_n('view')
_rz(z,fAQC,'class',129,e,s,gg)
_(r,fAQC)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx_XC_32";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx_XC_32();	if (__vd_version_info__.delayedGwx) __wxAppCode__['pages/report/report.wxml'] = [$gwx_XC_32, './pages/report/report.wxml'];else __wxAppCode__['pages/report/report.wxml'] = $gwx_XC_32( './pages/report/report.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['pages/report/report.wxss']=setCssToHead([".",[1],"honor-page{background-color:#fafafa;padding:",[0,20],"}\n.",[1],"header{color:#4b4b4b;font-size:",[0,48],";font-weight:700;margin-bottom:",[0,20],";text-align:center}\n.",[1],"subtitle{color:#555;font-size:",[0,32],";padding-bottom:",[0,10],";padding-top:",[0,10],"}\n.",[1],"honor-wall{display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;gap:",[0,24],"}\n.",[1],"honor-card{border-radius:",[0,20],";box-shadow:0 ",[0,4]," ",[0,10]," rgba(0,0,0,.05);margin-bottom:",[0,10],";padding:",[0,24],";width:100%}\n.",[1],"card-header{-webkit-justify-content:space-between;justify-content:space-between}\n.",[1],"card-header,.",[1],"card-header .",[1],"card-left{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"card-header .",[1],"card-left{gap:",[0,10],"}\n.",[1],"card-header .",[1],"icon{height:",[0,40],";width:",[0,40],"}\n.",[1],"card-header .",[1],"title{font-size:",[0,34],";font-weight:600}\n.",[1],"top3{margin-top:",[0,10],";width:100%}\n.",[1],"top3,.",[1],"top3 .",[1],"rank-item{display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column}\n.",[1],"top3 .",[1],"rank-item{-webkit-align-items:center;align-items:center}\n.",[1],"top3 .",[1],"rank-item .",[1],"rank{font-size:",[0,32],";margin-bottom:",[0,4],"}\n.",[1],"top3 .",[1],"rank-item .",[1],"avatar{border:",[0,4]," solid #fff;border-radius:50%;box-shadow:0 ",[0,2]," ",[0,6]," rgba(0,0,0,.1);height:",[0,80],";margin-bottom:",[0,6],";width:",[0,80],"}\n.",[1],"top3 .",[1],"rank-item .",[1],"name{color:#333;font-size:",[0,26],";margin-bottom:",[0,4],"}\n.",[1],"top3 .",[1],"rank-item .",[1],"value{color:#666;font-size:",[0,24],"}\n.",[1],"tui-legend__box{display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;-webkit-flex-wrap:wrap;flex-wrap:wrap}\n.",[1],"tui-legend__item{-webkit-align-items:center;align-items:center;box-sizing:border-box;display:-webkit-flex;display:flex;font-size:",[0,28],";margin-bottom:",[0,20],";margin-left:",[0,24],";padding-left:",[0,30],"}\n.",[1],"tui-legend__circle{border-radius:50%;-webkit-flex-shrink:0;flex-shrink:0;height:",[0,20],";margin-right:",[0,8],";width:",[0,20],"}\n.",[1],"tui-flex-box{-webkit-align-items:flex-start;align-items:flex-start;-webkit-justify-content:flex-start;justify-content:flex-start;margin-bottom:",[0,26],";width:100%}\n.",[1],"tui-flex-box,.",[1],"wrong-words-list{display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;-webkit-flex-wrap:wrap;flex-wrap:wrap}\n.",[1],"wrong-words-list{padding-bottom:",[0,20],";padding-left:",[0,12],";padding-right:",[0,20],"}\n.",[1],"tui-safearea-bottom{height:env(safe-area-inset-bottom);width:100%}\n.",[1],"record-play{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;z-index:99}\n.",[1],"record-play-icon{height:",[0,54],";width:",[0,54],"}\n.",[1],"star-speak{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;height:",[0,80],";-webkit-justify-content:center;justify-content:center;width:100%;z-index:1}\n.",[1],"icon-star-speak{height:",[0,52],";width:",[0,52],"}\n.",[1],"tui-new-label-text{-webkit-align-items:center;align-items:center;border-radius:12%;display:-webkit-flex;display:flex;height:",[0,34],";-webkit-justify-content:center;justify-content:center;position:absolute;right:",[0,0],";top:",[0,0],";width:",[0,56],"}\n",],undefined,{path:"./pages/report/report.wxss"});
}